### ISSUE TITLE
Fatal Error - Could not open the preferences file

### ISSUE THREAD

**Issue by apocsantos** [fatg3erman/RompR#100]
After configuring my USB Soundcard, RompR just answers with "Fatal Error - Could not open the preferences file" and it no longer serves the web page.

Any hint solving this issue ?

Regards

**Comment by fatg3erman** [comment]
I don't know how setting up a USB sound card could cause that, but the error means it can't open the prefs file, which is at rompr/prefs/prefs.var.

I suggest you check the read/write permissions on the prefs folder.

**Comment by apocsantos** [comment]
Hi,

Not sure either but it is how it happend! Anywho, file in rompr/prefs/prefs.var is rw to everyone on the system, and is also empty.

Regards

**Comment by fatg3erman** [comment]
Empty? That's not right. Check the permissions of the prefs directory itself....

Actually, tell you what, make sure the prefs directory and eveything in it is rw to everybody, then delete the prefs file and try again.

**Comment by apocsantos** [comment]
Hi,

Thank you!

It worked! Still dont know why, the permissions changed, cause it is in the home directory of my user, so, no system update would change anything..

**Comment by fatg3erman** [comment]
If the file was empty it could also mean that php-fpm crashed or was forcibly closed while rompr was writing to it. Perhaps a system upgrade caused that, although it shouldn't.
