### ISSUE TITLE
"Player Error: Failed to open "My Alsa Device"

### ISSUE THREAD

**Issue by apocsantos** [fatg3erman/RompR#101]
Hi,

Eveyrhting set right, I'm able to play music using omxplayer, but using Rompr it shows the error "Player Error: Failed to Open "My ALSA Device" (alsa); Failed to open ALSA Device "default": No such File or Directory

Command line to play:
`omxplayer -o alsa:hw:1,0  --no-osd -b 'Ava Max   Kings  Queens [Official Music Video].mp3'`

**Comment by fatg3erman** [comment]
You need to read up on how to configure mpd. That error is because mpd can't open the sound card. That's nothing to do with omxplayer at all, and nothing to do with rompr either.
