### ISSUE TITLE
Track "Panel" empty if tracklist too long

### ISSUE THREAD

**Issue by count00zero** [fatg3erman/RompR#102]
HI there and THANK YOU for your great RompR :)

I have an issue, since my "playlist" (playing my whole music library with mpd; visualizing with rompr) has grown a bit.
If I select a small playlist in the playlist panel and let mpd play it; all the tracks are visible in the playlist panel also the currently played track (see screen 1) including all the playing file info which is available (spotify, wikipedia, etc.)

When I load my whole music library (whole playlist) ~39800 playable songs, the playlist panel empties out and I get no currently played song info nor can I select wikipedia, spotify, etc.). <- screen 2.

Could you think of any reason for that behaviour?

THANKS a lot and BR,
count

![Screen 1](https://user-images.githubusercontent.com/14225157/93221936-9f578e00-f76e-11ea-9c4e-861498e3bf5b.jpg)
![Screen 2](https://user-images.githubusercontent.com/14225157/93221950-a2eb1500-f76e-11ea-87a5-50b699f2a90d.jpg)

**Comment by fatg3erman** [comment]
The playlist is too big and the web server is timing out before RompR has a chance to retrieve all of it.

The one thing I never, ever, expected people to do was have enormous playlists. I wrote RompR because I *hate* playlists :-D

RompR has plenty of better ways to play your entire collection on shuffle if that is what you want to do. Loading a playlist that large will *never* work.

**Comment by count00zero** [comment]
Hi and thanks for your reply.
I did the "playlist part" just to be able to repoduce it.
I have the same effect when I just fire up my mpd-daemon with my configured music_directory and then browse to my rompr installation.
I also tried to find something with the full debug log, but was unable to find the problem.

Using 
latest rompr.git source (but also tried earlier releases)
mpd: 0.22~git (v0.21.25-1114-ge8380cf2a)
mpc: version: 0.34

**Comment by fatg3erman** [comment]
OK I'm sorry but your explanation is not making any sense.

The first image above shows it all working correctly.

Please describe *EXACTLY* what you did to produce the second image. Do not assume anything, describe in detail every single thing you did. Because your two posts, currently, are contradicting each other.

**Comment by count00zero** [comment]
OK, I'll try to do that (start from scratch)
Let's assume I restart my mpd daemon service (with my configured music_directory) and the music starts playing.
mpc output:

> music/Kidneythieves/Zerospace (2002)/12 - Placebo.mp3
> [playing] #25823/38196   0:08/6:40 (2%)
> volume:100%   repeat: off   random: on    single: off   consume: off

Then I surf to my rompr installation and what I see (doesn't change over time) is this:
![Screen 2](https://user-images.githubusercontent.com/14225157/93256592-d7c19100-f79b-11ea-82f6-8175867837ea.jpg)

THEN I try to see if rompr works, load a small playlist and voila: 
![Screen 1](https://user-images.githubusercontent.com/14225157/93256691-fd4e9a80-f79b-11ea-9cb8-9c3fe7c2ba88.jpg)

That's the whole story :)

**Comment by fatg3erman** [comment]
OK thanks, that makes sense now, though I still don't understand why the title of this Issue is 'if playlist too long'?

I've just tried what you described and could not reproduce the problem, so what I need is a debug log, at level 7, of the case where you start RompR and it doesn't display any information.

https://fatg3erman.github.io/RompR/Troubleshooting#debug-logging

The Debug Information would also be useful:

https://fatg3erman.github.io/RompR/Troubleshooting#reporting-bugs

**Comment by count00zero** [comment]
Debug Info:
`
* **BACKEND INFO**
  * **Version** 1.51
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host** 
  * **proxy_password** 
  * **proxy_user** 
  * **spotify_token** 
  * **spotify_token_expires** 
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 10.0.0.33
  * **SERVER_NAME** *removed*
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /opt/www
  * **HTTP_HOST** *removed*
  * **HTTP_USER_AGENT** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
  * **REMOTE_ADDR** *removed*
  * **SERVER_PORT** 443
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **currenthost** AMD
  * **skin** desktop
  * **player_backend** mpd
* **PHP INFO**
  * **Version** 7.4.10
  * **mbstring** 7.4.10
  * **PDO** 7.4.10
  * **pdo_mysql** 7.4.10
  * **pdo_sqlite** 7.4.10
  * **curl** 7.4.10
  * **date** 7.4.10
  * **fileinfo** 7.4.10
  * **json** 7.4.10
  * **SimpleXML** 7.4.10
  * **GD** 7.4.10
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=*removed*
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=120, local_value=120, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=syslog, local_value=syslog, access=7
  * **error_reporting** global_value=22519, local_value=22519, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=4096M, local_value=4096M, access=7
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock, local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.22.0
  * **music_directory** /mnt/USB/musicmirror
  * **tagtype** Artist, Album, Title, Track, Genre, Date
  * **Commands** add, addid, addtagid, albumart, channels, clear, clearerror, cleartagid, close, commands, config, consume, count, crossfade, currentsong, decoders, delete, deleteid, delpartition, disableoutput, enableoutput, find, findadd, idle, kill, list, listall, listallinfo, listfiles, listmounts, listpartitions, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, moveoutput, newpartition, next, notcommands, outputs, outputset, partition, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readcomments, readmessages, readpicture, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, sticker, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **URL Handlers** file://
  * **URL Handlers** alsa://
  * **URL Handlers** cdda://
  * **URL Handlers** ftp://
  * **URL Handlers** ftps://
  * **URL Handlers** gopher://
  * **URL Handlers** http://
  * **URL Handlers** https://
  * **URL Handlers** mms://
  * **URL Handlers** mmsh://
  * **URL Handlers** mmst://
  * **URL Handlers** mmsu://
  * **URL Handlers** nfs://
  * **URL Handlers** rtmp://
  * **URL Handlers** rtmps://
  * **URL Handlers** rtmpt://
  * **URL Handlers** rtmpts://
  * **URL Handlers** rtp://
  * **URL Handlers** scp://
  * **URL Handlers** sftp://
  * **URL Handlers** smb://
  * **URL Handlers** srtp://
  * **plugin** mad, mpg123, vorbis, oggflac, flac, opus, sndfile, audiofile, dsdiff, dsf, faad, mpcdec, wavpack, modplug, mikmod, sidplay, fluidsynth, adplug, ffmpeg, gme, pcm
  * **suffix** mp3, mp2, mp3, ogg, oga, ogg, oga, flac, opus, ogg, oga, wav, aiff, aif, au, snd, paf, iff, svx, sf, voc, w64, pvf, xi, htk, caf, sd2, wav, au, aiff, aif, dff, dsf, aac, mpc, wv, 669, amf, ams, dbm, dfm, dsm, far, it, med, mdl, mod, mtm, mt2, okt, s3m, stm, ult, umx, xm, amf, dsm, far, gdm, imf, it, med, mod, mtm, s3m, stm, stx, ult, uni, xm, sid, mus, str, prg, P00, mid, amd, d00, hsc, laa, rad, raw, sa2, 16sv, 3g2, 3gp, 4xm, 8svx, aa3, aac, ac3, adx, afc, aif, aifc, aiff, al, alaw, amr, anim, apc, ape, asf, atrac, au, aud, avi, avm2, avs, bap, bfi, c93, cak, cin, cmv, cpk, daud, dct, divx, dts, dv, dvd, dxa, eac3, film, flac, flc, fli, fll, flx, flv, g726, gsm, gxf, iss, m1v, m2v, m2t, m2ts, m4a, m4b, m4v, mad, mj2, mjpeg, mjpg, mka, mkv, mlp, mm, mmf, mov, mp+, mp1, mp2, mp3, mp4, mpc, mpeg, mpg, mpga, mpp, mpu, mve, mvi, mxf, nc, nsv, nut, nuv, oga, ogm, ogv, ogx, oma, ogg, omg, opus, psp, pva, qcp, qt, r3d, ra, ram, rl2, rm, rmvb, roq, rpl, rvc, shn, smk, snd, sol, son, spx, str, swf, tak, tgi, tgq, tgv, thp, ts, tsp, tta, xa, xvid, uv, uv2, vb, vid, vob, voc, vp6, vmd, wav, webm, wma, wmv, wsaud, wsvga, wv, wve, ay, gbs, gym, hes, kss, nsf, nsfe, sap, spc, vgm, vgz
  * **mime_type** audio/mpeg, application/ogg, application/x-ogg, audio/ogg, audio/vorbis, audio/vorbis+ogg, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, application/ogg, application/x-ogg, audio/ogg, audio/x-flac+ogg, audio/x-ogg, application/flac, application/x-flac, audio/flac, audio/x-flac, audio/ogg, application/ogg, audio/opus, audio/wav, audio/aiff, audio/x-wav, audio/x-aiff, audio/wav, audio/aiff, audio/x-wav, audio/x-aiff, application/x-dff, audio/x-dff, audio/x-dsd, application/x-dsf, audio/x-dsf, audio/x-dsd, audio/aac, audio/aacp, audio/x-wavpack, application/flv, application/m4a, application/mp4, application/octet-stream, application/ogg, application/x-ms-wmz, application/x-ms-wmd, application/x-ogg, application/x-shockwave-flash, application/x-shorten, audio/8svx, audio/16sv, audio/aac, audio/aacp, audio/ac3, audio/aiff, audio/amr, audio/basic, audio/flac, audio/m4a, audio/mp4, audio/mpeg, audio/musepack, audio/ogg, audio/opus, audio/qcelp, audio/vorbis, audio/vorbis+ogg, audio/wav, audio/x-8svx, audio/x-16sv, audio/x-aac, audio/x-ac3, audio/x-adx, audio/x-aiff, audio/x-alaw, audio/x-au, audio/x-dca, audio/x-eac3, audio/x-flac, audio/x-gsm, audio/x-mace, audio/x-matroska, audio/x-monkeys-audio, audio/x-mpeg, audio/x-ms-wma, audio/x-ms-wax, audio/x-musepack, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, audio/x-pn-realaudio, audio/x-pn-multirate-realaudio, audio/x-speex, audio/x-tta, audio/x-voc, audio/x-wav, audio/x-wma, audio/x-wv, video/anim, video/quicktime, video/msvideo, video/ogg, video/theora, video/webm, video/x-dv, video/x-flv, video/x-matroska, video/x-mjpeg, video/x-mpeg, video/x-ms-asf, video/x-msvideo, video/x-ms-wmv, video/x-ms-wvx, video/x-ms-wm, video/x-ms-wmx, video/x-nut, video/x-pva, video/x-theora, video/x-vid, video/x-wmv, video/x-xvid, audio/x-mpd-ffmpeg, audio/L16, audio/L24, audio/x-mpd-float, audio/x-mpd-cdda-pcm, audio/x-mpd-cdda-pcm-reverse, audio/x-mpd-alsa-pcm
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **music_directory_albumart** /mnt/USB/musicmirror
  * **sortbycomposer** true
  * **composergenre** true
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** AT
  * **country_userset** true
  * **debug_enabled** 7
  * **custom_logfile** /var/log/rompr/rompr.log
  * **cleanalbumimages** false
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **multihosts** AMD=[host=10.0.0.33, port=6600, password=, socket=/run/mpd/socket, mopidy_remote=false, radioparams=[radiomode=, radioparam=, radiomaster=, radioconsume=0]]
  * **dev_mode** false
  * **live_mode** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1600690253984
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mpd
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **displaycomposer** true
  * **artistsatstart** 0=
  * **nosortprefixes** 0=
  * **sortcollectionby** album
  * **sortresultsby** sameas
  * **actuallysortresultsby** album
  * **google_api_key** 
  * **google_search_engine_id** 
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **last_lastfm_synctime** 1600085449000
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **sortbydate** true
  * **notvabydate** true
  * **currenthost** AMD
  * **player_backend** mpd
  * **collectionrange** 0
  * **lastfm_user** 
  * **lastfm_session_key** 
  * **autotagname** 
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** lastfm
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** double
  * **chooser** albumlist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** true
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.51
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **user_lang** en
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Modern-Dark
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 1
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1600266064811
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **bgimgparms** dummy=baby
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1600085546161
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1600239725823
  * **next_podcast_refresh** 1602204668879
  * **use_original_releasedate** true
  * **mpd_host** 10.0.0.33
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** /run/mpd/socket
  * **collection_type** mysql
  * **separate_collections** false
  * **mopidy_http_port** false
  * **hide_pluginplaylistslist** true
  * **language** en
  * **skin** desktop
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode** 
  * **radioparam** 
  * **radiomaster** 
  * **radioconsume** 0
`
Debug-Log:
[rompr.log](https://github.com/fatg3erman/RompR/files/5232782/rompr.log)

**Comment by fatg3erman** [comment]
It's a little difficult to be certain but what I can tell from the log is that you have a very large number of saved playlists and the processing of them simply stops. This could be due to the webserver timing out, or it could be running out of memory. What I really need to see is the web server error logs and the php (or php-fpm depending on your setup) error logs to find out what's causing it to stop, but I suspect it's not going to be something fixable.

Also you are still contradicting yourself. You say this is not to do with the tracklist but then you change the title to "If tracklist too long". How many tracks are in your tracklist when this happens?

**Comment by count00zero** [comment]
Thank's for the Info, I will look into that!

When I changed to the most recent version of mpd it started to build playlists, which it hadn't done in the past.
Maybe that's the reason.

Regarding the "tracklist" I am simply out of words to describe it the right way ;-)
I mean the list of tracks, which are defined within mpd.conf (music_directory) and which are in my playqueue and randomly sorted.

But maybe that's just a side effect. Because I even can't see the currently played song, which bugs me a bit more ...

**Comment by count00zero** [comment]
Just out of curiosity, i created the missing "/opt/www/rompr/newimages/thisdoesntexist.png"
And now I see this (see screen 3):
![Screen 3](https://user-images.githubusercontent.com/14225157/93662788-f60ce280-fa62-11ea-8c71-37ad67660af6.jpg)

**Comment by fatg3erman** [comment]
OK I'll try to rephrase the question one more time. How many tracks are in your play queue?

Or in other words, if the panel on the right was working, how many tracks would it contain?

**Comment by count00zero** [comment]
Based on mpc there would be 37484 tracks in my play queue

**Comment by fatg3erman** [comment]
Then I refer you back to the very first answer I gave you.

Rompr will not work with a play queue that long.

**Comment by count00zero** [comment]
OK, got it. Thanks a lot for your time and patience!
