### ISSUE TITLE
can't browse file directories

### ISSUE THREAD

**Issue by tidux** [fatg3erman/RompR#103]
Clicking on a directory in the file browser adds it to the playlist.  I expected that to open the folder so I could browse tracks individually, like basically any other music player with a file API.  My music collection has folders nested several deep, typically genre/artist/album/, so this is not desired behavior.

**Comment by fatg3erman** [comment]
Which skin?

**Comment by tidux** [comment]
Desktop skin, Darkness theme, circled light icons.

**Comment by fatg3erman** [comment]
You have t click the triangle next to it, not the item itself. You'rw not trying to do this on a small touch screen are you? That'll never work with the desktop skin. That's why it's called the desktop skin.

**Comment by tidux** [comment]
No, a 24" desktop monitor.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by fatg3erman** [comment]
Don't know what's going on then. Works for me. You sure you're clicking the triangle icon? Clicking the text will add it to the playlist, that's how it's supposed to work.

**Comment by tidux** [comment]
I figured it out.  It's an issue with some of the icon themes.  A right pointing arrow with a circle around it is the icon for both "expand this folder" and "windows media audio file".  Changing icon themes cleared up the ambiguity.
