### ISSUE TITLE
Error adding files from SMB Share

### ISSUE THREAD

**Issue by RolandWiebe** [fatg3erman/RompR#104]
I have several MPD instances running all over my house. The main music collection is located on my TrueNAS server. 
The MPD instances are configured to access the music collection via SMB which is configured directly in the mpd.conf files via`music_directory "smb://truenas.local/music" `. 
The music collection is shown properly in RompR, but when I want to add a title or complete album to the playlist I get an error message: `Player Error:{} No such directory`. 
Using another MPD client on my smartphone adding and playing files work just fine.
Changing the music directoy to a local folder or mounted fileshare works well.
So there seems to be an issue with the SMB share integration in MPD together with RompR.
`

**Comment by fatg3erman** [comment]
At a guess I'd say this is to do with SMB not supporting the full UTF-8 character set that is required for it to work in a browser, but without a debug log there is very little I can do.

**Comment by RolandWiebe** [comment]
[RomR debug log.txt](https://github.com/fatg3erman/RompR/files/5584557/RomR.debug.log.txt)
You are totally right. Here is the debug log I created whe the issue happens.

**Comment by RolandWiebe** [comment]
Forcing the TrueNAS SMB shares to be case insensitive fixed the issue.

**Comment by fatg3erman** [comment]
I'm only adding the path that MPD reports to me, so that's very strange indeed. I run it on case-sensitive filesystems all the time. Maybe MPD is not case-sensitive? Something of a mystery, but glad you found a way to resolve it.

Out of interest, it would be interesting to see what MPD returns if you telnet to your MPD and type

    lsinfo "/"

**Comment by RolandWiebe** [comment]
Here the output as requested:

```Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
OK MPD 0.21.4
lsinfo "/"
directory: roland
Last-Modified: 2020-11-23T15:43:33Z
playlist: ULTRA-[laradiofm.com]
Last-Modified: 2020-03-09T07:05:40Z
playlist: hr3_2
Last-Modified: 2020-03-09T07:05:40Z
playlist: bayern3_2
Last-Modified: 2020-03-09T07:05:40Z
playlist: rockantenne
Last-Modified: 2020-03-09T07:05:40Z
playlist: Radiosender
Last-Modified: 2020-04-27T12:26:58Z
OK
```

**Comment by fatg3erman** [comment]
Hmmm. So MPD is saying the directory name is a lower case 'r'.

However, could you now do

    lsinfo "roland"

and then

    lsinfo "roland/10 Years - Division"

I'd just like to see where the capital R is coming from. I can't see that it would be me, but currently it is a mystery.. :)

**Comment by RolandWiebe** [comment]
I  shortened the output a little bit, but I think you'll get the information you need.
```
lsinfo "roland"      
file: roland/Set It Off - This Christmas (I'll Burn It To The Ground).mp3
Last-Modified: 2015-12-25T06:46:37Z
Format: 44100:f:2
Time: 210
duration: 210.000
directory: roland/10 Years - Division
Last-Modified: 2017-06-16T12:31:35Z
...
```

```
lsinfo "roland/10 Years - Division"  
file: roland/10 Years - Division/01 - Actions & Motives.mp3
Last-Modified: 2013-08-11T17:49:41Z
Format: 44100:f:2
Time: 203
duration: 203.000
Artist: 10 Years
Album: Division
AlbumArtist: 10 Years
Title: Actions & Motives
Track: 1
Genre: Rock
Date: 2008
Composer: 10 Years
file: roland/10 Years - Division/02 - Just Can't Win.mp3
Last-Modified: 2013-08-11T17:49:41Z
Format: 44100:f:2
Time: 214
duration: 214.000
Artist: 10 Years
Album: Division
AlbumArtist: 10 Years
Title: Just Can't Win
Track: 2
Genre: Rock
Date: 2008
Composer: 10 Years
...
```

**Comment by fatg3erman** [comment]
Well... Obviously no capital R's there :)

Has the folder been renamed? Has it had a capital 'R' at some point in the past? The only explanation for what's happening is that the file has a capital 'R' in Rompr's database. Some database implementations are case insensitive. I can't see anywhere in the code where that could happen though, so it must have happened when the database was created in the first place.

**Comment by RolandWiebe** [comment]
All my MPD instances were using a mounted NFS share to the local filesystem as music directory.
Today I moved to the MPD integated SMB storage plugin as I'm moving all my data to a new server which is running TrueNAS.
The old NFS share was indeed with an capital 'R' in the directory name. The new SMB share uses lower case "r" for the directory. 
After changing the music directory I triggered to udpdate the database. Well, I thought the update will clean all references to the old fileshare. 

In between I also restarted the apache where RompR is running. Maybe this is the reason I don't get the captial "R" any more. 
Furthermore I remove also the workaround in the TrueNAS SMB shares and it still works.

I did the test and switched back to the NFS share, restart MPD and updated the mpd database in RompR but I cannot get the issue again. Updating the MPD database this time just worked.
Maybe something just got stuck in my transition from the old server to the new one.

**Comment by fatg3erman** [comment]
There's a lot of issues with case sensitivity across different file shares. NFS is always case sensitive. SMB usually isn't, and I wonder if MPD's implementation assumes it isn't. Then there's the issue that some implementations of databases are case insensitive and would not regard 'roland' as being the same as 'Roland' and would not update even when asked to. I suspect one or other or a combination of those as at the root of the problem. I just did a test here and renamed a directory to lower case and my install of MPD is now reporting the lower case *and* the upper case one that no longer exists!

In general RompR is very happy for you to move your music to wherever you like, as it doesn't regard the URI as the thing that identifies a track, but you seem to have found the edge case where it doesn't work. I doubt we'll ever be certain what caused it, but I'm glad it's working now.
