### ISSUE TITLE
INSTALL.txt needs an update

### ISSUE THREAD

**Issue by dtrace4linux** [fatg3erman/RompR#105]
The link for doing an upgrade is

http://sourceforge.net/p/rompr/wiki/Installation/

but that link doesnt exist. Presume everything is here on github?

**Comment by fatg3erman** [comment]
Where is that link? Yes everything is now on github.

**Comment by dtrace4linux** [comment]
INSTALL.txt - was trying to figure out how to upgrade. Did it manually by
copying over some files.

BTW - you are a brilliant person. rompr is such a brilliant utility.

RompR-1.48//INSTALL.txt
==================
= Installing RompR
==================
Please read the installation instructions here:

http://sourceforge.net/p/rompr/wiki/Installation/

MacOS X Users
=============

Please read the instructions here:

http://sourceforge.net/p/rompr/wiki/Installation%20on%20Mac%20OS%20X/

Windows Users
=============

First, install a better operating system, then read this file again :)
Actually, it may well be possible to get this to run on Windows, if mpd or
mopidy
can be got
to work then there's probably a LAMP stack for Windows that will run apache
and ph
p
OK. But I don't intend to go buy a Windows computer just to find out.
