### ISSUE TITLE
radio: something went wrong retrieving the playlist

### ISSUE THREAD

**Issue by jimydirektsaft** [fatg3erman/RompR#106]
Adding a radio station to the playlist fails with "something went wrong retrieving the playlist".

* **BACKEND INFO**
  * **Version** 1.53
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host** [Redacted]
  * **lastfm_session_key** [Redacted]
  * **spotify_token** [Redacted]
  * **spotify_token_expires** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /utils/debuginfo.php
  * **SERVER_ADDR** 172.16.253.2
  * **SERVER_NAME** _
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /app/rompr
  * **HTTP_HOST** dietpi:81
  * **HTTP_USER_AGENT** Mozilla/5.0 (X11; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0
  * **REMOTE_ADDR** 172.16.254.54
  * **SERVER_PORT** 80
  * **REQUEST_URI** /utils/debuginfo.php
* **COOKIES**
  * **currenthost** mopidy
  * **skin** desktop
  * **sessionid-P4MKV** gKZ6GoEmbAGPNp3jHm7TSfWeAYduvcfR
  * **CSRF-Token-P4MKV** ANqhMuRgTC2WnJJcggf7HK9YekWTwev9
  * **io** hyry8YnPsu2RwPwVAAAA
  * **XSRF-TOKEN** eyJpdiI6Im03RkEwNmZWSUM4XC9VaDRKUW9nY0FRPT0iLCJ2YWx1ZSI6ImlnQ0dwM2paWTljSmJZbmVXb1hQT09hcE5qWXBCUXhkaDFXUmh0SGFzMElBN0s2eWU5NnNUTGNjTjE0Unp4alIiLCJtYWMiOiJiN2IxYWFjMzY4MWEyOWNkNDEyNjY2ZjliNWUyZGNhMDU2YmYxZDIzNjVlNWIxN2Y5OGZkNGE0Njk5ZGExNzhlIn0=
  * **heimdall_session** eyJpdiI6IldcL2xPcExueDQ0dlZZY0NcL2hHZDNLdz09IiwidmFsdWUiOiIraUZiR3dYd1RrNTdcLzdNT2JaaW9uMkNIMkt0TVVHSVwva1RKSjVxanZseDVnKzNwNDM1M29DRVMyblwvSk5CcE9WIiwibWFjIjoiNTdjYTI4ODA0ZDUyMDZiMDYzMzc2NWFiNTIzM2M4ZTljMjJkOWUyODAxMmU2NzczMDc1M2Y3MDJmZWIxMzZiMSJ9
  * **_ga** GA1.1.1366810629.1613846110
  * **_gid** GA1.1.386863640.1613846110
  * **player_backend** mopidy
* **PHP INFO**
  * **Version** 7.4.15
  * **mbstring** 7.4.15
  * **PDO** 7.4.15
  * **pdo_mysql** 7.4.15
  * **pdo_sqlite** 7.4.15
  * **curl** 7.4.15
  * **date** 7.4.15
  * **fileinfo** 7.4.15
  * **json** 7.4.15
  * **SimpleXML** 7.4.15
  * **GD** 7.4.15
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=1, local_value=1, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock, local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Artist, ArtistSort, Album, AlbumArtist, AlbumArtistSort, Title, Track, Name, Genre, Date, Composer, Performer, Disc, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_TRACKID, X-AlbumUri, X-AlbumImage
  * **Commands** add, addid, addtagid, channels, clear, clearerror, cleartagid, close, commands, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, list, listall, listallinfo, listfiles, listmounts, listneighbors, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, next, notcommands, outputs, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** beets
  * **URL Handlers** bookmark
  * **URL Handlers** file
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** internetarchive
  * **URL Handlers** local
  * **URL Handlers** m3u
  * **URL Handlers** mixcloudsimple
  * **URL Handlers** mms
  * **URL Handlers** podcast
  * **URL Handlers** podcast+file
  * **URL Handlers** podcast+http
  * **URL Handlers** podcast+https
  * **URL Handlers** rtmp
  * **URL Handlers** rtmps
  * **URL Handlers** rtsp
  * **URL Handlers** sc
  * **URL Handlers** somafm
  * **URL Handlers** soundcloud
  * **URL Handlers** spotify
  * **URL Handlers** tunein
  * **URL Handlers** youtube
  * **URL Handlers** yt
  * **URL Handlers** ytmusic
* **CONFIG**
  * **rgbs** r=100, g=50, b=1, a=1
  * **skin** desktop
  * **music_directory_albumart** /archive
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** true
  * **mopidy_collection_folders** 0=Local media
  * **lastfm_country_code** DE
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** /debug/log.txt
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** true
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1614346023954
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** /archive/audiobooks
  * **collection_player** mopidy
  * **snapcast_server** dietpi
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 
  * **multihosts** mopidy=[host=localhost, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=, radiomaster=, radioconsume=0]]
  * **old_style_sql** false
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** albumbyartist
  * **sortresultsby** album
  * **actuallysortresultsby** album
  * **sync_lastfm_playcounts** true
  * **sync_lastfm_at_start** true
  * **next_lastfm_synctime** 1613850956207
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 1600823823
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** mopidy
  * **player_backend** mopidy
  * **collectionrange** 3
  * **lastfm_user** [Redacted]
  * **autotagname** 
  * **lastfm_logged_in** true
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** discogs
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** double
  * **chooser** radiolist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.53
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** VariableLight.css
  * **icontheme** Modern-Light
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1613811926138
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 3
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1613679792894
  * **playlistbuttons_isopen** true
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1613828474663
  * **next_podcast_refresh** 1614150927127
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby
  * **last_lastfm_synctime** 1613847356207
  * **google_api_key** 
  * **google_search_engine_id** 
  * **user_lang** en
  * **collection_type** sqlite
  * **collectioncontrolsvisible** true
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** 
  * **separate_collections** false
  * **mopidy_http_port** false
  * **interface_language** en-GB
  * **maxrgbs** r=255, g=75, b=1, a=1
  * **bgdrgbs** r=0, g=0, b=0, a=0
  * **radiomode** 
  * **radioparam** 
  * **radiomaster** 
  * **radioconsume** 0
[debug-log.txt](https://github.com/fatg3erman/RompR/files/6016221/debug-log.txt)

**Comment by fatg3erman** [comment]
Thanks for providing the logs, but I can't see the error and can't reproduce the problem. Are you using a custom logfile in rompr? Those don't contain php error messages or webserver messages, and it's those I need to see.

**Comment by jimydirektsaft** [comment]
Oh - sorry, I missed that the custom logfile is not sufficient.
Below you can see the output in the nginx error log when this error occurs.

`2021/02/21 11:30:25 [error] 22#22: *190 FastCGI sent in stderr: "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /app/rompr/collection/playlistcollection.class.php on line 22" while reading response header from upstream, client: 172.16.254.58, server: _, request: "GET /api/tracklist/?_=1613903250979 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "dietpi:81", referrer: "http://dietpi:81/"`

**Comment by fatg3erman** [comment]
I still can't reproduce the problem. Can you try something? Edit line 22 of rompr/collection/playlistcollection.class.php so it reads

`		if (is_array($filedata['Artist']) && count($filedata['Artist']) > 1) {
`

That ought to fix it, but I don't know if the same issue might occur somewhere else. I think it might be something to do with you running a different version of PHP than me so I can't test it.

**Comment by jimydirektsaft** [comment]
Yes this change eliminates the problem.
Which is the recommended php version for RompR?

**Comment by jimydirektsaft** [comment]
I switched to php7.3 as a test, but the problem also arises with that.

**Comment by fatg3erman** [comment]
There isn't a reccomended version, it should work. I'm using 7.3 and can't reproduce the problem. Are you adding the radio station using mopidy-tunein, or are you using Rompr's tunein browser?

The fix as it stands is fine, I'm just curious as to why it is needed.

**Comment by jimydirektsaft** [comment]
I understand that.
I'm adding the radio station with Rompr.

**Comment by jimydirektsaft** [comment]
When I add the radio station to the playlist with mopidy, Rompr updates the playlist without any error.

**Comment by jimydirektsaft** [comment]
I'm sorry
accidentally closed

**Comment by fatg3erman** [comment]
I'm going to close it because I have fixed it. I'm not sure about why it needed fixing, but I can't be bothered to figure that out either :)

**Comment by jimydirektsaft** [comment]
Greate!
Just updated to 1.55 :)
