### ISSUE TITLE
setup screen appears on errors which can only be recovered if you have access to the UI

### ISSUE THREAD

**Issue by akamming** [fatg3erman/RompR#107]
Hi,

1st of  my compliments for creating and maintaining RompR.  It's a great interface for MPD, Mopidy and Snapcast! I built a multiroom internetradio using Rompr, Snapcast and Mopidy

just wanted te report an issue in the error handling: If there is any error on MPD or Mopidy, i cannot access the UI anymore. 

On some errors this is correct (e.g. mpd or mopidy not running), but there are several errors (like this example: there is an error in the internet radio stream) i cannot get past the setup screen and the only way te recover the error is to use another MPD client to switch to another internet radio station.:

![image](https://user-images.githubusercontent.com/30364409/108968867-9e158000-7681-11eb-8fb9-27defbfa791d.png)

Could you make a fix that with errrors like this are presented in the UI instead of going to setup screen?

(PS I tested with latest RompR version: I can reporoduce on MPD and Mopidy)

**Comment by fatg3erman** [comment]
Is this a radio station you have previously tried to play using a different client?

Rompr will always display any error in the UI during normal operation and then it will clear the error. Always. The presence of an error flag from mpd at connect time is the only way I can check for connection problems.

The only way I can see this happening is if you tried to add this station using a different client that does not clear errors correctly.

**Comment by akamming** [comment]
No,  it was played using rompr.

basically what happens is 
1. On my handset i open a URL to RompR to select an internet radio station 
2. The "radio" starts playing
3. i am listening for several hours to that station until it stops
4. I reopen RompR on my handset (or laptop) and then only can get in the setup screen showing the error

the only reason i installed another mpd (a android app which i only open in case of this error) was as a workaround to recover from this error, so i can access rompr again

I'm not 100% sure, but i think i have seen this error as well when not using rompr for quite some time (a few days) and the last played item was an internet source

**Comment by fatg3erman** [comment]
OK I understand what is happening.

That's going to be a difficult one to fix though, because like I say the 'error' flag from MPD can indicate a genuine connection error so I absolutely have to act on it. I'll look at what I can do but I'm not convinced that this is fixable.

**Comment by akamming** [comment]
ok... i understand what you are saying. 

If it is not fixable, would it be an option to always show the error in the UI and give the user an option (e.g. presenting a link in the error message) to go to setup page instead of automatically redirect to that page?

**Comment by fatg3erman** [comment]
I'm going to try to see what happens if I clear the error when the setup page appears. The danger is I get into an infinite loop of errors, but I'll do some experiments and see what happens.

**Comment by fatg3erman** [comment]
I think I can work around it. The main issue is that I can't even create the UI until I can connect to the player, so if there's an error I have to redirect. Sadly mpd doesn't have a defined list of errors so I need to do the same thing no matter what the error is. I'll post back when I have something.

**Comment by fatg3erman** [comment]
Fixed in version 1.55

**Comment by akamming** [comment]
Tx a lot! 

i'll install the new release and let you know if i encounter any new errors
