### ISSUE TITLE
Library discrepency between Mpd/Rompr

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#11]
What Mpc says (Mpd 0.20.20)
Artists:  11700
Albums:    7700
Songs:    78200

What Rompr says (1.15.5)
3300 artists
54800 tracks
6700 albums

```
Music Player Daemon 0.20.20

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient nfs curl

Neighbor plugins:
 smbclient upnp

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz

```

**Comment by fatg3erman** [comment]
I wouldn't place too much emphasis on those numbers being the same.

MPD's artist count includes all artists who appear only on compilations, Rompr's count only includes Album Artists. For similar reasons, what Rompr considers to be an album might not be the same as what MPD considers, Rompr does a lot of sorting. Rompr will also not include duplicate tracks (tracks with the same title, album, artist, and album artist).

That said if you can find a few tracks that are in your MPD library that aren't in Rompr's collection then we can do some investigation.

It will help if you enable debug logging (see the docs) and do a music sollection update.

**Comment by fatg3erman** [comment]
By the way, thanks for logging all this stuff, it really does help to have people reporting problems.

**Comment by gerroon** [comment]
@fatg3erman 
Thanks for the insight, I will look into this in more depth tos ee if I can catch the missing stuff though not so easy.

I am more happy when the devs respond to my reports.
