### ISSUE TITLE
music from everywhere fails to exclude sources

### ISSUE THREAD

**Issue by jimydirektsaft** [fatg3erman/RompR#112]
In `personalised radio > music from everywhere > play from these sources` select only "local".
Create a "Last.FM Lucky Dip"  playlist.

RompR selects tracks from the local library and from other sources.
In the attached [personalised-radio.log](https://github.com/fatg3erman/RompR/files/6136361/personalised-radio.log) you can see that one spotify track was added to the playlist.

**Comment by jimydirektsaft** [comment]
**debug information:**

* **BACKEND INFO**
  * **Version** 1.55
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host** [Redacted]
  * **lastfm_session_key** [Redacted]
  * **spotify_token** [Redacted]
  * **spotify_token_expires** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /utils/debuginfo.php
  * **SERVER_ADDR** 172.16.253.2
  * **SERVER_NAME** _
  * **SERVER_SOFTWARE** nginx/1.14.2
  * **DOCUMENT_ROOT** /app/rompr
  * **HTTP_HOST** dietpi:81
  * **HTTP_USER_AGENT** Mozilla/5.0 (X11; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0
  * **REMOTE_ADDR** 172.16.254.58
  * **SERVER_PORT** 80
  * **REQUEST_URI** /utils/debuginfo.php
* **COOKIES**
  * **currenthost** mopidy
  * **skin** desktop
  * **collectionrange** 1
  * **sortbydate** false
  * **sortresultsby** album
  * **actuallysortresultsby** album
  * **_ga** GA1.1.1615439118.1613574971
  * **sortcollectionby** album
  * **CSRF-Token-P4MKV** fMG7uGuEpg3Ao4xcqyLuzzsXqR4XqNaW
  * **io** L8Le5BDfNZkUsJy3AAAs
  * **sessionid-P4MKV** 3tSWVqqp9mAm3wXLbLsGaZvigM5xpDM5
  * **_gid** GA1.1.1723041145.1615710757
  * **player_backend** mopidy
  * **XSRF-TOKEN** eyJpdiI6IjZvNGtYakYxK1lJS1hXZTdTZ3BtWmc9PSIsInZhbHVlIjoiQUd2OExnM3RqZjdHeUpldUpySlU2UCtOZWRJK3V2VlwvcnNoVnZyQjlxM3ZqWDYzUDVyQmVhdkx5RWNMUEhRRVUiLCJtYWMiOiJjNmM3ZTUwZDkzMDRmOGJjZThiMDUxYzY2ZDUyNjlhYTM5NDAzOTlhN2RhMDA0NzE2Y2MwNGI2ODIwNGYxMjczIn0=
  * **heimdall_session** eyJpdiI6ImVGd2h4MXcwN3VVNUpITit5WDF0NVE9PSIsInZhbHVlIjoidGVnclhpemRYXC9uMjVcL1wveDVIZ0RkR010akFhZVh2U0pJSGNoZStQcEc2dWtlSDlXQzJ2bzVwb0VQdWlCMUVpMSIsIm1hYyI6IjIwNjhlYjkyOTJjNTM1MGRhZTJkZTczOTQ5NDAwYjZmMmY2OGZhOWZhODY2MWExMDJlM2NiYmJiZjNmMDc0MzAifQ==
* **PHP INFO**
  * **Version** 7.3.27-1~deb10u1
  * **mbstring** 7.3.27-1~deb10u1
  * **PDO** 7.3.27-1~deb10u1
  * **pdo_mysql** 7.3.27-1~deb10u1
  * **pdo_sqlite** 7.3.27-1~deb10u1
  * **curl** 7.3.27-1~deb10u1
  * **date** 7.3.27-1~deb10u1
  * **fileinfo** 7.3.27-1~deb10u1
  * **json** 1.7.0
  * **SimpleXML** 7.3.27-1~deb10u1
  * **GD** 7.3.27-1~deb10u1
  * **GD Info** GD Version=2.2.5, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=1, local_value=1, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock, local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Artist, ArtistSort, Album, AlbumArtist, AlbumArtistSort, Title, Track, Name, Genre, Date, Composer, Performer, Disc, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_TRACKID, X-AlbumUri, X-AlbumImage
  * **Commands** add, addid, addtagid, channels, clear, clearerror, cleartagid, close, commands, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, list, listall, listallinfo, listfiles, listmounts, listneighbors, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, next, notcommands, outputs, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** bandcamp
  * **URL Handlers** beets
  * **URL Handlers** bookmark
  * **URL Handlers** file
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** internetarchive
  * **URL Handlers** local
  * **URL Handlers** m3u
  * **URL Handlers** mixcloudsimple
  * **URL Handlers** mms
  * **URL Handlers** podcast
  * **URL Handlers** podcast+file
  * **URL Handlers** podcast+http
  * **URL Handlers** podcast+https
  * **URL Handlers** rtmp
  * **URL Handlers** rtmps
  * **URL Handlers** rtsp
  * **URL Handlers** sc
  * **URL Handlers** somafm
  * **URL Handlers** soundcloud
  * **URL Handlers** spotify
  * **URL Handlers** tunein
  * **URL Handlers** youtube
  * **URL Handlers** yt
  * **URL Handlers** ytmusic
* **CONFIG**
  * **rgbs** r=2, g=23, b=40, a=1
  * **skin** desktop
  * **music_directory_albumart** /archive
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** true
  * **mopidy_collection_folders** 0=Local media
  * **lastfm_country_code** DE
  * **country_userset** true
  * **debug_enabled** 8
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** true
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1615919272540
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** /archive/audiobooks
  * **collection_player** mopidy
  * **snapcast_server** dietpi
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 
  * **multihosts** mopidy=[host=localhost, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=null, radiomaster=1613811926138, radioconsume=[["consume","0"],["repeat","0"],["random","0"]]]]
  * **old_style_sql** false
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** album
  * **sortresultsby** album
  * **actuallysortresultsby** album
  * **sync_lastfm_playcounts** true
  * **sync_lastfm_at_start** true
  * **next_lastfm_synctime** 1615714144990
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 1600823823
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** mopidy
  * **player_backend** mopidy
  * **collectionrange** 1
  * **lastfm_user** [Redacted]
  * **autotagname** 
  * **lastfm_logged_in** true
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** true
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** spotify
  * **sourceswidthpercent** 33.58447371237383
  * **playlistwidthpercent** 22.476568132660418
  * **downloadart** true
  * **clickmode** double
  * **chooser** filelist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.55
  * **scrolltocurrent** true
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **synctags** true
  * **synclove** true
  * **synclovevalue** 5
  * **theme** VariableLight.css
  * **icontheme** Modern-Light
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** true
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 
  * **mopidy_radio_domains** 0=local
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** true
  * **communityradioorderby** name
  * **browser_id** 1604928052811
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 3
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1615578110179
  * **playlistbuttons_isopen** true
  * **collectionbuttons_isopen** true
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1615708297360
  * **next_podcast_refresh** 1615932181372
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby
  * **last_lastfm_synctime** 1615710544990
  * **google_api_key** 
  * **google_search_engine_id** 
  * **user_lang** en
  * **collection_type** sqlite
  * **collectioncontrolsvisible** true
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** 
  * **separate_collections** false
  * **mopidy_http_port** false
  * **interface_language** en-GB
  * **maxrgbs** r=200, g=200, b=200, a=1
  * **bgdrgbs** r=0, g=0, b=0, a=0
  * **radiomode** 
  * **radioparam** null
  * **radiomaster** 1613811926138
  * **radioconsume** [["consume","0"],["repeat","0"],["random","0"]]

**Comment by fatg3erman** [comment]
I'm completely unable to reproduce this under any circumstances.

Your log is extremely confusing. Please send one *at level 6* that starts when you activate the Last.FM radio station (tail it and pipe to another file, like in the docs).

**Comment by jimydirektsaft** [comment]
Ok - I found that happens if I've opened one browser with rompr, in which "local" is marked as source and a second browser with rompr, in which "local" and "spotify" are marked as sources. If I select the last.fm radio from the first browser with only "local" selected the playlist gets populated with tracks from local and from spotify. If I close the second browser (where "local" and "spotify" are selected) the playlist gets populated only with tracks from local.

Please find the trace log from the session with two open browsers in the attached file.

[logtrace.txt](https://github.com/fatg3erman/RompR/files/6217610/logtrace.txt)

**Comment by fatg3erman** [comment]
Essentially that is how it is supposed to work.

Populating the radio stations is decentralised - any open browser can do it. For that to make sense the browser has to honour the sources options selected, and that selection has to be honoured if it is changed during population. I can't change the options in one browser to match the other, because which ones are the "correct" ones? Honestly there's no reliable way to know.

The only correct "fix" for this, I'm afraid, is to make sure you select appropriate options in how ever many browsers you have open.

**Comment by jimydirektsaft** [comment]
That's reasonable. Thank you for your kind reply. From my user centric point of view I would suggest to sync the souces options between browsers (maybe by a preferences config option) but you already wrote that you can't change the options in one browser to match the other. So I think the current behaviour is a bit irritating but I absolutely can live with it. In any way RompR is a great thing! Thanks again!

**Comment by fatg3erman** [comment]
I'll leave this open to remind me to think about it, you never know, I might come up with something :)

**Comment by fatg3erman** [comment]
In version 1.57, just released, I've made a change that I think should fix this.
All browsers should now share the same radio source options. You will need to change them one, from any browser, for this to take effect.
