### ISSUE TITLE
domains undefined in widgets.js

### ISSUE THREAD

**Issue by Lionel642** [fatg3erman/RompR#116]
Hi;

I'm not sure why, but on my instance, using v1.57 I've got an error in : 
in widgets.js
setSelection: function(domains) 
domains is undefiend.

Simply adding a check for domains existence :

 if (**domains &&** domains.indexOf(d) > -1)

fixed it.

**Comment by fatg3erman** [comment]
That's very odd, as that check isn't there because it isn't possible for domains to be undefined :)

I'd very much like to see the information from the Debug Information plugin, as described in the troubleshooting docs.

**Comment by Lionel642** [comment]
tried to, removed the piece of code, can't reproduce, not much changed, I don't know. Will come back if it happens again.
