### ISSUE TITLE
wrong display of songs with accents

### ISSUE THREAD

**Issue by oupala** [fatg3erman/RompR#117]
I've been using RompR for a few days and I can see that songs with accents in their name are not well displayed on RompR.

There nothing special to reproduce, except having a look at the following screenshot:

![screenshot](https://user-images.githubusercontent.com/13458743/122939095-9b970e80-d373-11eb-89e5-04ebcc54b19b.png)

I'm using a quite default install of RompR, I've not set anything special in the settings.

Here are the debug informations from RompR:

* **BACKEND INFO**
  * **Version** 1.57
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /music/utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.11
  * **SERVER_NAME** [Redacted]
  * **SERVER_SOFTWARE** Apache
  * **DOCUMENT_ROOT** /var/www/[Redacted]
  * **HTTP_HOST** [Redacted]
  * **HTTP_USER_AGENT** Mozilla/5.0 (X11; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0
  * **REMOTE_ADDR** 161.106.4.5
  * **SERVER_PORT** 443
  * **REQUEST_URI** /music/utils/debuginfo.php
* **COOKIES**
  * **phpMp_config_lastsong** 34
  * **phpMp_config_playlist_focus** 34
  * **currenthost** Default
  * **skin** desktop
  * **player_backend** mpd
* **PHP INFO**
  * **Version** 7.3.27-1~deb10u1
  * **mbstring** 7.3.27-1~deb10u1
  * **PDO** 7.3.27-1~deb10u1
  * **pdo_mysql** 
  * **pdo_sqlite** 7.3.27-1~deb10u1
  * **curl** 7.3.27-1~deb10u1
  * **date** 7.3.27-1~deb10u1
  * **fileinfo** 7.3.27-1~deb10u1
  * **json** 1.7.0
  * **SimpleXML** 7.3.27-1~deb10u1
  * **GD** 
  * **ImageMagick** Not Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=30, local_value=30, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** [NOT SET]
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.21.4
  * **tagtype** Artist, ArtistSort, Album, AlbumSort, AlbumArtist, AlbumArtistSort, Title, Track, Name, Genre, Date, OriginalDate, Composer, Performer, Disc, Label, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_TRACKID, MUSICBRAINZ_RELEASETRACKID, MUSICBRAINZ_WORKID
  * **Commands** add, addid, addtagid, albumart, channels, clear, clearerror, cleartagid, close, commands, config, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, kill, list, listall, listallinfo, listfiles, listmounts, listpartitions, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, newpartition, next, notcommands, outputs, outputset, partition, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readcomments, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, sticker, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **URL Handlers** alsa://
  * **URL Handlers** http://
  * **URL Handlers** https://
  * **URL Handlers** gopher://
  * **URL Handlers** rtp://
  * **URL Handlers** rtsp://
  * **URL Handlers** rtmp://
  * **URL Handlers** rtmpt://
  * **URL Handlers** rtmps://
  * **URL Handlers** smb://
  * **URL Handlers** nfs://
  * **URL Handlers** mms://
  * **URL Handlers** mmsh://
  * **URL Handlers** mmst://
  * **URL Handlers** mmsu://
  * **URL Handlers** cdda://
  * **plugin** mad, mpg123, vorbis, oggflac, flac, opus, sndfile, audiofile, dsdiff, dsf, faad, mpcdec, wavpack, modplug, mikmod, sidplay, fluidsynth, adplug, ffmpeg, gme, pcm
  * **suffix** mp3, mp2, mp3, ogg, oga, ogg, oga, flac, opus, ogg, oga, wav, aiff, aif, au, snd, paf, iff, svx, sf, voc, w64, pvf, xi, htk, caf, sd2, wav, au, aiff, aif, dff, dsf, aac, mpc, wv, 669, amf, ams, dbm, dfm, dsm, far, it, med, mdl, mod, mtm, mt2, okt, s3m, stm, ult, umx, xm, amf, dsm, far, gdm, imf, it, med, mod, mtm, s3m, stm, stx, ult, uni, xm, sid, mus, str, prg, P00, mid, amd, d00, hsc, laa, rad, raw, sa2, 16sv, 3g2, 3gp, 4xm, 8svx, aa3, aac, ac3, adx, afc, aif, aifc, aiff, al, alaw, amr, anim, apc, ape, asf, atrac, au, aud, avi, avm2, avs, bap, bfi, c93, cak, cin, cmv, cpk, daud, dct, divx, dts, dv, dvd, dxa, eac3, film, flac, flc, fli, fll, flx, flv, g726, gsm, gxf, iss, m1v, m2v, m2t, m2ts, m4a, m4b, m4v, mad, mj2, mjpeg, mjpg, mka, mkv, mlp, mm, mmf, mov, mp+, mp1, mp2, mp3, mp4, mpc, mpeg, mpg, mpga, mpp, mpu, mve, mvi, mxf, nc, nsv, nut, nuv, oga, ogm, ogv, ogx, oma, ogg, omg, opus, psp, pva, qcp, qt, r3d, ra, ram, rl2, rm, rmvb, roq, rpl, rvc, shn, smk, snd, sol, son, spx, str, swf, tak, tgi, tgq, tgv, thp, ts, tsp, tta, xa, xvid, uv, uv2, vb, vid, vob, voc, vp6, vmd, wav, webm, wma, wmv, wsaud, wsvga, wv, wve, ay, gbs, gym, hes, kss, nsf, nsfe, sap, spc, vgm, vgz
  * **mime_type** audio/mpeg, application/ogg, application/x-ogg, audio/ogg, audio/vorbis, audio/vorbis+ogg, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, application/ogg, application/x-ogg, audio/ogg, audio/x-flac+ogg, audio/x-ogg, application/flac, application/x-flac, audio/flac, audio/x-flac, audio/ogg, application/ogg, audio/opus, audio/x-wav, audio/x-aiff, audio/x-wav, audio/x-aiff, application/x-dff, audio/x-dff, audio/x-dsd, application/x-dsf, audio/x-dsf, audio/x-dsd, audio/aac, audio/aacp, audio/x-wavpack, application/flv, application/m4a, application/mp4, application/octet-stream, application/ogg, application/x-ms-wmz, application/x-ms-wmd, application/x-ogg, application/x-shockwave-flash, application/x-shorten, audio/8svx, audio/16sv, audio/aac, audio/aacp, audio/ac3, audio/aiffaudio/amr, audio/basic, audio/flac, audio/m4a, audio/mp4, audio/mpeg, audio/musepack, audio/ogg, audio/opus, audio/qcelp, audio/vorbis, audio/vorbis+ogg, audio/x-8svx, audio/x-16sv, audio/x-aac, audio/x-ac3, audio/x-adx, audio/x-aiffaudio/x-alaw, audio/x-au, audio/x-dca, audio/x-eac3, audio/x-flac, audio/x-gsm, audio/x-mace, audio/x-matroska, audio/x-monkeys-audio, audio/x-mpeg, audio/x-ms-wma, audio/x-ms-wax, audio/x-musepack, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, audio/x-pn-realaudio, audio/x-pn-multirate-realaudio, audio/x-speex, audio/x-ttaaudio/x-voc, audio/x-wav, audio/x-wma, audio/x-wv, video/anim, video/quicktime, video/msvideo, video/ogg, video/theora, video/webm, video/x-dv, video/x-flv, video/x-matroska, video/x-mjpeg, video/x-mpeg, video/x-ms-asf, video/x-msvideo, video/x-ms-wmv, video/x-ms-wvx, video/x-ms-wm, video/x-ms-wmx, video/x-nut, video/x-pva, video/x-theora, video/x-vid, video/x-wmv, video/x-xvid, audio/x-mpd-ffmpeg, audio/L16, audio/L24, audio/x-mpd-float, audio/x-mpd-cdda-pcm, audio/x-mpd-cdda-pcm-reverse
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **skin** desktop
  * **music_directory_albumart** 
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** FR
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1624748318257
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mpd
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=, radiomaster=, radioconsume=0]]
  * **old_style_sql** false
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 86400000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mpd
  * **collectionrange** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** lastfm
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** double
  * **chooser** albumlist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.57
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** interface
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Bobalophagus-Dark
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1624363879308
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 0
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1624312277711
  * **next_podcast_refresh** 1626262733028
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby
  * **last_lastfm_synctime** 1624143512000
  * **collection_type** sqlite
  * **mopidy_http_port** false
  * **interface_language** en-GB
  * **collectioncontrolsvisible** true
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode** 
  * **radioparam** null
  * **radiomaster** 
  * **radioconsume** 0

**Comment by fatg3erman** [comment]
Rompr will display *precisely* what it recieves from MPD. But it assumes MPD is giving it tags in UTF8 format. You’ll have to check your tags and your mpd setup to ensure the correct encoding is being used. I have plenty of accented characters in my files and they all work fine

**Comment by oupala** [comment]
You're right, it seems that my tags are wrongly encoded in utf-8:

```log
>eyeD3 Musique/mp3/Alain\ Ramanisum/La\ Réunion\ lé\ la/La\ Réunion\ lé\ la.mp3 
eyed3.id3:WARNING: Invalid numeric genre ID: 255
eyed3.id3.tag:WARNING: Invalid numeric genre ID: 255
/home/user/Musique/mp3/Alain Ramanisum/La Réunion lé la/La Réunion lé la.mp3                                                                        [ 3.99 MB ]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 04:22	MPEG1, Layer III	[ 128 kb/s @ 44100 Hz - Joint stereo ]
----------------------------------------------------------------------------------------------------------------------------------------------------------------
ID3 v1.0:
title: La RÃ©union lÃ© la
artist: Alain Ramanisum
album: La RÃ©union lÃ© la
track: 		
----------------------------------------------------------------------------------------------------------------------------------------------------------------
```

It is possible to write mp3 and ogg tags in utf-8? What tools can do that with linux? I'm using `vorbiscomment` for ogg files and `eyeD3` for mp3, but I'm not sure how to handle utf-8...

**Comment by fatg3erman** [comment]
I am very surprised to learn that there are tools that do not use utf8. Every tool I’ve used has that set as the default and I think most players now assume it. 

I always use Muscibrainz Picard these days.

**Comment by oupala** [comment]
Nevermind @fatg3erman. I tried to retag the problematic songs, and it appears that the problem is fixed after retagging.

I think I was using an old version od eyeD3 at the time where I retagged this songs. They must have been retagged with problem. The fix is to retag the songs with a recent version of retagging tool.
