### ISSUE TITLE
Automated metadata backup doesn't work

### ISSUE THREAD

**Issue by tljohnsn** [fatg3erman/RompR#119]
Following the docs here:
https://fatg3erman.github.io/RompR/Backing-Up-Your-Metadata.html
curl -d '[{"action": "metabackup"}]' -H "Content-Type: application/json" -X POST  http://localhost/rompr/api/metadata/

Returns:
{"dummy":"baby"}

Results: There is no backup in the list of metadata backups
Expected: There is a new backup in the list of metadata backups

The backup works fine using the web interface.

Automatic backups were previously working for me on 1.48 using the old api endpoint.

Thanks,
Trent

* **BACKEND INFO**
  * **Version** 1.58
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **spotify_token** [Redacted]
  * **spotify_token_expires** [Redacted]
  * **bing_api_key** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 10.0.2.101
  * **SERVER_NAME** tunes.local
  * **SERVER_SOFTWARE** Apache/2.4.38 (Debian)
  * **DOCUMENT_ROOT** /var/www/html
  * **HTTP_HOST** tunes.local
  * **HTTP_USER_AGENT** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
  * **REMOTE_ADDR** 10.0.2.123
  * **SERVER_PORT** 80
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **sortcollectionby** artist
  * **actuallysortresultsby** artist
  * **_ga** GA1.2.155561936.1625402230
  * **player_backend** mopidy
  * **skin** tablet
* **PHP INFO**
  * **Version** 7.3.27-1~deb10u1
  * **mbstring** 7.3.27-1~deb10u1
  * **PDO** 7.3.27-1~deb10u1
  * **pdo_mysql** 7.3.27-1~deb10u1
  * **pdo_sqlite** 7.3.27-1~deb10u1
  * **curl** 7.3.27-1~deb10u1
  * **date** 7.3.27-1~deb10u1
  * **fileinfo** 7.3.27-1~deb10u1
  * **json** 1.7.0
  * **SimpleXML** 7.3.27-1~deb10u1
  * **GD** 7.3.27-1~deb10u1
  * **GD Info** GD Version=2.2.5, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=US/Central, local_value=US/Central, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=30, local_value=30, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock, local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Artist, ArtistSort, Album, AlbumArtist, AlbumArtistSort, Title, Track, Name, Genre, Date, Composer, Performer, Disc, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_TRACKID, X-AlbumUri, X-AlbumImage
  * **Commands** add, addid, addtagid, channels, clear, clearerror, cleartagid, close, commands, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, list, listall, listallinfo, listfiles, listmounts, listneighbors, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, next, notcommands, outputs, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** local
  * **URL Handlers** m3u
  * **URL Handlers** mms
  * **URL Handlers** rtmp
  * **URL Handlers** rtmps
  * **URL Handlers** rtsp
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **skin** tablet
  * **music_directory_albumart** /home/ftp/local
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** true
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** US
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 20
  * **linkchecker_nextrun** 1627125507449
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mopidy
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=null, radiomaster=1601302190437, radioconsume=[["consume","1"],["repeat","0"],["random","0"]]]]
  * **old_style_sql** false
  * **displaycomposer** true
  * **artistsatstart** 0=
  * **nosortprefixes** 0=The, 1=A
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 86400000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mopidy
  * **collectionrange** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** file
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** false
  * **clickmode** single
  * **chooser** infopane
  * **hide_albumlist** false
  * **hide_filelist** true
  * **hide_radiolist** false
  * **hide_podcastslist** true
  * **hide_playlistslist** false
  * **hide_audiobooklist** true
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.58
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** interface
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Modern-Dark
  * **coversize** 05-Tiny.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1601302190437
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1626520678319
  * **playlistbuttons_isopen** true
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1626609809763
  * **next_podcast_refresh** 1627202600348
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby
  * **chartoption** 0
  * **consume_workaround** false
  * **we_do_consume** false
  * **last_lastfm_synctime** 1625083382000
  * **collection_type** sqlite
  * **mopidy_http_port** tunes.local:6680
  * **interface_language** en-GB
  * **collectioncontrolsvisible** true
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** 
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode** 
  * **radioparam** null
  * **radiomaster** 1601302190437
  * **radioconsume** [["consume","1"],["repeat","0"],["random","0"]]

**Comment by tljohnsn** [comment]
[Sun Jul 18 07:41:51.765504 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] LOG   : INIT              : (require_once)            : Player backend pref is not set at load time
[Sun Jul 18 07:41:51.765882 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] MARK  : INIT              :                           : Detecting browser...
[Sun Jul 18 07:41:51.767989 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] INFO  : INIT              :                           : Browser is a desktop browser or was not detected
[Sun Jul 18 07:41:51.768443 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] MARK  : USERRATING        :                           : --------------------------START---------------------
[Sun Jul 18 07:41:51.775313 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] LOG   : METADATA          :                           :   Doing action METABACKUP
[Sun Jul 18 07:41:51.775530 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] TRACE : Parameter         :                           :      action : metabackup
[Sun Jul 18 07:41:51.775655 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] WARN  : METADATA          :                           : WARNING : Disc is not set!
[Sun Jul 18 07:41:51.776749 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] LOG   : METADATA          : (sanitise_data)           : Year is not a 4 digit year, analyzing Date field instead
[Sun Jul 18 07:41:51.776941 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] WARN  : USERRATINGS       :                           : Unknown Request metabackup
[Sun Jul 18 07:41:51.777185 2021] [php7:notice] [pid 12111] [client 127.0.0.1:49038] MARK  : USERRATING        :                           : ---------------------------END----------------------

**Comment by fatg3erman** [comment]
Apologies, that's a mistake in the docs.

curl -d '[{"action": "metabackup"}]' -H "Content-Type: application/json" -X POST http://localhost/rompr/api/metadata/backup/

**Comment by tljohnsn** [comment]
Thanks that does indeed work.
