### ISSUE TITLE
Only show online snapcast client controls

### ISSUE THREAD

**Issue by daniauri** [fatg3erman/RompR#122]
I use snapcast and enabled it to be main volume control in RompR.  When a client goes offline (e.g. my phone with snapdroid is leaving the WiFi) it is still shown in the top control elements but with volume at 100%. In the config menu the snapcast client is marked "Not Connected" and has no volume control attached. 

![image](https://user-images.githubusercontent.com/51371774/132128272-6da803bd-084a-402c-bb05-f5d97f30c0ec.png)

Wouldn't it be better if the control disappears from the top control if offline and reappear if online?

**Comment by fatg3erman** [comment]
Yep, that is definitely a bug, thanks for reporting. Both sets of controls should behave the same.

**Comment by daniauri** [comment]
Maybe a checkbox for hiding offline clients in the config menu. Like it is done in the snapweb applet.
The controls in the top can be hidden by default if offline. Otherwise they are just wasting space.
