### ISSUE TITLE
"Failed sending commands to mpd" and "Could not get a response from player" errors

### ISSUE THREAD

**Issue by Dlucic01** [fatg3erman/RompR#123]
Hello,
I am having problems with rompr.
apache with mysql server.
It connects to database with my personal account and not the one given in example.
When i try to play a song it says "Could not get a response from the player!".
I tried to check all files and google and couldn't find anything

**Comment by fatg3erman** [comment]
More information required. Please provide debug information and debug logs as requested under the sticky post on the issues page. Bug reports without logs will not be looked at.
