### ISSUE TITLE
[feature] support sending stream URLs to satellite MPDs

### ISSUE THREAD

**Issue by tomchiverton** [fatg3erman/RompR#124]
This would mean the remove MPDs would not need to mount file shares.

MPD is broken for Samba share's, on Fedora, sadly

**Comment by fatg3erman** [comment]
Sorry for the delay getting back to you. I don't really use MPD much and I can't find any information on what a stream URL in MPD is. Can you give some more information?

**Comment by tomchiverton** [comment]
I've moved on to use OMPD which supports this. You can close.

Stream means the playing mpd doesn't need file based access, because the data is streamed from server.

Much simpler saterlite set up. 
-- 
†øღ

**Comment by fatg3erman** [comment]
Unless MPD supports creating streams then I can't do that anyway, as the web server doesn't necessarily have access to the files. I'll close this.
