### ISSUE TITLE
Rompr wrongly assumes that is served on port 80 (http) or 443 (https)

### ISSUE THREAD

**Issue by adrhc** [fatg3erman/RompR#131]
```log
Failed to construct 'WebSocket': The URL 'ws://192.168.1.32:81:6680/mopidy/ws' is invalid.
```

I set "Mopidy HTTP Interface Port" to 6680.
The problem is that Rompr wrongly assumes that is served on port 80 (http) or 443 (https).

* **BACKEND INFO**
  * **Version** 1.61
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.32
  * **SERVER_NAME** raspberrypi
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /var/www/rompr
  * **HTTP_HOST** 192.168.1.32
  * **HTTP_USER_AGENT** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
  * **REMOTE_ADDR** 192.168.1.161
  * **SERVER_PORT** 80
  * **REQUEST_URI** /utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **skin** desktop
  * **_ga** GA1.1.152397344.1642957733
  * **player_backend** mopidy
* **PHP INFO**
  * **Version** 7.4.28
  * **mbstring** 7.4.28
  * **PDO** 7.4.28
  * **pdo_mysql** 
  * **pdo_sqlite** 7.4.28
  * **curl** 7.4.28
  * **date** 7.4.28
  * **fileinfo** 7.4.28
  * **json** 7.4.28
  * **SimpleXML** 7.4.28
  * **GD** 7.4.28
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=syslog, local_value=syslog, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=86400, local_value=86400, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=512M, local_value=512M, access=7
  * **pdo_mysql.default_socket** [NOT SET]
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Date, MUSICBRAINZ_TRACKID, Track, Comment, Disc, ArtistSort, Name, MUSICBRAINZ_ALBUMARTISTID, Genre, X-AlbumUri, Performer, Composer, Title, MUSICBRAINZ_ALBUMID, AlbumArtist, AlbumArtistSort, Album, MUSICBRAINZ_ARTISTID, Artist
  * **Commands** add, addid, addtagid, channels, clear, clearerror, cleartagid, close, commands, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, list, listall, listallinfo, listfiles, listmounts, listneighbors, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, next, notcommands, outputs, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** bandcamp
  * **URL Handlers** file
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** internetarchive
  * **URL Handlers** jamendo
  * **URL Handlers** local
  * **URL Handlers** m3u
  * **URL Handlers** mms
  * **URL Handlers** podcast
  * **URL Handlers** podcast+file
  * **URL Handlers** podcast+http
  * **URL Handlers** podcast+https
  * **URL Handlers** podcast+itunes
  * **URL Handlers** rtmp
  * **URL Handlers** rtmps
  * **URL Handlers** rtsp
  * **URL Handlers** somafm
  * **URL Handlers** tunein
  * **URL Handlers** youtube
  * **URL Handlers** yt
  * **URL Handlers** ytmusic
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **interface_language** en-GB
  * **music_directory_albumart** 
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** RO
  * **country_userset** true
  * **debug_enabled** 3
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1653595333516
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** null
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=, radiomaster=, radioconsume=0]]
  * **old_style_sql** false
  * **auto_audiobook** 
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 86400000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mopidy
  * **collectionrange** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** true
  * **infosource** lastfm
  * **sourceswidthpercent** 32.711060193159454
  * **playlistwidthpercent** 35.017115172859256
  * **downloadart** true
  * **clickmode** double
  * **chooser** albumlist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.61
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** interface
  * **synctags** false
  * **synclovevalue** 0
  * **theme** Numismatist.css
  * **icontheme** Bobalophagus-Dark
  * **coversize** 48
  * **fontsize** 11
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1652993791497
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1652990532399
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1652990533480
  * **next_podcast_refresh** 1655109748512
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby, Numismatist.css=[timeout=60000, lastchange=1652993791256, random=false, position=top left]
  * **chartoption** 0
  * **consume_workaround** false
  * **we_do_consume** false
  * **somafm_quality** highest_available_quality
  * **last_lastfm_synctime** 1652990530000
  * **collection_type** sqlite
  * **mopidy_http_port** 192.168.1.32:6680
  * **skin** desktop
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **collectioncontrolsvisible** true
  * **radiomode** 
  * **radioparam** 
  * **radiomaster** 
  * **radioconsume** 0

**Comment by fatg3erman** [comment]
What did you set the address for your Mopidy player to? I can't reproduce this.

**Comment by fatg3erman** [comment]
Sorry I should have read the log you helpfully provided :) Can you try using an IP address instead of localhost for Mopidy? localhost often gives strange problems and I don't like it.

As the debug info shows, the pref more mopidy_http_port is set correctly: 192.168.1.32:6680

So I have no idea where that :81 is coming from. Rompr makes no assumptions about which port it is served on.

**Comment by fatg3erman** [comment]
According to your debug info above, your server *is* running on Port 80. The mopidy websocket address, if mopidy is configured to use 'localhost', is created from a combination of the server-side variable HTTP_HOST (which you can see is set to an IP address, as it should be) and the mopidy HTTP port. There's nowhere in any of that info that points to port 81 being used anywhere in your setup, so it's a total mystery why it's there. It's as if the browser is adding it. If you enable debug logging you should see a message in the Javascript console that says 'MOPISOCKET Connecting to' and the the address the code is using.

**Comment by adrhc** [comment]
> According to your debug info above, your server is running on Port 80

Right, I changed it to 80 otherwise I couldn't use Rompr; initially (before copying the debug information) was 81.

```nginx
server {
    listen 81 default_server;
    listen [::]:81 default_server;

    root /var/www/rompr/;
    index index.php index.html index.htm;

    server_name raspberrypi;

    client_max_body_size 512M;

    error_page 404 = /rompr/404.php;

    # This section can be copied into an existing default setup
    location / {
        allow all;
        index index.php;
        location ~ \.php {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
            fastcgi_read_timeout 864000;
        }
        # error_page 404 = /rompr/404.php;
        try_files $uri $uri/ =404;
        location ~ /albumart/* {
                expires -1s;
        }
    }
}
```

**Comment by fatg3erman** [comment]
OK so firstly, with reference to your other post, I think your error_page 404 should point to /404.php, because you've set your root to /var/www/rompr/. The error_page is a path relative to the server root. You should correct that.

I still don't understand why it's including the :81 in the prefs. Like I say, this is built up server-side, so unless HTTP_HOST includes the port number, and only does so when you use a non-standard port (which would make no sense) then it shouldn't be there.

If it's obvious from the js code why this is, please provide an example.

**Comment by adrhc** [comment]
> I think your error_page 404 should point to /404.php

Thanks, I closed the other post because of this (you are right about it).

Sorry, somehow I missed the javascript error code where one can see that the ws:// part is computed dynamically in javascript (i.e. uses `location.host` in a script concatenation) - so, it's not built up server-side.

I can't reproduce it right now because I'm conducting a very long collection update but I'll paste the error as soon I can reproduce it.

**Comment by fatg3erman** [comment]
There's absolutely nowhere in the code where I use location.host. Anywhere. At least not in the current release. It is definitely built server-side, there's PHP function called get_player_ip() that does it.

I have reproduced it here, but like I say I can't think of a way to fix it. I can't use 'localhost' because it's not necessarily 'localhost' as far as the browser is concerned. So I have to convert 'localhost' to an IP address, and it doesn't look like the server gives me any infomation I can trust to do that reliably.

**Comment by adrhc** [comment]
I don't think that "localhost" matters, I think only the website address matters; e.g. for my Rompr is 192.168.1.32:81; when computing the ws:// part one should get ws://192.168.1.32:81/mopidy/ws instead of ws://192.168.1.32:81:6680/mopidy/ws. I think here is about telling Rompr to not directly access Mopidy from the browser, but rather consider it proxied by the Rompr's host.

**Comment by fatg3erman** [comment]
Are you actually trying to explain to me how my own code works?

`
socket = new WebSocket('ws://'+prefs.mopidy_http_port+'/mopidy/ws');
`

prefs.modify_http_port is created *in the backend* by probe_http_api() and nice_server_address(), which used HTTP_HOST if the player address is 'localhost. End of discussion.

Open the Preferences panel, Edit Player,s and replace localhost with the IP of the machine your Mopidy is running on. Problem solved.
