### ISSUE TITLE
LastFM Login

### ISSUE THREAD

**Issue by Briggsbfc** [fatg3erman/RompR#133]
Hi,
I updated to 1.61 recently and tried to reconnect to LastFM. I entered my user id, hovered over the 'Login' button which lit up and displayed 'Rompr Preferences' but did nothing when pressed. The login had been fine until the update.
Kind Regards and thanks for this brilliant software.
Chris.
* **BACKEND INFO**
  * **Version** 1.61
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.128
  * **SERVER_NAME** musicbox
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /home/rompr
  * **HTTP_HOST** 192.168.1.128
  * **HTTP_USER_AGENT** Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
  * **REMOTE_ADDR** 192.168.1.171
  * **SERVER_PORT** 80
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **skin** desktop
  * **sortcollectionby** artist
  * **actuallysortresultsby** artist
  * **collectionrange** 0
  * **player_backend** mpd
* **PHP INFO**
  * **Version** 7.4.30
  * **mbstring** 7.4.30
  * **PDO** 7.4.30
  * **pdo_mysql** 
  * **pdo_sqlite** 7.4.30
  * **curl** 7.4.30
  * **date** 7.4.30
  * **fileinfo** 7.4.30
  * **json** 7.4.30
  * **SimpleXML** 7.4.30
  * **GD** 7.4.30
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** [NOT SET]
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.22.4
  * **tagtype** Artist, ArtistSort, Album, AlbumSort, AlbumArtist, AlbumArtistSort, Title, Track, Name, Genre, Date, OriginalDate, Composer, Performer, Conductor, Work, Grouping, Disc, Label, MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID, MUSICBRAINZ_TRACKID, MUSICBRAINZ_RELEASETRACKID, MUSICBRAINZ_WORKID
  * **Commands** add, addid, addtagid, albumart, binarylimit, channels, clear, clearerror, cleartagid, close, commands, config, consume, count, crossfade, currentsong, decoders, delete, deleteid, delpartition, disableoutput, enableoutput, find, findadd, getfingerprint, idle, kill, list, listall, listallinfo, listfiles, listmounts, listpartitions, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, moveoutput, newpartition, next, notcommands, outputs, outputset, partition, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readcomments, readmessages, readpicture, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, sticker, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **URL Handlers** alsa://
  * **URL Handlers** cdda://
  * **URL Handlers** ftp://
  * **URL Handlers** ftps://
  * **URL Handlers** gopher://
  * **URL Handlers** hls+http://
  * **URL Handlers** hls+https://
  * **URL Handlers** http://
  * **URL Handlers** https://
  * **URL Handlers** mms://
  * **URL Handlers** mmsh://
  * **URL Handlers** mmst://
  * **URL Handlers** mmsu://
  * **URL Handlers** nfs://
  * **URL Handlers** rtmp://
  * **URL Handlers** rtmps://
  * **URL Handlers** rtmpt://
  * **URL Handlers** rtmpts://
  * **URL Handlers** rtp://
  * **URL Handlers** rtsp://
  * **URL Handlers** rtsps://
  * **URL Handlers** scp://
  * **URL Handlers** sftp://
  * **URL Handlers** smb://
  * **URL Handlers** srtp://
  * **plugin** mad, mpg123, vorbis, oggflac, flac, opus, sndfile, audiofile, dsdiff, dsf, faad, mpcdec, wavpack, modplug, mikmod, sidplay, fluidsynth, adplug, ffmpeg, gme, pcm
  * **suffix** mp3, mp2, mp3, ogg, oga, ogg, oga, flac, opus, ogg, oga, wav, aiff, aif, au, snd, paf, iff, svx, sf, voc, w64, pvf, xi, htk, caf, sd2, wav, au, aiff, aif, dff, dsf, aac, mpc, wv, 669, amf, ams, dbm, dfm, dsm, far, it, med, mdl, mod, mtm, mt2, okt, s3m, stm, ult, umx, xm, amf, dsm, far, gdm, imf, it, med, mod, mtm, s3m, stm, stx, ult, uni, xm, sid, mus, str, prg, P00, mid, amd, d00, hsc, laa, rad, raw, sa2, 16sv, 3g2, 3gp, 4xm, 8svx, aa3, aac, ac3, adx, afc, aif, aifc, aiff, al, alaw, amr, anim, apc, ape, asf, atrac, au, aud, avi, avm2, avs, bap, bfi, c93, cak, cin, cmv, cpk, daud, dct, divx, dts, dv, dvd, dxa, eac3, film, flac, flc, fli, fll, flx, flv, g726, gsm, gxf, iss, m1v, m2v, m2t, m2ts, m4a, m4b, m4v, mad, mj2, mjpeg, mjpg, mka, mkv, mlp, mm, mmf, mov, mp+, mp1, mp2, mp3, mp4, mpc, mpeg, mpg, mpga, mpp, mpu, mve, mvi, mxf, nc, nsv, nut, nuv, oga, ogm, ogv, ogx, oma, ogg, omg, opus, psp, pva, qcp, qt, r3d, ra, ram, rl2, rm, rmvb, roq, rpl, rvc, shn, smk, snd, sol, son, spx, str, swf, tak, tgi, tgq, tgv, thp, ts, tsp, tta, xa, xvid, uv, uv2, vb, vid, vob, voc, vp6, vmd, wav, webm, wma, wmv, wsaud, wsvga, wv, wve, ay, gbs, gym, hes, kss, nsf, nsfe, sap, spc, vgm, vgz
  * **mime_type** audio/mpeg, application/ogg, application/x-ogg, audio/ogg, audio/vorbis, audio/vorbis+ogg, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, application/ogg, application/x-ogg, audio/ogg, audio/x-flac+ogg, audio/x-ogg, application/flac, application/x-flac, audio/flac, audio/x-flac, audio/ogg, application/ogg, audio/opus, audio/wav, audio/aiff, audio/x-wav, audio/x-aiff, audio/wav, audio/aiff, audio/x-wav, audio/x-aiff, application/x-dff, audio/x-dff, audio/x-dsd, application/x-dsf, audio/x-dsf, audio/x-dsd, audio/aac, audio/aacp, audio/x-wavpack, application/flv, application/m4a, application/mp4, application/octet-stream, application/ogg, application/x-ms-wmz, application/x-ms-wmd, application/x-ogg, application/x-shockwave-flash, application/x-shorten, audio/8svx, audio/16sv, audio/aac, audio/aacp, audio/ac3, audio/aiff, audio/amr, audio/basic, audio/flac, audio/m4a, audio/mp4, audio/mpeg, audio/musepack, audio/ogg, audio/opus, audio/qcelp, audio/vorbis, audio/vorbis+ogg, audio/wav, audio/x-8svx, audio/x-16sv, audio/x-aac, audio/x-ac3, audio/x-adx, audio/x-aiff, audio/x-alaw, audio/x-au, audio/x-dca, audio/x-eac3, audio/x-flac, audio/x-gsm, audio/x-mace, audio/x-matroska, audio/x-monkeys-audio, audio/x-mpeg, audio/x-ms-wma, audio/x-ms-wax, audio/x-musepack, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, audio/x-pn-realaudio, audio/x-pn-multirate-realaudio, audio/x-speex, audio/x-tta, audio/x-voc, audio/x-wav, audio/x-wma, audio/x-wv, video/anim, video/quicktime, video/msvideo, video/ogg, video/theora, video/webm, video/x-dv, video/x-flv, video/x-matroska, video/x-mjpeg, video/x-mpeg, video/x-ms-asf, video/x-msvideo, video/x-ms-wmv, video/x-ms-wvx, video/x-ms-wm, video/x-ms-wmx, video/x-nut, video/x-pva, video/x-theora, video/x-vid, video/x-wmv, video/x-xvid, audio/x-mpd-ffmpeg, audio/L16, audio/L24, audio/x-mpd-float, audio/x-mpd-cdda-pcm, audio/x-mpd-cdda-pcm-reverse, audio/x-mpd-alsa-pcm
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **interface_language** en-GB
  * **music_directory_albumart** 
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** GB
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1659268931303
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mpd
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** Default=[host=192.168.1.128, port=6600, password=bollocks2000, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=null, radiomaster=, radioconsume=0]]
  * **old_style_sql** false
  * **auto_audiobook** 
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 86400000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** false
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mpd
  * **collectionrange** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **tradsearch** false
  * **lastfm_scrobbling** true
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** lastfm
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** double
  * **chooser** albumlist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.61
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** interface
  * **synctags** false
  * **synclovevalue** 0
  * **theme** Oxygen.css
  * **icontheme** Bobalophagus-Dark
  * **coversize** 48
  * **fontsize** 11
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1637322343179
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1658672764891
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** true
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1658750658422
  * **next_podcast_refresh** 1660783345555
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby, Oxygen.css=[timeout=60000, lastchange=1643467788510, random=false, position=top left]
  * **chartoption** 0
  * **consume_workaround** false
  * **we_do_consume** false
  * **somafm_quality** highest_available_quality
  * **last_lastfm_synctime** 1656257327000
  * **collection_type** sqlite
  * **mopidy_http_port** false
  * **skin** desktop
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode** 
  * **radioparam** null
  * **radiomaster** 
  * **radioconsume** 0

**Comment by fatg3erman** [comment]
Hmmm. That's going to be tricky to debug, the code has moved on a long way since 1.61.

Can you open your browser's Javascript Console and see if there are any error messages in there when you click the Login button?

**Comment by Briggsbfc** [comment]
Hi,
I'm happy to wait for the next release if it is working ok there. Below is a screenshot of the console.
![image](https://user-images.githubusercontent.com/37410039/180803101-6e0e0a29-cd0b-4c14-972b-21834b747dd7.png)

**Comment by fatg3erman** [comment]
I'm sorry it's not working for you, all the debug info looks OK and it is working in the current dev version. The next releae might be some time away though.

You could try the following, which might have the effect of clearing whatever's got stuck:

Enter your username into the box but don't click login. Wait 10 seconds. Delete your username, wait 10 seconds. Refresh the page. Now re-enter your username, wait 10 seconds, then try to log in.
