### ISSUE TITLE
Refreshing of song status / move to next song

### ISSUE THREAD

**Issue by mattange** [fatg3erman/RompR#134]
Hi,
I really love your project and i am testing it out.

I know you seem not to use docker much, but i have managed to make it work in the past. Something somewhere "broke" though and i am unclear on where the problem is... hence opening an issue here but just looking for guidance.

Simply put: everything works fine, i can control multiple Mopidy instances and so on.. only one thing seems to be off... the statusbar on the song does not refresh (see snapshot). It does not move alongside the song, so to speak. And when the list moves to the next song, the information stays the same on screen. I have to refresh the page to see a refreshed song info. But the status still sits at "0%".
I can seek the song position by clicking on the horizontal bar but ... then it stays there at whatever %age of the song i moved it to.

The debug logs seem to say nothing useful this time around, but attached.

And it may well NOT be an issue with ROMPR... just can't figure out where that is as everything else appears to be working.
I have confirmed using another Mopidy client that the status of the son on that client gets updated as expected... 

I am using this with docker-compose, with official nginx and php images to start with, with appropriate config amendments.

Any help appreciated!

![Capture1](https://user-images.githubusercontent.com/3732650/191044861-e7e30006-3b88-416a-b668-cbcc03b01315.PNG)

[info.txt.txt](https://github.com/fatg3erman/RompR/files/9599953/info.txt.txt)

[error.log](https://github.com/fatg3erman/RompR/files/9599955/error.log)

[phpinfo.pdf](https://github.com/fatg3erman/RompR/files/9599956/phpinfo.pdf)

**Comment by fatg3erman** [comment]
That implies a problem n the javascript side of things. Have a look for errors in your browser's Javascript console.

i don't know anything about Docker so I don't really understand your setup.

**Comment by mattange** [comment]
Ok-thanks for feedback I did not think of checking that out, will do.
I also noticed that my snapcast group(s) do not show up, but the server can definitely be reached (and in fact no error messages when I put the right address either). 
All in standard skin. 

Will try to inspect JavaScript - I am using Firefox but seemed to be a problem also with Edge for instance from windows. 

As to docker, the fact that I can control Mopidy which is on a completely different machine than the docker stuff running Rompr tells me that that side of things seems to be just fine. 

It used to be OK in earlier versions of ... Something! (Rompr / Firefox / libraries in general).

Will keep you posted and happy to contribute my recent setup as a pull request if you like as a subfolder of your repo later on.

**Comment by fatg3erman** [comment]
If it's Mopidy then this is likely a cross-site RPC problem. Make sure csrf_protection is set to false in your mopidy.conf. The Snapcast issue is probably similar.

**Comment by mattange** [comment]
OK - a bit of an update.
1) managed to figure out the issue with the status update for the song: i had included the additional port in the setup for Mopidy and that seems to prevent the update of the status... now i only have the standard mpd port and that seems to be working fine. Maybe it's because i have multiple Mopidy instances and they have different ports... possible to setup the individual port on the mpd-like side but a single port on the http-like side of things it seems. Solved by using only the MPD port, although admittedly i was not clear about that initially!
2) view of the channel / details of snapcast still not working (use snapserver 0.26). No error is apparent but by inspecting the console it shows a snapcast.js is indeed the problem. it definitely used to work. is there any setting you're familiar i should change? See attachments.
![Capture1](https://user-images.githubusercontent.com/3732650/192374799-e9f8f28b-827f-427e-98ed-6b00b7b8be91.PNG)
![Capture2](https://user-images.githubusercontent.com/3732650/192374804-0e8af5c7-ca09-4b32-aa7d-4e27f97dfc62.PNG)

again... thanks for the excellent work i hope the above help

**Comment by fatg3erman** [comment]
1. Yes, I really never expect Mopidy to use a different port from the default. If you have different instances using different ports, that won't work. I might look at making that configurable per-player, but it's really not a simple matter.
2. That error is coming from your browser, it's telling you you're trying to do something insecure - the domain you're trying to connect to for your snapserver is not the same as the domain that your webpage is displaying. It's a browser security feature, annoying in this case but there is nothing I can do about it. Either rompr and snapserver need to be on the same domain, or you could try using an IP address for the snapserver, that might work.

**Comment by mattange** [comment]
i see you're right i can probably amend that... fair
