### ISSUE TITLE
rel 1.61: on iphone 12  menu icons are not very clickable anymore

### ISSUE THREAD

**Issue by akamming** [fatg3erman/RompR#135]
Hi,

first  of all thanx for all the great work. Been using rompr a lot.

Unfortunately i have an issue since i installed 1.61. Due to the fact that in the phone skin the icons are now at the bottom of the screen, due to the rounded edges it is very difficult to click on the play icon (bottom left) or menu icon (top bottom). Furthermore the centre bottom icons ( radio, podcast, volume) overlap with the menu bar from the iphone

here is made a screenshot : 
![image](https://user-images.githubusercontent.com/30364409/195991877-d1106a36-311e-4592-afec-afc8688d6eb2.png)
 
unfortunately the screenshot does not show the rounded edges of the iphone 12 screen, so i just grabbed an iphone 12 image from internet. so you can imagine how the image above looks on a iphone 12 screen with rounded edges on the LCD display, not showing the entire icon, because they are too far in the corner, which is not shown
![image](https://user-images.githubusercontent.com/30364409/195991967-c433480e-850b-4e9d-b835-3358d50137d7.png)

**Comment by fatg3erman** [comment]
Great. I moved them to the bottom because the exact same thing happens to me if they're at the top.

**Comment by akamming** [comment]
I assume it is Fixed if they are placed just a bit higher

**Comment by fatg3erman** [comment]
Difficult for me to know exactly how many pixels. Can you try something?

find the file rompr/skins/phone/skin.css, and find this block at line 101

headerbar {
	height:40px;
	padding:0px;
	margin:0px;
	border:none;
}

and change it to

headerbar {
	height:40px;
	padding: 0px;
	padding-bottom: 8px;
	margin:0px;
	border:none;
}

Adjust the value for padding-bottm until it works for you. Note that you might need to refresh the page several times for changes to be picked up, because Safari has bugs in its caching.

**Comment by akamming** [comment]
tx... 12px seems to be the right value. as a sideeffect however also the icons are becoming a bit smaller. This is still better than it used to be, but would be nice if the icons kan keep there original size..
![image](https://user-images.githubusercontent.com/30364409/196114456-b61f2305-1b98-4275-95ff-fc877598e92a.png)

**Comment by fatg3erman** [comment]
I've added a configurable padding to the bottom of screen, will be in version 2.0
