### ISSUE TITLE
read-in m3u playlist skips tracks with spaces in filename

### ISSUE THREAD

**Issue by g13092** [fatg3erman/RompR#136]
I've been trying to figure a nice method to move some playlists into my setup.  I generated a playlist with Clementine, then updated the path to match "local:track:" instead of relative "../" or absolute path "/server/blah/.."  After updating the collection via Rompr, expanding the list of tracks in the playlist, I noticed that the only tracks listed are ones that happen to have no spaces in the file names.  All the ones listed have no spaces, either using %20 or _ or -.

Funny thing, I can find the tracks in the library and play them directly.  So then I add them to my playlist and resave.  Looking the playlist text, I see the former spaces have %20 in the spaces.  

Maybe this is all expected behavior?

BTW, rompr is pretty fn cool for interfacing with mopidy and snapserver.

* **BACKEND INFO**
  * **Version** 1.59.1
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /utils/debuginfo.php
  * **SERVER_ADDR** 172.19.0.3
  * **SERVER_NAME** _
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /app/rompr
  * **HTTP_HOST** 192.168.1.253
  * **HTTP_USER_AGENT** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
  * **REMOTE_ADDR** 192.168.1.250
  * **SERVER_PORT** 80
  * **REQUEST_URI** /utils/debuginfo.php
* **COOKIES**
  * **skin** desktop
  * **currenthost** Default
  * **token** 3f20ab4bf2a142a3994a4fe263dd5fc2
  * **userLevel** 3
  * **X-OPENMEDIAVAULT-SESSIONID** 41oi961ht3kkhovutcohdk0n4j
  * **sortcollectionby** artist
  * **actuallysortresultsby** artist
* **PHP INFO**
  * **Version** 7.4.21
  * **mbstring** 7.4.21
  * **PDO** 7.4.21
  * **pdo_mysql** 7.4.21
  * **pdo_sqlite** 7.4.21
  * **curl** 7.4.21
  * **date** 7.4.21
  * **fileinfo** 7.4.21
  * **json** 7.4.21
  * **SimpleXML** 7.4.21
  * **GD** 7.4.21
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=1, local_value=1, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock, local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **CONFIG**
  * **rgbs** r=77, g=80, b=17, a=1
  * **skin** desktop
  * **music_directory_albumart** 
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** US
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1669999934552
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mopidy
  * **snapcast_server** 192.168.1.253
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** Default=[host=192.168.1.253, port=6600, password=, socket=, mopidy_remote=false, radioparams=[radiomode=, radioparam=, radiomaster=, radioconsume=0]]
  * **old_style_sql** false
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 86400000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** true
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mopidy
  * **collectionrange** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** true
  * **infosource** file
  * **sourceswidthpercent** 27.73809523809524
  * **playlistwidthpercent** 36.42857142857142
  * **downloadart** true
  * **clickmode** double
  * **chooser** albumlist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** true
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** true
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.59.1
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** interface
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Leaf.css
  * **icontheme** Bobalophagus-Light
  * **coversize** 30-Medium.css
  * **fontsize** 02-Normal.css
  * **fontfamily** Calibri.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** true
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** true
  * **communityradioorderby** name
  * **browser_id** 1666043244222
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1669395139308
  * **playlistbuttons_isopen** true
  * **collectionbuttons_isopen** true
  * **advsearchoptions_isopen** false
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1669395134518
  * **next_podcast_refresh** 1671514349542
  * **use_original_releasedate** false
  * **bgimgparms** dummy=baby
  * **chartoption** 0
  * **consume_workaround** false
  * **we_do_consume** false
  * **last_lastfm_synctime** 1669395087000
  * **collection_type** sqlite
  * **interface_language** en-GB
  * **mpd_host** 192.168.1.253
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** 
  * **mopidy_http_port** 192.168.1.253:6680
  * **collectioncontrolsvisible** true
  * **maxrgbs** r=136, g=142, b=30, a=1
  * **bgdrgbs** r=0, g=0, b=0, a=0
  * **radiomode** 
  * **radioparam** 
  * **radiomaster** 
  * **radioconsume** 0

**Comment by fatg3erman** [comment]
Sorry for taking so long to reply to this. Mopidy urlencodes everything. Spaces *have* to be encoded to %20 or they won't work. This isn't a RompR thing, it's how Mopidy handles URIs.
