### ISSUE TITLE
FR: Support playback of youtube streams

### ISSUE THREAD

**Issue by svalo** [fatg3erman/RompR#137]
Hello, I'm opening this one to ask if you'd consider to add support for youtube audio tracks. 

The idea would be doing something similar to what can be achieved using `mpc`  with the following command:

 ```bash
 mpc add $(youtube-dl -g --format bestaudio https://www.youtube.com/watch?v=<videoid>)
 ```
or for playlists

```bash
for url in $(youtube-dl -g -f bestaudio https://www.youtube.com/watch?v=<videoid>&list=<listid> )
do
    mpc add "$url"
done
```

This basically asks `youtube-dl` to get the url for the best audio quality available for the specified video and pass that to `mpc` to enqueue it. Especially for playlists this can take long so it may be better to make it run in the background.

What I'd find really nice is to have an icon alongside radio,file browser ...  exposing a text box where I can paste the url of the youtube video, on submit the corresponding audio stream url is appended to the playlist. 

Thank you for your time :)

**Comment by fatg3erman** [comment]
You can already do this by using Mopidy with its YTMusic backend. Rompr version 2, out soon, will have extensive support for that setup.

**Comment by svalo** [comment]
Great, thank you for your feedback!
I'll stick with mpc waiting for Rompr version 2. You can close this for me
