### ISSUE TITLE
Unable to add tracks to saved playlist

### ISSUE THREAD

**Issue by chandranorth** [fatg3erman/RompR#141]
I am unable to save tracks to a new playlist, or to add tracks to an existing playlist.  I can make new playlists and add to playlists using another mopidy web frontend, e.g., Mopidy Iris, and once created, these appear in Rompr.  Perhaps a write permission error?

Attached is the debug information from Rompr.  Please let me know if any other information is required.

Thanks again for a great piece of software!

* **BACKEND INFO**
  * **Version** 2.00
  * **System** Linux mopidy 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.118
  * **SERVER_NAME** _
  * **SERVER_SOFTWARE** nginx/1.18.0
  * **DOCUMENT_ROOT** /var/www/html
  * **HTTP_HOST** 192.168.1.118
  * **HTTP_USER_AGENT** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
  * **REMOTE_ADDR** 192.168.1.131
  * **SERVER_PORT** 80
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **browser_id** 1668772970070
  * **currenthost** Default
  * **player_backend** mopidy
  * **skin** desktop
  * **_ga** GA1.1.1613913748.1669590781
* **PHP INFO**
  * **Version** 7.4.33
  * **mbstring** 7.4.33
  * **PDO** 7.4.33
  * **pdo_mysql** 
  * **pdo_sqlite** 7.4.33
  * **curl** 7.4.33
  * **date** 7.4.33
  * **fileinfo** 7.4.33
  * **json** 7.4.33
  * **SimpleXML** 7.4.33
  * **GD** 7.4.33
  * **GD Info** GD Version=2.3.0, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** [NOT SET]
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **RELEVANT RUNNING PROCESSES**
  * ****
```
www-data  5287  0.0  2.5  80640 23636 ?        S    Jan17   0:28 php /var/www/html/rompr/rompr_backend.php
www-data  5299  0.0  2.5  82708 23948 ?        S    Jan17   0:00 php /var/www/html/rompr/romonitor.php --currenthost Default

```

* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **config** []
  * **tagtypes** {"tagtype":["Artist", "ArtistSort", "Album", "AlbumArtist", "AlbumArtistSort", "Title", "Track", "Name", "Genre", "Date", "Composer", "Performer", "Disc", "MUSICBRAINZ_ARTISTID", "MUSICBRAINZ_ALBUMID", "MUSICBRAINZ_ALBUMARTISTID", "MUSICBRAINZ_TRACKID", "X-AlbumUri", "X-AlbumImage"]}
  * **commands** {"command":["add", "addid", "addtagid", "channels", "clear", "clearerror", "cleartagid", "close", "commands", "consume", "count", "crossfade", "currentsong", "decoders", "delete", "deleteid", "disableoutput", "enableoutput", "find", "findadd", "idle", "list", "listall", "listallinfo", "listfiles", "listmounts", "listneighbors", "listplaylist", "listplaylistinfo", "listplaylists", "load", "lsinfo", "mixrampdb", "mixrampdelay", "mount", "move", "moveid", "next", "notcommands", "outputs", "password", "pause", "ping", "play", "playid", "playlist", "playlistadd", "playlistclear", "playlistdelete", "playlistfind", "playlistid", "playlistinfo", "playlistmove", "playlistsearch", "plchanges", "plchangesposid", "previous", "prio", "prioid", "random", "rangeid", "readmessages", "rename", "repeat", "replay_gain_mode", "replay_gain_status", "rescan", "rm", "save", "search", "searchadd", "searchaddpl", "seek", "seekcur", "seekid", "sendmessage", "setvol", "shuffle", "single", "stats", "status", "stop", "subscribe", "swap", "swapid", "tagtypes", "toggleoutput", "unmount", "unsubscribe", "update", "urlhandlers", "volume"]}
  * **notcommands** {"command":["config", "kill"]}
  * **urlhandlers** ["file", "http", "https", "local", "m3u", "rtsp", "somafm", "tidal", "tunein"]
  * **decoders** true
* **CONFIG**
  * **rgbs** {"r":1, "g":1, "b":1, "a":"0.75"}
  * **interface_language** en-GB
  * **music_directory_albumart** 
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** ["Classical"]
  * **preferlocalfiles** false
  * **mopidy_collection_folders** ["Local media"]
  * **lastfm_country_code** US
  * **country_userset** true
  * **debug_enabled** 0
  * **custom_logfile** 
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **clear_update_lock** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **dev_mode** false
  * **live_mode** false
  * **use_mopidy_scan** true
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 12/31/1969, 6:00:00 PM
  * **link_checker_frequency** 604800
  * **link_checker_is_running** false
  * **audiobook_directory** 
  * **collection_player** mopidy
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **snapcast_http** 1780
  * **http_port_for_mopidy** 6680
  * **multihosts** {"Default":{"host":"localhost", "port":"6600", "password":"", "socket":"", "mopidy_remote":false, "do_consume":false, "websocket":"192.168.1.118:6680/mopidy/ws", "websocket_port":"6680", "radioparams":{"radiomode":"", "radioparam":"", "radioconsume":[], "radiodomains":["local", "spotify", "youtube", "ytmusic"], "toptracks_current":1, "toptracks_total":1}}}
  * **old_style_sql** false
  * **auto_audiobook** []
  * **backend_version** 2.00
  * **spotify_mark_unplayable** false
  * **consume_workaround** false
  * **we_do_consume** false
  * **smartradio_clearfirst** true
  * **collection_type** sqlite
  * **displaycomposer** true
  * **artistsatstart** ["Various Artists", "Soundtracks"]
  * **nosortprefixes** ["The"]
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **next_lastfm_synctime** 12/31/1969, 6:00:00 PM
  * **lastfm_sync_frequency** 86400
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **hide_master_volume** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **communityradioorderby** name
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 9/24/55010, 6:41:30 PM
  * **use_original_releasedate** false
  * **chartoption** 0
  * **lastfm_user** 
  * **autotagname** 
  * **lastfm_logged_in** false
  * **lastfm_scrobbling** false
  * **scrobblepercent** 50
  * **use_mopidy_search** true
  * **last_lastfm_synctime** 1674044916
  * **currenthost** Default
  * **player_backend** mopidy
  * **browser_id** 1668772970070
  * **clickmode** double
  * **skin** desktop
  * **sortbydate** false
  * **notvabydate** false
  * **collectionrange** 0
  * **sortcollectionby** artist
  * **sortresultsby** sameas
  * **actuallysortresultsby** artist
  * **alarmindex** null
  * **sleeptime** 30
  * **snooze** null
  * **tradsearch** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** lyrics
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **chooser** playlistslist
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** false
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hide_pluginplaylistslist** false
  * **hidebrowser** false
  * **shownupdatewindow** 2.00
  * **scrolltocurrent** false
  * **lastfmlang** interface
  * **synctags** false
  * **synclovevalue** 0
  * **theme** Numismatist.css
  * **icontheme** Bobalophagus-Dark
  * **coversize** 48
  * **fontsize** 11
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** ["local", "spotify"]
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **use_albumart_in_playlist** true
  * **bgimgparms** {"dummy":"baby", "Numismatist.css":{"timeout":60000, "lastchange":1668772970006, "random":false, "position":"top left"}, "Mountains.css":{"timeout":60000, "lastchange":1672579845522, "random":false, "position":"top left"}}
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **somafm_quality** highest_available_quality
  * **stupid_rounded_corner_buffer_size** 0
  * **maxrgbs** {"r":150, "g":150, "b":150, "a":"0.75"}
  * **bgdrgbs** {"r":1, "g":1, "b":1, "a":"0"}

**Comment by fatg3erman** [comment]
I can't reproduce this but experience suggests that when this doesn't work it's a bug in one of your Mopidy backends.

RompR uses the MPD interface to save and amend playlists, the other frontends you've tried probably use the HTTP interface. Some backends are not well-behaved and can cause errors because of this. If I had to guess which one it was, I'd bet it was Tidal but I have no evidence other than experience to support that.

**Comment by chandranorth** [comment]
Thanks for your response. Is there any other configuration required in the [mpd] section of mopidy.conf? At present I have:

[mpd]
enabled = true
max_connections = 30
connection_timeout = 600


Best regards,

Venkat Chandrasekhar

     On Thursday, January 19, 2023, 03:45:53 PM CST, Mark Greenwood ***@***.***> wrote:  
 
 


I can't reproduce this but experience suggests that when this doesn't work it's a bug in one of your Mopidy backends.

RompR uses the MPD interface to save and amend playlists, the other frontends you've tried probably use the HTTP interface. Some backends are not well-behaved and can cause errors because of this. If I had to guess which one it was, I'd bet it was Tidal but I have no evidence other than experience to support that.

**Comment by fatg3erman** [comment]
That's all the config you need. This isn't a configuration problem, it's a badly-written-backend problem. You might get some debug information out of Mopidy if you run it in a terminal and then try to save a playlist from RompR, but like I say it works on my setup, with a different set of backends. I can't test Tidal but it's the only one of your backends that I've never used so it points to that as the culprit.

**Comment by chandranorth** [comment]
You are probably right. See the discussion on Tidal playlists: https://github.com/tehkillerbee/mopidy-tidal/issues/86

Thanks again,

Venkat

     On Friday, January 20, 2023, 03:06:15 AM CST, Mark Greenwood ***@***.***> wrote:  
 
 


That's all the config you need. This isn't a configuration problem, it's a badly-written-backend problem. You might get some debug information out of Mopidy if you run it in a terminal and then try to save a playlist from RompR, but like I say it works on my setup, with a different set of backends. I can't test Tidal but it's the only one of your backends that I've never used so it points to that as the culprit.

**Comment by tehkillerbee** [comment]
@chandranorth Just to understand your issue so we can try to replicate it. 

You can add to the playlist through Mopidy Iris or similar - but not when using RompR?

**Comment by chandranorth** [comment]
Johannes,

Sorry for the delayed response. Unfortunately, I am now having a problem with the mopidy-tidal plugin, but that is a separate issue.

Yes, the problem was that I could add to playlists using Iris, but not when using Rompr.

I noticed that fatg3erman has opened the same issue on the github page of mopidy-tidal.


     On Monday, April 10, 2023, 10:58:42 AM CDT, Johannes L ***@***.***> wrote:  
 
 


@chandranorth Just to understand your issue so we can try to replicate it.

You can add to the playlist through Mopidy Iris or similar - but not when using RompR?

**Comment by fatg3erman** [comment]
>> I noticed that fatg3erman has opened the same issue on the github page of mopidy-tidal.

No, I did not do that. This isn't my bug, so can we stop reopening this please.
