### ISSUE TITLE
No lyrics, even if files are tagged

### ISSUE THREAD

**Issue by Sancoraa** [fatg3erman/RompR#142]
I have checked my files are correctly tagged using Picard, and they certainly are.
However, when I check the lyrics section in RompR, I get the following message : 
```
No Lyrics were found
To use the lyrics viewer you need to ensure your local files are tagged with lyrics
```

I have made sure that in the settings it is correctly pointed to my music folder.
Thanks for any help !

**Comment by fatg3erman** [comment]
Works for me. Check that your webserver has read access to your music files. If that doesn't help then I need the output from the Debug Information plugin, and a debug log.

**Comment by Sancoraa** [comment]
I'm not very comfortable with webservers, I installed Rompr using docker
How can I make sure the server has read access to my files ?

**Comment by fatg3erman** [comment]
Ha, well we're both in the dark then, cos I know absolutely nothing about Docker. 

Your webserver process will be running with a specific userid. If that userid doesn't have read access to your files then Rompr can't scan them for tags. I don't know what that userid will be, though.

**Comment by Sancoraa** [comment]
I did a `chmod 777` recursively to my Songs folder, so I think it is not a permission issue

**Comment by fatg3erman** [comment]
In that case, either your docker image is running one of those distros that need permissions to be inherited all the way down from /, or I'm going to need to see a debug log.

**Comment by Sancoraa** [comment]
I'm running on an Arch based distro (ArcoLinux)
Where can I get that debug log ?

**Comment by fatg3erman** [comment]
Arch is one of those distributions that require permissions to be granted on all the directories between / and the target directory, so just altering your music directory will not work. You'll have to grant permissions on the entire directory tree. I've no idea how this affects docker but I suspect it gets even more complicated.

I'd try to fix that first, and if it still doesn't work instructions for getting the debug log are in the docs.
