### ISSUE TITLE
Enhancement for file browser: Download mp3 files

### ISSUE THREAD

**Issue by reconditefinite** [fatg3erman/RompR#145]
Enhancement for file browser:

I would like to be able to hover the mouse over any of the mp3 files in the file browser and view a url for each file. Clicking either the existing mp3 icon or on a new down arrow icon (see screenshot) would then download that file. The link below shows an example of how this could be done. Users would not have direct access to the folder where the audio files are stored but they would still be able to download them.

https://www.codexworld.com/force-download-file-php/

![files_screenshot](https://user-images.githubusercontent.com/130524049/231331852-09bba299-8b56-4749-991d-25df5d339eb2.jpg)

**Comment by fatg3erman** [comment]
This is possible provided the path to local music option is set in the Preferences and the web server is running on the same machine as the local music is stored on.
