### ISSUE TITLE
Podcast database error prevents backend service from starting

### ISSUE THREAD

**Issue by leinaht** [fatg3erman/RompR#147]
Not sure what went wrong here, but after getting everything working last night I woke up today and the backend daemon keeps running into what looks like a PHP error when updating the podcasts database. Here are my debug logs--what could the issue be? 
[romprlogs.txt](https://github.com/fatg3erman/RompR/files/11848383/romprlogs.txt)

**Comment by fatg3erman** [comment]
Thanks for the log, tells me exactly what the problem is - this is a bug. Must have forgotten to test that... Oops.

To fix it temporarily you can set 'Number to Keep' to 'Unlimited' - you'll need to make sure to do this for every podcast you're subscribed to.

**Comment by leinaht** [comment]
Thank you! That makes sense--the one change I made before running into the bug was adding a number of episodes to keep, so I've changed that back and it's working again.

**Comment by fatg3erman** [comment]
Fixed in 2.06
