### ISSUE TITLE
Version 2.07 is "repackaged" version 2.06

### ISSUE THREAD

**Issue by gjoelong** [fatg3erman/RompR#151]
Just installed the upgrade, going from 2.06 to 2.07 - thanks.
But it is still 2.06.

Looking at the assets for the zip file it is the files dated for the 2.06 release repackaged for 2.07.

So, I think I just reinstalled version 2.06.

**Comment by fatg3erman** [comment]
Whoops. Forgot to actually push the code to GitHub :)

2.08 just released, and this one should be correct.
