### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: fclose(): 

### ISSUE THREAD

**Issue by sevi4310** [fatg3erman/RompR#152]
I am on Debian 12, PHP8.2, Apache2
Did all instructions from:
https://fatg3erman.github.io/RompR/Installation-on-Linux-Alternative-Method.html
Getting this error (/var/log/apache2/error.log)
[Mon Oct 30 00:30:35.785374 2023] [php:warn] [pid 17771] [client 192.168.1.22:55731] PHP Warning:  fopen(prefs/prefs.lock): Failed to open stream: No such file or directory in /var/www/html/rompr/includes/prefs.class.php on line 351
[Mon Oct 30 00:30:35.785709 2023] [php:error] [pid 17771] [client 192.168.1.22:55731] PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in /var/www/html/rompr/includes/prefs.class.php:352\nStack trace:\n#0 /var/www/html/rompr/includes/prefs.class.php(352): fclose()\n#1 /var/www/html/rompr/includes/prefs.class.php(409): prefs::lock_prefs()\n#2 /var/www/html/rompr/includes/prefs.class.php(440): prefs::save_prefs_file()\n#3 /var/www/html/rompr/includes/prefs.class.php(658): prefs::save()\n#4 /var/www/html/rompr/includes/vars.php(65): prefs::early_prefs_update()\n#5 /var/www/html/rompr/index.php(9): require_once('...')\n#6 {main}\n  thrown in /var/www/html/rompr/includes/prefs.class.php on line 352
![image](https://github.com/fatg3erman/RompR/assets/59147445/78949f22-b699-4a53-a2a3-20fb19409f0f)

**Comment by fatg3erman** [comment]
Does your prefs directory exist, and does the webserver have write access?
