### ISSUE TITLE
Discoverator play media from local library KO?

### ISSUE THREAD

**Issue by Lionel642** [fatg3erman/RompR#155]
Hello;

I'm not sure is this is supposed to work like that, if I double click an album from Discoverator that I'm sure I have in my music library, it never plays, is the Discoverator supposed to work without Spotify (or other)? 

And actually is it possible to tell it to only propose albums that are in the local music library?

Regards,
Lionel

**Comment by fatg3erman** [comment]
No, the Discoverator is supposed to be about finding new music you have never heard before. It won't be of much use if you don't have Spotify. I think it might work with youtube music as well.
