### ISSUE TITLE
FR: Easier profile switching

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#16]
It would be nice if the source profile switching is exposed in one of the main menus especially in the mobile uis, instead of going through the preferences. For instance we could have additional icons for each of the Mpd/Mopidy instances under the vertical hamburger menu button thing, with some randomized colors or numbers to differentiate them. That list can be a bit longer with additional stuff like this. 

Also it would be nice to have an indidication of the current profile somewhere in the browser.

thanks

**Comment by gerroon** [comment]
Extending on this req, one idea that have for the mobile is that it can be nice to access to the profiles via some kind of url extension like "http://xx.xx.xx.xx/rompr?profile=mpda", this way one can bookmark/create mobile desktop shortcuts for each player, so if you hhave 3 players, you can have 3 different rompr shortcus on your phone's home. 

Ideal Rompr should name the browser title with player name, so these shortcuts are created with proper names.

thanks

**Comment by fatg3erman** [comment]
In fact, thinking about it, the player choice is set by a Cookie, so making multiple shortcuts will not work as the Cookie will be set for all of them, because that's how browsers work.

**Comment by gerroon** [comment]
You can edit the shortcuts for the booksmarks, but I am not sure if I can edit name/url of the web apps that is added to the phone's home or desktop.

Well clicking couple times, scrolling is not that much of work sure except on mobile. it is just a usability suggestion.


If you consider moving the profile switched, but do not want put in the current window, I propose that putting the profile switch just above or just below the theme settings could places to consider.
