### ISSUE TITLE
PHP Fatal Error:  Uncaught TypeError

### ISSUE THREAD

**Issue by NullDev42** [fatg3erman/RompR#162]
I'm hoping you can help point me in the correct direction.  I'm attempting to build Rompr into a docker container and I'm hitting a PHP Fatal error.  Specifically:

```
[error] 27#27: *26 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /app/rompr/index.php:223) in /app/rompr/includes/prefs.class.php on line 405; PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /app/rompr/streamplugins/classes/commradioplugin.class.php:106
Stack trace:
#0 /app/rompr/search/g_search_commradio.class.php(13): commradioplugin->get_country_list()
#1 /app/rompr/includes/search_handler.class.php(64): g_search_commradio->__construct()
#2 /app/rompr/skins/desktop/skin.php(207): search_handler->create_search_panel()
#3 /app/rompr/index.php(323): include('...')
#4 {main}
  thrown in /app/rompr/streamplugins/classes/commradioplugin.class.php on line 106" while reading upstream, client: 172.17.0.1, server: _, request: "POST /index.php?force_restart=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "localhost", referrer: "http://localhost/"
```

I've tried using Alpine:3.20 and Debian:Bookworm base images with PHP 8.2 and PHP 8.3 and have gotten similar results.  I did regression testing and I have to go back to Romper v1.61 before it works properly.  I'm developing in Windows 10 using WSL and Docker desktop.

The container has these packages added to the base image:
nginx, php-fpm, php-sqlite3, php-json, php-xml, php-mbstring, php-gd, php-curl, php-intl, curl, imagemagick

The Rompr page loads the "infobar" and most of the "headerbar" and fails during creation of the "playlistcontrols" block with everything else blank.

Thank you in advance for your time and help.

**Comment by NullDev42** [comment]
I enabled additional details in the logging and found this just prior to the failure, so I suspect it might be related possibly:

```
2024/07/04 16:48:56 [error] 18#18: *19 FastCGI sent in stderr: "
; PHP message: DEBUG : URL_DOWNLOADER  : (get_data_to_file)         
: Downloading https://api.spotify.com/v1/markets to file 
; PHP message: DEBUG : URL_DOWNLOADER  : (check_cache)              
: Returning cached data prefs/jsoncache/spotify/9be36397f5dac9d40d7dd083f71a6d7b" while reading upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "localhost"

2024/07/04 16:48:56 [error] 18#18: *19 FastCGI sent in stderr: "
; PHP message: TRACE : PREFS           : (set_cookie_pref)          : Setting Cookie collectiondomains to Al
; PHP message: PHP Warning:  Cannot modify header information - headers already sent by (output started at /app/rompr/index.php:223) in /app/rompr/includes/prefs.class.php on line 405
; PHP message: MARK  : SEARCHHANDLER   :                            : Initiating Blomquist Transfusion
; PHP message: INFO  : INIT            :                            : Including search/a_search_player.class.php
; PHP message: INFO  : INIT            :                            : Including search/d_search_podcasts.class.php
; PHP message: INFO  : INIT            :                            : Including search/g_search_commradio.class.php
; PHP message: LOG   : COMMRADIO       : (get_server)               : Using 89.58.16.19
; PHP message: DEBUG : URL_DOWNLOADER  : (get_data_to_file)         
: Downloading https://89.58.16.19/json/countries?hidebroken=true to file
; PHP message: WARN  : URL_DOWNLOADER  :                            :   ..  Download Failed With Status Code 0; PHP message: WARN  : CACHE HANDLER   :                            : There was an HTTP error
; PHP message: WARN  : CACHE HANDLER   :                            : 500 Internal Server Error
; PHP message: PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /app/rompr/streamplugins/classes/commradioplugin.class.php:106
```
Trying to pull up "https://89.58.16.19/json/countries?hidebroken=true" in my web browser chokes due to a certificate error:
```
Firefox does not trust this site because it uses a certificate that is not valid for 89.58.16.19.
The certificate is only valid for at1.api.radio-browser.info.
Error code: [SSL_ERROR_BAD_CERT_DOMAIN](about:certerror?e=nssBadCert&u=https%3A//89.58.16.19/json/countries%3Fhidebroken%3Dtrue&c=UTF-8&d=%20#certificateErrorDebugInformation)
```
If I swap out the IP for the domain in the cert (https://at1.api.radio-browser.info/json/countries?hidebroken=true), I get a proper loaded page.  I'll dig a bit in the Rompr code and see if I can find where this URL is formed.

**Comment by fatg3erman** [comment]
I don't know anything about docker, and I can't really debug without a debug log. The error message suggests that the data you're getting from the Community Radio API is not valid in some way. Quite often things like this are permission problems, first check the read/write permissions on the prefs directory. If that isn't it then a debug log is needed.
There is already a RompR docker container, it's linked from the docs. Maybe that would help?

**Comment by fatg3erman** [comment]
Ah I've just seen the edit. Wiedrly though I'm not getting that error so something in your setup is causing that failure. No idea what that would be, Seems like your PHP is checking certificates. Never heard of that behaviour before.

**Comment by fatg3erman** [comment]
This is an issue with your setup not doing reverse DNS lookups. The rules for using the community radio API state that I have to pull a list of IP addresses, choose one at random, and then change that back into a DNS name using gethostbyaddr(), which is what happens in commradioplugin.class.php->get_server().
On my setup the debug log shows
COMMRADIO       (get_server)               : Using at1.api.radio-browser.info
So if your setup is returning an IP address then the issue is with your DNS. I guess I need to put some code in there to trap that failure.

**Comment by fatg3erman** [comment]
Here's the fix
https://github.com/fatg3erman/RompR/commit/16702d43dcce0f54d29c487d81a9fbc862d2f773

**Comment by NullDev42** [comment]
BINGO!  That fixed it.  Thank you!
