### ISSUE TITLE
Template goes black in Chrome fullscreen mode on Android

### ISSUE THREAD

**Issue by kindlydodo** [fatg3erman/RompR#165]
This happens on my both Android devices in the Chrome Browser, both Android 14, and current Chrome version:

I do not want to display adress bar in chrome when im on rompr site, so i force chrome into fullscreen mode the following way: Go to your Rompr site and type this in the URL bar and press enter:

    javascript: (function(){document.querySelector("body").requestFullscreen();})();

Now im in fullscreen mode, and here starts the problem: the Template (default nunmalist and Phone skin) going completely dark:
![Screenshot_20240804-183835](https://github.com/user-attachments/assets/fa259b22-b8f8-40de-b1ed-73069f93815d)

This also happens on Desktop skin:
![Screenshot_20240804-184856](https://github.com/user-attachments/assets/23c5e544-f755-488c-a7e6-47c7a0da1d73)

I guess this is a client side problem therefore i did not commit debug infos (READ THIS BEFORE REPORTING BUGS). If needed, i will.

**Comment by fatg3erman** [comment]
Hmmm. I have no idea what would cause this, and I don't have an Android phone to debug it. You're right that a debug log will not help, so I don't really know what to do.

**Comment by kindlydodo** [comment]
I found the solution 

https://stackoverflow.com/questions/48051631/chrome-extension-entering-in-fullscreen-mode-turns-the-page-background-color-t

I needed to switch the ‘document.body.webkitRequestFullscreen()’ to ‘document.documentElement.webkitRequestFullscreen()’ and now it works.
