### ISSUE TITLE
Mopidy: Adding folders does not work

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#17]
I get this when I try to add/click/doubleclick/dragndroptoplaylist in the interface.  The kind of choice does not seem to matter.

"Player Error: {add} directory or file not found"

I tried it with many Mopidy sources like Dlna/LocalMedia/BeetsServer etc with the same result. However If I enter an erroring folder and just click on a song it just plays. I am not sure if this is a limitation with the Mopidy source.

thanks

**Comment by fatg3erman** [comment]
Confirmed. It happens with MPD too, it's related to CD Player Mode.

**Comment by gerroon** [comment]
thanks for looking into it.
