### ISSUE TITLE
Turkish characters not rendered properly

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#20]
```Fikret Kızılok = Dünden Bugüne```  shown as 

See the image

![wrong](https://filebin.net/qyzflvem7wnaz70y/asdsad.png?t=09wj2gq8)

**Comment by fatg3erman** [comment]
Where is this? Is it an album in your collection? Are the tags in the files in UTF-8 format? MPD or Mopidy?

It might also be an issue with the font you're using. Not all fonts support all character sets.

**Comment by gerroon** [comment]
THis is in Iridium (Chrmium clone).  Same with Waterfox, rendered improperly.

The song is in the current queue. I never had this issue rendered improperly in other apps.

I saved the tags with picard from  MB databse. I checked it again now and it looks fine in Picard.

**Comment by fatg3erman** [comment]
So it looks like the data coming from Mopidy is incorrect. Works for me.

<img width="306" alt="screen shot 2018-06-13 at 19 29 56" src="https://user-images.githubusercontent.com/1430781/41370725-4b68e2ca-6f40-11e8-9683-ba1efa13e7fb.png">

**Comment by gerroon** [comment]
Are you testing it in Mopidy?

**Comment by fatg3erman** [comment]
Yes

**Comment by gerroon** [comment]
OK thanks for looking into this, I am going to investigate this.

**Comment by fatg3erman** [comment]
Are you using the json local database with mopidy, or mopidy-local-sqlite?

**Comment by gerroon** [comment]
I think it is json stuff, I did not set any database.

**Comment by fatg3erman** [comment]
My guess is that is the problem.

**Comment by gerroon** [comment]
hmm, ok thanks I will look into installing it.

**Comment by gerroon** [comment]
I am convinced tyhat this is a Mopidy issue, and Rompry is not at fault here.

**Comment by gerroon** [comment]
If anyone else is having the same issue

set (in mopidy.conf)
default_encoding = utf8

under [m3u]

The Rompr renders them correctly as well
