### ISSUE TITLE
FR : Show source for wishlist tracks

### ISSUE THREAD

**Issue by fatg3erman** [fatg3erman/RompR#23]
Show some kind of icon/name where the starred song from when it was starrred, is it local, is it online radio, name of the radio maybe, date ? I think this can help for relocating the song, and can be like a bit of listening journal thing, see when and how all those stars and wishlist originated.

**Comment by gerroon** [comment]
This is going to be super useful mainly because some tracks form online radios are exclusive, never played before or rare tracks that are not available online. This way one can at least track back to the source

**Comment by fatg3erman** [comment]
OK this is qjuite easy. I can add it so that the wishlist records the radio station you were listening to when the track was added to it, and the wishlist viewer allows you to start that station playing.
