### ISSUE TITLE
FR: Subsonic API :)

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#24]
I can totally hear @fatg3erman screaming "nayn nayn, noooo, naaaaa", but please take a deep breath for a sec before crushing this bug to death.

One of the main issue with MPD based setups is that it is purely streaming, meaning that no offline stuff especially for the mobile users. Subsonic(and derivatives) have good mobile/desktop clients that offer various features, one of them is letting user download music.

I personally use Dsub just to download some songs to my phone/tablet before going out, because I do not have constant internet and sizable data connection is still expensive for me and many users around the world. The nice thing about Dsub is that (though not much updated) I can star/rate while offline, and they get synced to Airsonic server(Subsonic derivative) later.

Another nice thing about Dsub is that, it offers casting to Dlna/Upnp devices (like Kodi) which is very convenient, so one does not have to stream on Mpd and setup listening clients. It is a bit clunky because what plays music is different than what controls music and what streams the music (though powerful), though in some occasions Rompr offers nice controls.

By offering a Subsonic API compatible API, one might be able to use all those clients with Rompr against Mpd/Mopidy. 

I like the mobile Rompr interface  it is as good as it gets, though still can use some optimisation on the cpu side. But it does not offer offline content. So that is one of the reason I am opening this feature.

If the dev(s) plan to implement this in  like 1.000.000 years which is not bad of a wait time, please take a look at Ampache, it offers a decent compatible API that I used to use. Maybe it can give you an idea to see what it takes to implement, or see the positive sides of having it.

I realize maybe this is an impossible thing to do given that Mpd does not offer downloads itself, but Ampache does with ffmpeg transcoding I think.

https://github.com/ampache/ampache/wiki/API#subsonic-api

**Comment by gerroon** [comment]
@fatg3erman 

You got it backwards :) I actaully meant that Rompr impersonates a Subsonic server, not act like a subsonic client. 

Please see Ampache for Subsonic api, any Subsonic client can connect to Ampache and play music from it. 

Mopidy-Subsonic is just a client for Subsonic that makes Mopidy to grab song stuff from a Subsonic server.

**Comment by fatg3erman** [comment]
That's impossible.

Rompr runs in a browser, and the browser has no access to the host filesystem, so downloading tracks through Rompr cannot be done.

**Comment by gerroon** [comment]
Well, Ampache does it? Ampache runs in a browser too (and implements Mysql+Apache). I mean Rompr seems close to Ampache as far as aI can tell, it is just that Ampache lets you also stream inside the browser. I might be dead wrong on it since I am not a dev.

 I do not want to take more of your time on this but check Ampache whenever you ever have any time to waste.

**Comment by fatg3erman** [comment]
No, you can download to the Ampache Server but that is not the same as downloading to your phone.

Also, downloading tracks from Spotify/GMusic etc is a violation of their terms of service, so I am never going to implement that.

**Comment by gerroon** [comment]
Not sure, I think that you have a different conception in your mind than what I am trying to explain here. I am guessing that because you never went the route of Subsonic/Dsub/Ampache route you might be thinking something else. 

I never mentioned spotify or gmusic myself. Subsonic api has nothing to do with online services and it would be only for local music.

**Comment by fatg3erman** [comment]
OK it was your use of the word 'download' that made me think of downloading from spotify etc. I think I understand what you mean, but I have to say it is VERY unlikely that I will ever implement this.

**Comment by gerroon** [comment]
If you are curious what this is all about, try Airsonic (avail on Github) and Dsub on Android (or other clients on Iphone). Setting up takes like 5 min, but again I do not want to waste your time, this is not a demand. I am just trying to expand your initial vision for your application (not a cocky way ) ;)

**Comment by gerroon** [comment]
It is ok if you never implement it, like I said, I am just putting these wishes into words, incase someone else might be interested in developing it for Rompr.

**Comment by fatg3erman** [comment]
Yes the idea of keeping stuff in sync is a good one, I've been thinking about ways to do that myself, but it needs to work with not only local files but also everything that Mopidy supports and podcasts, otherwise it is only a partial solution.

**Comment by gerroon** [comment]
@fatg3erman 

I am glad that we are on the same path for the initial goal. That is why Subsonic api seemed to make given that there are bunch of clients avail already. 

Most of the time these kinds of things are more about the client app than the server. If the client sux, it does not matter how awesome the server is. 

To me the usability is #1 for media related stuff, I like the current mbile ui, it is very nice in general, but missing offline stuff, synching music etc is the issue like you mentioned as well.

**Comment by gerroon** [comment]
Btw check out Koel, it lets you download music in a zip, though I am not a big fan of that method either. because that is quite a qork to get going on a Mobile device.

**Comment by gerroon** [comment]
Also I like to iterate another nice thing about Dusbone more time . Being able to cast to Dlna?upnp enabled devices, that way you can send your audio to any Tv, stereo, Android, Chromecast etc device in different rooms. I find this to be priceless because then I do not need to setup multiple stream players for Mpd manually.

**Comment by fatg3erman** [comment]
This topic is not relevant to Rompr.
