### ISSUE TITLE
FR: Search with MusicbrainzID if avail

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#29]
HI

I can`t be sure about this but I think that Rompr is not using MusicbrainzID to get info from the MB site.

Here is an example, I played track 7 from it but it was not able to pull any info in the MB tab. The tracks have all the neccessary MB ids created by Picard.

https://musicbrainz.org:443/release/248670a2-2f06-4203-b90f-27635d43a389

I get 

"Could not find this artist on Musicbrainz"
"Could not find this album on Musicbrainz"

From the metadata

artist id :9a4bb654-35c5-4c88-8460-39d5bb01aa57; 22872b62-5faa-43f3-8a45-f4386385af1d; 3a9f0e21-5796-4f04-bd4c-3deafd59ad80

racording id: c43eb169-b9e4-4c4d-851f-ae6e5e9cc77f

release id: 248670a2-2f06-4203-b90f-27635d43a389

**Comment by gerroon** [comment]
Btw the gitq forum paghe is borked, whenever I try to post (I lost couple posts already) I get 400 there, so I did not have chance to query this issue there.

**Comment by fatg3erman** [comment]
Rompr definitely uses the MusicBrainz ID if it is available. I've just tested it.

That specific artist id you posted there has 3 separate MusicBrianz IDs in it. I'd need to see the output from MPD/Mopidy to see if it harsed it correctly.

**While that track is playing:**

    telnet ip.address:port

Where ip.address:port is the address of your player

    currentsong

Send me the output.

In any case, requests to MusicBrains are both rate-limited and number-limited. If you have been doing a lot of requests you will have been locked out for 24 hours.

**Comment by fatg3erman** [comment]
Additionally, based on both this and the collection build debug log you sent, I have a suspicion that your player (MPD?) is not configured to output Album Artist information. This is a setting in your mpd.conf (Google it). Either that or your files are not tagged with Album Artist information. By default, RompR bases all of its searches on Album Artist information so if that's not available it won't have an MusicBrainnz IDs to work with.

You can also try enabling the option 'Display Composer/Performer in Now Playing' which will make RompR display all artist information it can find, and give you chooser bar at the top of the into panel. In that configuration it will be using the artist information.

Still send me the telnet output though, it will confirm things.

**Comment by gerroon** [comment]
Hi

Here is the output. 


```

currentsong
file: Music/Jordi Savall, Hespèrion XXI, La Capella Reial de Catalunya/Granada Eterna (1013 - 1526)/7-[III. EPOCA ALMOHADE] Taqsim (improv. Kanun) - moaxaja. Ya gosan naqa.flac
Last-Modified: 2018-05-08T23:11:56Z
Composer: Traditional, Ibn Zuhr
Performer: Hespèrion XXI, La Capella Reial De Catalunya
Genre: Classical
Title: [III. EPOCA ALMOHADE] Taqsim (improv. Kanun) - moaxaja. Ya gosan naqa
Date: 2016-08-12
Disc: 1
Album: Granada Eterna (1013 - 1526)
Artist: Jordi Savall, La Capella Reial de Catalunya, Hespèrion XXI
Track: 7
Time: 166
duration: 166.133
Pos: 0
Id: 2162
OK

```


I will look into the album artist for Mpd and try again. Also I use album artists, 


This the ffprobe for the example track (track 7) I mentioned

```
Input #0, flac, from '7-[III. EPOCA ALMOHADE] Taqsim (improv. Kanun) - moaxaja. Ya gosan naqa.flac':
  Metadata:
    COMPOSER        : Traditional, Ibn Zuhr
    PERFORMER       : Hespèrion XXI, La Capella Reial De Catalunya
    GENRE           : Classical
    TITLE           : [III. EPOCA ALMOHADE] Taqsim (improv. Kanun) - moaxaja. Ya gosan naqa
    TOTALDISCS      : 1
    LABEL           : Alia Vox
    TOTALTRACKS     : 24
    MUSICBRAINZ_ALBUMARTISTID: 9a4bb654-35c5-4c88-8460-39d5bb01aa57;22872b62-5faa-43f3-8a45-f4386385af1d;3a9f0e21-5796-4f04-bd4c-3deafd59ad80
    DATE            : 2016-08-12
    disc            : 1
    TRACKTOTAL      : 24
    MUSICBRAINZ_RELEASETRACKID: 6814203e-c991-40bc-8251-72176c41b2b6
    ASIN            : B01EMG5FUW
    ALBUMARTISTSORT : Savall, Jordi, Capella Reial de Catalunya, La, Hespèrion XXI
    ORIGINALDATE    : 2016-08-12
    SCRIPT          : Latn
    MUSICBRAINZ_ALBUMID: 248670a2-2f06-4203-b90f-27635d43a389
    RELEASESTATUS   : official
    album_artist    : Jordi Savall, Hespèrion XXI, La Capella Reial de Catalunya
    ACOUSTID_ID     : b9aebe68-bd0f-46fd-a494-93e80de07f62
    ALBUM           : Granada Eterna (1013 - 1526)
    MUSICBRAINZ_ARTISTID: 9a4bb654-35c5-4c88-8460-39d5bb01aa57;22872b62-5faa-43f3-8a45-f4386385af1d;3a9f0e21-5796-4f04-bd4c-3deafd59ad80
    MEDIA           : Digital Media
    RELEASETYPE     : album
    ORIGINALYEAR    : 2016
    ARTIST          : Jordi Savall, La Capella Reial de Catalunya, Hespèrion XXI
    DISCTOTAL       : 1
    MUSICBRAINZ_RELEASEGROUPID: b2907207-f3ec-4a57-b424-1e21efe88bfc
    MUSICBRAINZ_TRACKID: f56418fb-7ddf-4f02-8c8c-aad1df14a243
    ARTISTSORT      : Savall, Jordi, Capella Reial de Catalunya, La, Hespèrion XXI
    ARTISTS         : Jordi Savall;La Capella Reial de Catalunya;Hespèrion XXI
    track           : 7
  Duration: 00:02:46.13, start: 0.000000, bitrate: 702 kb/s
    Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 1500x1500 [SAR 300:300 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)


```

**Comment by fatg3erman** [comment]
As I suspetced there is no AlbumArtist field in the MPD output. Also there is no Musicbrainz info there either. I can only use the info MPD gives me.

Something wierd in the ffprobe output is that you have mutiple album_artists separated by commas and mutiple musicbrainz albumartistds, but separated by semicolons. MPD expects semicolons for multiple fields, so what you effectively have there is one artist with 3 IDs. That is never going to work.

 As this is either an issue with your tags or with your mpd configuration, I'm closing it.

**Comment by gerroon** [comment]
Hi

Thanks for looking into this. I am still investigating why Mpd does not scan for the album artist. I have been using ffmpeg for Mpd, I wonder if that is the issue.

On the other hand, lets say that that albumartist field is either missing or jumbled, how about the actual Musicbrainz IDs if they were to exist in the song? They are no use this in this case?

**Comment by gerroon** [comment]
Btw, I understand what you are saying about MB IDs separated by semicolon stuff, to be honest I haave seen all kinds stufff used for field sepearations from MB myself like ampersand, comman, semi colon, slashe etc.

**Comment by fatg3erman** [comment]
With MPD (not supported in Mopidy) Try the telnet thing again but this time issue the command

    tagtypes

You should  et a list that looks like the following:

```
tagtypes
tagtype: Artist
tagtype: ArtistSort
tagtype: Album
tagtype: AlbumSort
tagtype: AlbumArtist
tagtype: AlbumArtistSort
tagtype: Title
tagtype: Track
tagtype: Name
tagtype: Genre
tagtype: Date
tagtype: Composer
tagtype: Performer
tagtype: Disc
tagtype: MUSICBRAINZ_ARTISTID
tagtype: MUSICBRAINZ_ALBUMID
tagtype: MUSICBRAINZ_ALBUMARTISTID
tagtype: MUSICBRAINZ_TRACKID
tagtype: MUSICBRAINZ_RELEASETRACKID

```

That's mine. AlbumArtist is there, along with the musicbrainz stuf. If it's not then MPD is not scanning for it. You need to fix that and then completely rescan all your files.

The Musicbrainz IDs are no use if they have no artist to match with. In your example you have effectively one artist - "Jordi Savall, La Capella Reial de Catalunya, Hespèrion XXI" but 3 Musicbrainz IDs. Which one should I use? There's no way to tell. And in fact they're all wrong for that 'artist'.

I take your point about the tagging, but there **is** a de-facto standard, and it is to use semicolons.

**Comment by gerroon** [comment]
HI 

Thanks for the reply.

My tagtypes is quite limited it seems :( I wonder if the Debian maintainer did not compile it wiht other options, I ll look into this.

tagtypes
tagtype: Artist
tagtype: Album
tagtype: Title
tagtype: Track
tagtype: Name
tagtype: Genre
tagtype: Date
tagtype: Composer
tagtype: Performer
tagtype: Disc

**Comment by gerroon** [comment]
@fatg3erman  

Do you mind telling me how you were able to have MUSICBRAINZ_* tag types with your MPD? I cant find any info on how to add those , not sure :(

**Comment by fatg3erman** [comment]
So is it working now? Bear in mind you will have to do a full collection rescan, not just an update

**Comment by gerroon** [comment]
Yeah, I think I finally did it, I was missing the actual MB tags+rebuilding Mpd database, having albumartist was not enough I think.

Thanks for the guidelines here.
