### ISSUE TITLE
bad song index error

### ISSUE THREAD

**Issue by galaxynite** [fatg3erman/RompR#30]
If I add a series of http stream into the playlist, and try jump to next song by pressing the next track buttom, I got bad song index error.

**Comment by fatg3erman** [comment]
I can't reproduce this. Need some more information.

Player type (mpd or mopidy)
List of http urls, in order, that you added to the playlist

**Comment by galaxynite** [comment]
My case is complicated. Actually, the playlist is created by Lumin /upmpdcli instead of Rompr. I think it is not the bug of Rompr, and I know how to deal with it now. Pls close this issue. Thanks.
