### ISSUE TITLE
FR: Podcast: Flat list

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#37]
@fatg3erman 

The new podcast import combination with Mpd makes Rompr the best podcast server to me. I do not think if such server exists really.  It is just great and new level in podcast litstening, at least so far.

I am wondering what you would think about providing couple extra features. I can list all here or I can open new reports. But one of the thing that can help with dealing with multiple podcasts/episodes is some kind of addiitonal  flat list display of episodes that is sorted by the latest episodes at top. That way one could see the latest episodes or lately uploaded first at the top, and this list provides new episodes.

If such display is not possible, then I would propose that the podcast list can be sorted by the latest updates. So lets say any podcast that has updates today will be put at the top of the podcasts sesction, so the listener will know what got updated today.

**Comment by gerroon** [comment]
Sure but that is not what I am trying to explain. 


To be clear lets define the terms here

Episode: Each published segment of a podcast
Podcast: The actual published channel.


I have hundreds of podcasts (which is why I originally asked for import :)  I am asking a special way to see only updated podcast from newer to older. 

Sorting episodes within a podcast is already done as the default behavior by Rompr, which is cool but that is not the issue I am raising here.  What I am askign is a Podcast/Channel agnostic way of seeing the newer episodes in a flat list. This way the user will be able to browse lately published episodes. 

The second way I asked in case a flat list was not possible, then a special sorting method for Podcast to be sorted based on their latest published episodes.  

Lets say I have the podcasts below.  Imagine Intercepted has jsut published a new episode, then Intercepted will be at the top of the list, regardless of the podcasts original add date, or the alphabetical sort. And lets also assume that Hive45 did not pubish any episodes for a long time, then Hive45 will be at the bottom of the podcasts tab list.

I hope it makes sense

```
<outline text="3D Printing Podcast" title="3D Printing Podcast" type="rss" xmlUrl="http://3dprintingpodcast.com/feed/" htmlUrl="http://3dprintingpodcast.com" />
    <outline text="Adventures in SciFi Publishing" title="Adventures in SciFi Publishing" type="rss" xmlUrl="http://feeds.podtrac.com/bmUErl__Cjdu" htmlUrl="http://www.adventuresinscifipublishing.com" />
    <outline text="Algocracy and the Transhumanist Project" title="Algocracy and the Transhumanist Project" type="rss" xmlUrl="https://algocracy.wordpress.com/feed/" htmlUrl="https://algocracy.wordpress.com" />
    <outline text="HIVE45 Tech, Future &amp; Singularity Audio" title="HIVE45 Tech, Future &amp; Singularity Audio" type="rss" xmlUrl="http://recordings.talkshoe.com/rss83571.xml" htmlUrl="http://www.talkshoe.com/talkshoe/web/tscmd/tc/83571" />
    <outline text="In Our Time: Philosophy" title="In Our Time: Philosophy" type="rss" xmlUrl="https://podcasts.files.bbci.co.uk/p01f0vzr.rss" htmlUrl="http://www.bbc.co.uk/programmes/p01f0vzr" />
    <outline text="Intercepted with Jeremy Scahill" title="Intercepted with Jeremy Scahill" type="rss" xmlUrl="http://feeds.feedburner.com/InterceptedWithJeremyScahill" htmlUrl="https://theintercept.com/podcasts" />
    <outline text="WSJ Opinion: Potomac Watch" title="WSJ Opinion: Potomac Watch" type="rss" xmlUrl="http://feeds.wsjonline.com/wsj/podcast_opinion_potomac_watch" htmlUrl="http://www.wsj.com/podcasts" />
  </body>
```

**Comment by fatg3erman** [comment]
I was thinking about adding some sort options to the Podcasts list, I haven't decided yet what form they will take though.

**Comment by gerroon** [comment]
Thanks for considering. LIke I said, I do not think that there is a podcast listening server or even if there is any , it is probably nowhere near as nice as Rompr.

thanks

**Comment by gerroon** [comment]
Thanks for implementing the initial sorting. This is so much more useful than the initial podcast layout. Amazing premise here.
