### ISSUE TITLE
Tablet and Phone skins get  unresponsive 

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#38]
Hi

It seems like if there are couple hundreds songs in the playlist, these two skins get quite unresponsive on phones. I tried it them with FIrefox and Chromium on my phone, and both browsers got unresponsive such that pressing buttons were not doing anything. I do not get this issue with playlist with couple songs. I do  not have this issue with the same playlists on desktop.

Not sure if it is a bug or a feature but I thought I would report it.

**Comment by fatg3erman** [comment]
It's certainly not a feature :) but it's not really a bug either. Rompr does push phones to their limits in terms of resource usage, and having a large playlist will definitely make that worse.

I have a couple of ideas on how to reduce the resource usage, but some things you can do are:

1. Minimise your use of the Info panel - this does pull in a *lot* of data.
2. Use smaller playlists :)
3. Get a better phone :)

What phone are you using?

**Comment by gerroon** [comment]
Hi

I have a Note 4, it is decent.  I would like to update my phone at some point for sure :)


I am thinking that it is probably trying to cache all that cover images making it worse?

**Comment by fatg3erman** [comment]
Yes, that's one of the things that I am going to change, the playlist uses the full resolution version of the cover image so if you have a lot and they are large it is very resource intensive.

**Comment by gerroon** [comment]
Thanks and sorry for all the troubles I have been giving you since you moved to GIthub :)

**Comment by fatg3erman** [comment]
That's kind of why I moved the GitHub :) If you go to SourceForge you can practically see the tumbleweed rolling down the streets :)

**Comment by gerroon** [comment]
Then this song would be a good ending ;)

https://www.youtube.com/watch?v=i94HHGKml9M

**Comment by fatg3erman** [comment]
Perfect :)

**Comment by gerroon** [comment]
How about a another phone/tablet skin that has does not deliver album art? Maybe this can be a remedy for slow connections, helps with data plans and responsiveness issue.

**Comment by fatg3erman** [comment]
Hopefully, 1.19 will address a lot of this.

1.19 can also make use of PHP-GD to further reduce the size of images. On Ubuntu you'd do

    sudo apt-get install php7.0-gd

before running 1.19.
