### ISSUE TITLE
Podcasts: Rompr readds old podcasts as unlistened after a refresh

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#40]
I am guessing this is an issue with imports, I never used the regular podcast adding  way. 

I manually went through all my podcasts and mark them as listened (using the headphones icon), then I used the sql command  `UPDATE PodcastTracktable SET Listened = 1;` to make sure even the  new ones are tagged as listened. After overnight (set to daily update), now all the podcasts  with hundreds of episodes are all shown as unlistened.

**Comment by fatg3erman** [comment]
It's always dangerous to go messing about with SQL commands, especially when the person telling you the command hasn't tested them and gets them wrong.

    UPDATE Podcasttracktable SET Listened = 1, New = 0;

**Comment by gerroon** [comment]
cool thanks I will try this
