### ISSUE TITLE
FR:Podcast: Resume episode

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#42]
I am sorry but I have to ask for this :) 

This is most podcast apps can provide. Basically, when you stop playing an episode from a podcast, the player keeps the resume state (some can even do this when the episode is streamed), so next time you start playing it (unless you do not want that), it will remember where it was stopped and it will resume from that time code.

thanks

**Comment by fatg3erman** [comment]
Funnily enough I was just working on this.

**Comment by gerroon** [comment]
That is awesome. I will test it out from the dev branch.

**Comment by fatg3erman** [comment]
Careful with the dev branch, it can be very unstable. Don't rely on it working, I'm still testing it.
