### ISSUE TITLE
QA: Local album art?

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#43]
Hi

Somehow I am unable to post to the forum, so I am going to ask this one here. I will try not to use github issues as  a forum, but until I find out why qitq is broken for me (must be a firewall kind of thing) I need to spot an answer for this.

Does Rompr use the local images automatically if present (cover.jpg) at all? Because when I browse the album cover browser, it shows me some albums that both has local cover and also has embed cover in them. So I am thinking that it is not using it?  Weird thing is that, I can load those covers from the local  images tab, so images are not missing as far as I can tell. 

If it is not using them, is it possible to provide a cover art server that Rompr can try using? For instance Mopidy can already serve cover arts , also I am running a Lightttp server on my server for my covers arts to couple Mpd clients like Malp. It works well and I definetely prefer that Rompr uses my cover arts before going out its own way. 

I have gone through huge trouble to add as much cover art (and some are my own covers) as possible and I would like to avoid redoing this work in Rompr. I know I can select local images in the cover browser, but in reality Rompr says , "9402 albums, 4815 albums without a cover" As you can see this is soo much work for me :(

See this page for how Mpd cover art tricks work if you have not came across.

https://github.com/abarisain/dmix/wiki/Album-Art-on-your-LAN

thanks

**Comment by fatg3erman** [comment]
I would prefer if people didn't use Issues for asking questions, as issues is a list of things I need to work on and I will close them if they don't need any work. I'd like questions like this to be on a forum where people can browse them. Is gitq really never working for you? It is having some issues and is up and down. Be patient and wait.

If you can see them from the local images tab then you have configured it correctly. One thing that may have happened is that Rompr has searched once before you configured the local music path. Once it has searched once unsuccessfully it will not search automatically again - but 'Get Missing Covers', or 'Get These Covers' in the album art manager should still update them with your local images. Please try that.

Mopidy does not serve local cover art through its MPD interface, and the patch I made to make this work proved to be so slow that it was pointless.

**Comment by fatg3erman** [comment]
Oh, also, Rompr has a list of filenames it matches to:

"cover", "albumart", "thumb", "albumartsmall", "front"

(with any image file extension). If your images aren't named like that they won't be used automatically unless there's only one image in the folder in which case that will be used.

**Comment by gerroon** [comment]
I get error big red 500 when I try press post button on the gitq forum. Like I said in my initial entry here, I wont use it that way, this is an exception but I need to resolve this and it is the only way I am able to contact you. 

Mopidy does not serve cover art via Mpd sure, but it has a local image extension that serves as far as I understand. 

All my images are named "cover.jpg". 

I will try auto update again.

thanks

**Comment by fatg3erman** [comment]
Mopidy's local image extension is not connected to the MPD backend. There is no way to use it. Also, it is hellishly slow, as I explained.

This is the last time I will respond on the Issues board to something that is not a bug. I am only one person. Nobody else read this.

**Comment by fatg3erman** [comment]
Actually, it does appear as though gitq is broken, and the contact page brings up a 404 error... Keep using the Issues board for the time being, I will try and find a better host for the forum.
