### ISSUE TITLE
DEV: Google Api slots are missing

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#45]
Hi

It looks like the Google api slots in the preferences window is missing from the dev branch. The Lastfm one is there but I am not seeing the Google stuff there.

**Comment by fatg3erman** [comment]
Read the Changelog (docs/Changelog.md).

**Comment by fatg3erman** [comment]
Please read all available documentation before raising issues. I put a lot of effort into the documentation so that I don't have to keep answering questions
