### ISSUE TITLE
Podcast stops playing after pause.

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#48]
Hi,

I am not sure if this is an issue with Mpd or Rompr. 

The podcast playing seem to be distrupted if the podcast has been paused for sometime. For instance, start playing an episode for a while, then somewhere in the middle pause the playing. Wait about 20 mins then resume the play, the podcast plays for couple minutes then stops/resets play. 

I am able to repeat this issue many times, so I thought maybe it is time to bug about it.

I am using Rompr (Debian Testing) with Mpd (Debian Testing).

thanks

**Comment by fatg3erman** [comment]
MPD problem. Pausing anything being streamed doesn't actually pause the stream, it just mutes the output and throws the streamed data away, because MPD can't tell the difference between a podcast episode and a radio stream. Mopidy sometimes handles this better.

**Comment by gerroon** [comment]
Ok thanks, it makes sense.
