### ISSUE TITLE
Secured with .htaccess breakes streaming the downloaded episodes

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#50]
I secured the site with .htacces with basic auth.  When I open Rompr I enter the creds and open the site. Everything works except the downloaded podcasts. I am guessing that it is trying to stream from the server then fails, because the site is hardened with .htaccess. 

The original remote streams work fine no problem.

This is what I get

 `MPD                 Clearing Player Error Failed to decode http://xx.xx.xx.xx/rompr/prefs/podcasts/248/18784/format=VBR+MP3&ignore=x.mp3; CURL failed: The requested URL returned error: 401 Unauthorized`

```
AuthType Basic
AuthName "Password Protected Area"
AuthUserFile /var/.pass/.htpasswd
Require valid-user

 <Limit GET POST>
 require user USERNAME
 </Limit>

```

As a  user I guess I am fine with it if there is no solution ((prefer security over convenience). I will just listen the stream version, and download for archiving. 

I thought I would point it out.

**Comment by fatg3erman** [comment]
Yep, nothing I can do about that. The downloaded ones are streamed from the server so until MPD supports authorisation a secure server isn't going to work.

You might be able to work around it by setting no authorisation on the prefs/podcasts directory, though I'm not sure how you do that with .htaccess. Should be fairly secure though as it's only downloaded podcast episodes and images in there.

**Comment by gerroon** [comment]
@fatg3erman 
Thanks for the reply. LIke I said I realized that nothing can be done about it. It works fine as is gien that I can stream from the original source. I just added it here in case someone else will have the same issue.
