### ISSUE TITLE
EDGE & IE11 Browser cant render latest version of ROMPR

### ISSUE THREAD

**Issue by TheBodger** [fatg3erman/RompR#58]
Running the latest rompr on raspbian, it renders fine in chrome and firefox but none of the windows browsers (edge, internet explorer on win 10, IE11 on win 2008)

![image](https://user-images.githubusercontent.com/41484656/43014561-76fadda0-8c44-11e8-80b6-ed398558158d.png)

**Comment by fatg3erman** [comment]
Undortunately I can’t support non-standards compliant Microsoft browsers since I have no way to test them. Rompr supports Chrome, Firefox, Safari, and Opera. I’m unable to fix problems in other browsers.

**Comment by fatg3erman** [comment]
Also windows 2008 is a decade old. No browser that old will render rompr properly.
