### ISSUE TITLE
Funky Album art errors in Albumart

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#59]
Hi

I have been testing the bleeding edge commits, and I think that something has changed the way album art is/can be added via the Albumart manager. I tried many albums covers, even ones that already have album art assigned and I am getting errors applying it. This was working fine before but when I do not know. It must be a change in recent commits.

Lets say I have an album that has a local cover art that I can see in the Albumart manager, I click on the image (it is listed there already), but when I click on it, the thumbnail turns to generic CD back with "image not found" written on it. And this is the log I get from the log.

```
21:35:19 :    26089 : GETALBUMCOVER       ------- Searching For Album Art --------
21:35:19 :    26089 :  key                 efe6c6d32b5cac3fc5deafbac955f67d
21:35:19 :    26089 :  artist              
21:35:19 :    26089 :  album               
21:35:19 :    26089 :  imgkey              efe6c6d32b5cac3fc5deafbac955f67d
21:35:19 :    26089 :  source              http://192.168.1.100/rompr/prefs/temp/81f96c24e0bea7f80764ceb45f168af2
21:35:19 :    26089 : GETALBUMCOVER       Found album Cloneo in collection
21:35:19 :    26089 : URL_DOWNLOADER      Downloading http://192.168.1.100/rompr/prefs/temp/81f96c24e0bea7f80764ceb45f168af2 to prefs/temp/efe6c6d32b5cac3fc5deafbac955f67d
21:35:19 :    26089 : URL_DOWNLOADER        ..  Download Failed With Status Code 401
21:35:19 :    26089 : GETALBUMCOVER       No art was found. Try the Tate Modern
21:35:19 :    26089 : GETALBUMCOVER       --------------------------------------------
```

My server has not changed at all, and I just made sure that my music is 777.

**Comment by fatg3erman** [comment]
HTTP error 401 means Unauthorised. You said you’ve been using a password with . htaccess. 

So your server confifuration most definitely has changed, and that has broken local album art. I’m not going to fix that, as I don’t think it’s possible.

**Comment by fatg3erman** [comment]
There is a workaround, you can disable authentication for the prefs directory. This would also make downloaded podcasts stream correctly.

    rompr/prefs/.htaccess:

    Require all granted

There is some slight danger in doing this, in that your Music folders are symlinked from within prefs, but this is the only way you're going to get this to work.

Your log still looks slightly odd though, in that the source image appears to be in prefs/temp. I'm not sure how that could happen.

**Comment by fatg3erman** [comment]
Ignore my comment about it being in prefs/temp, that's what happens when you have album art embedded in local files. It's fine.

**Comment by fatg3erman** [comment]
Of course, once I thought about it and looked at the code, it was trivial to actually fix it so it works without doing an override... :)

**Comment by gerroon** [comment]
Sorry about not bringing .htaccess change I did recently. I did not think that it would affect this issue since it was local file as you said. I will think about these issues better next time.

I am going to try the fix, thanks for being a speedy fat g3rman.
