### ISSUE TITLE
FR: Album Art Wall

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#61]
I think that album art wall style album browsing is the one feature that will grab more people's interest in Rompr. An efficient way of browsing albums with their covers layed out in a grid (or even an adaptive grid) would look very sexy. I think that is one reason most people use Iris for Mopidy or Emby, AIrsonic etc.

**Comment by fatg3erman** [comment]
Try Skypotao skin

**Comment by gerroon** [comment]
I tried skypatato before but I did not think about browsing in album mode, seems to work well.  

it is a big sluggish on the other hand. is it using the optimized cover modes? Album mode feels very slow in general in the tree view mode, but in skypatato, it is not as bad.


also it does not seem to respond the "added today", "added this week" etc filters. 

i think that you should put a screenshot of this type of album wall (with dark theme maybe)  to grab some interest

thanks

**Comment by fatg3erman** [comment]
I'll look into the filters on all the skins, I haven't tested that yet.

As for speed, well it's running in a browser, it'll never be fast. There's nothing I can do about that, browsers aren't really designed for that sort of load. On the other hand, which browser are you using? By far and away the fastest browser for displaying images is Firefox. Chrome is appalling, and Safari is somewhere in between.
