### ISSUE TITLE
FR: Stream

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#63]
Hi

I wonder how viable it would be to provide streaming inside the browser. From a user perspective that would cut down on multiuple apps usage to stream, I use VLc type apps to stream from my MPD http outputs. I know some people like Koel because they can play their music right in the browser. Would it be possible to provide that functionalty in the browser? 

Obviously this can only happen if Mpd (Mopidy Icesast does not work at the moment, at least for me) has http outputs defined. And Rompr can make an educated guess on which output to stream from, or even can be defined in the player settings. That way we can get play/pause button in the notification area on Android, I think this is a default browser thing when media is playing. So people end up not needing to use multiple apps to stream when they are away from their servers.

thanks

**Comment by fatg3erman** [comment]
Somebody tried making a patch to do this a couple of years ago, but it didn't work. It's horribly complicated to do. I'm not going to say 'no', but it won't happen any time soon :)

**Comment by gerroon** [comment]
Yeah I figured it is not a trivial thing to do, but I am glad that you are not againts it.

**Comment by Chreece** [comment]
hey @fatg3erman sorry for reopening this.

first of all, great project! looks amazing!

I just wanted to inform you that IRIS which also implements snapcast allows you to stream in the browser via snapcasts stream.
So, if they, why not you?

Keep up :D

**Comment by fatg3erman** [comment]
Because I've no interest in doing it and no need for it. If you wish to submit a patch, feel free :)
