### ISSUE TITLE
FR: Mobile: Add volume buttons

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#65]
Hi

I think that it would be great if the mobile UIs have additional volume up and down buttons in the playing now window

atm 

```(<<) (>) ([]) (>|) (>>)```

with volume buttons

```(-)  (<<) (>) ([]) (>|) (>>) (+)```

thanks

**Comment by fatg3erman** [comment]
It's only one tap tp get the volume control to show up, is that really so much effort?  The interface has enough buttons as it is, not to mention the fact that this wouldn't fit on small screens, nor on some of the responsive layouts on larger screens. I don't think I'm going to do this.

**Comment by gerroon** [comment]
Well it is not a number of tap thing but the slider is hard to control precisely sometimes.
