### ISSUE TITLE
Global Podcast update does not update

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#66]
Hi

I think that there is some funky in the way the global update control for the podcasts. 

When I click on update/refresh in the global section of the Podcasts tab, I see in the log that some update activity happens, but that seems to be a gimmick because the actual podcasts have no update shown, even after I restart the browser. However if I go into a poidcast that I suspect it probably has a new episode and click on the podcast's own refresh button, it gets the new episodes.

One curious thing I see in the log is this line (when global refresh is used)

```PODCASTS            Podcast has not been updated since last refresh```

Maybe this is preventing Rompr from getting the podcasts for real?

**Comment by fatg3erman** [comment]
There's no difference in code path between the two update mechanisms. The message you're seeing simply indicates that the podcast has not published any new episodes since you last refreshed it.

I'll look into it, since I've had suspicions myself that something isn't right with the refresh mechanism.

**Comment by fatg3erman** [comment]
I've made a slight tweak to the refresh code and put in some more debug output. If it happens again, send me the complete log showing the global refresh and the refresh of the podcast that does show new episodes. I need to see the whole thing.

**Comment by fatg3erman** [comment]
Closing because this has been open for so long and no further problems reported.
