### ISSUE TITLE
mysql 8.0 Authentication

### ISSUE THREAD

**Issue by rawdlite** [fatg3erman/RompR#70]
Using mysql 8.0 i had issues to authenticate.
Problem was Caching SHA-2 Pluggable Authentication was not supported.
This solved the issue.

`CREATE USER 'rompr'@'%' IDENTIFIED WITH mysql_native_password BY '$PASS'`

HTH

**Comment by fatg3erman** [comment]
Thanks, already found that one. Crazy how they completely changed the default authentication method to something that nothing supports!
