### ISSUE TITLE
Sqlite3 unable to open database file

### ISSUE THREAD

**Issue by rawdlite** [fatg3erman/RompR#71]
I am trying to setup a rompr docker container using sqlite.
This is to provide an alternative to the (slightly) more complex multi container setup that i got working now.
Now i run into the problem that rompr claims 
`SQLSTATE[HY000] [14] unable to open database file`
I also see:

```
<b>Warning</b>:  file_put_contents(prefs/prefs.var): failed to open stream: No such file or directory in <b>/app/rompr/includes/vars.php</b> on line <b>284</b><br />
--
  | <br />
  | <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /app/rompr/includes/vars.php:284) in <b>/app/rompr/index.php</b> on line <b>111</b><br />
  | <br />
  | <b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /app/rompr/includes/vars.php:284) in <b>/app/rompr/includes/functions.php</b> on line <b>479</b>
```
But i assume this is triggered by the first error.
The prefs directory is there and it is writable 

`drwxr-xr-x 1 www-data root  4096 Sep  5 07:30 prefs/`

Directory is empty though.
php -i tells me (among other things) that sqlite is installed

```
SQLite3 support => enabled
SQLite3 module version => 7.2.7-0ubuntu0.18.04.2
SQLite Library => 3.22.0

Directive => Local Value => Master Value
sqlite3.extension_dir => no value => no val
```

Since this error happens early on no debug log gets written and i am at a loss now where else to look.
I am running "Ubuntu 16.04.4 LTS" in the container.

**Comment by fatg3erman** [comment]
That's definitely a write permissions problem. Both errors indicate that it's unable to create any files in the prefs directory. It should also have created all the cache directories in there which hasn't happened, so it's nothing specifically to do with sqlite.

It's hard to tell exactly what the problem is though, as you say. 

Some ideas:
I'd first suggest changing permissions on prefs to global read/write, just to see if that works. 
However the failure to open prefs.var indicates that the prefs directory doesn't exist, or can't be found.
Is prefs definitely in the right place?
Is your apache (or ngnix) conf file pointing to the correct location?
If using Apache, check php_value include_path in your apache conf file. If using nginx, check it in the php.ini. Should be '.'

**Comment by fatg3erman** [comment]
I'm also suspicious about

    /app/rompr/includes/vars.php

which looks a little as though you're accessing rompr from a URL something like 

    http://some.ip/app/rompr

Is that right? If so, I don't think that will work. Needs to be http://some.ip/rompr or just http://some.ip/

If your install needs dep directory structures you need to symlink /rompr into your system webroot.

**Comment by rawdlite** [comment]
Hmm,

My setup is: 
/var/www/html/rompr is linked to -> /app/rompr/

In apache site.conf i have:
DocumentRoot /var/www/html/rompr
<Directory /var/www/html/rompr>
php_value include_path .
php_admin_value upload_tmp_dir /var/www/html/rompr/prefs
...

I will focus into permissions and general apache setup then.

**Comment by fatg3erman** [comment]
I think your DocumentRoot is the problem. I don't believe I specify this anywhere in the install instructions? You shouldn't change it from the default, should be /var/www/html

**Comment by rawdlite** [comment]
After a frustrating amount of time i found the error to be at an unexpected place.
I was running the docker container on an OSX host. The same docker image runs flawlessly on a linux host.
Since i use the OSX for development only, this is ok with me for now and i will probably not investigate further.
Thank you for your support and the issue can be closed.

On a side note i found it rather convenient to define the DocumentRoot as an environment variable.
This is what i use in my Dockerfile:

`ENV APACHE_DOCUMENT_ROOT /app/rompr
 RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf`

This allows for easy changing of DocumentRoot and makes sure it is changed in all the right places.
HTH

**Comment by fatg3erman** [comment]
Peculiar. I know nothing at all about Docker so thanks for your efforts.

**Comment by lokeb** [comment]
It's not about DocumentRoot. I observed prefs folder is missing from the root. When PHP looks for `"sqlite:prefs/collection.sq3"`, it can't find the folder, thus it does not create the database and throws the error. Your gitignore file forces prefs exclusion, thus the error. You can either create the path before creating the db, or include prefs folder in gitignore.

**Comment by fatg3erman** [comment]
It is very clearly stated in the install instructions that you have to create the prefs folder and set correct write permissions on it. It is included in the gitignore because prefs contains private and transient files that must not be uploaded to a repository. Do not remove it from gitignore.
