### ISSUE TITLE
Theme settings are reseting

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#75]
Hi

I am not sure when this started but lately the theme settings are not saved at all, all theme settings I do on desktop seems to reset back to the default white theme.  I use dark themes so this issue is quite clear. This was not used to be the case, not sure when it started but probably something in the last months update.

I am using Rompr 1.26 , Apache/2.4.37 (Debian), mariadb  Ver 15.1 Distrib 10.1.37-MariaDB

thanks

**Comment by fatg3erman** [comment]
Theme settings are saved in the browser, and it's working for me. Can you try a different browser to see if it's there. Also send me the info from the Debug Information panel in the browser where it's not working.

**Comment by fatg3erman** [comment]
Also, 1.26 isn't released. I have mentioned before that breakage is to be *expected* if you run the development version.

**Comment by gerroon** [comment]
Sure I am not expecting everythign to be working in the dev version, just reporting the issue.

**Comment by fatg3erman** [comment]
OK, I need the information from the Debug Information panel in the UI, and a debug log at Level 9 (very important it's level 9) from the server. Do not use a custom logfile, I need to see all the PHP output too.
