### ISSUE TITLE
Play whole folder on mobile

### ISSUE THREAD

**Issue by Majstr** [fatg3erman/RompR#76]
I could just click on folder in file browser on mobile device to play whole folder (added on play list), but now I can not. Can you add some kind of button? 
Maybe I am missing something.

**Comment by fatg3erman** [comment]
I think you need to switch to the Tablet skin. It has never been possible to add whole folders on the Phone skin.

**Comment by Majstr** [comment]
I will try. But this will be really useful feature.

**Comment by Majstr** [comment]
On some phones I can switch to Tablet skin, but on some I can't.

**Comment by fatg3erman** [comment]
How do you mean you can't? The option is always there in the preferences.

**Comment by Majstr** [comment]
Yes option id. Bit when you choose it, page is reloaded and it automatically set back to phone. I think it has to do something with screen resolution. If I set it on my s8 its stays on tablet mode. But on phones with lower resolution is set back to phone mode.

**Comment by fatg3erman** [comment]
The skin is set as a Cookie, so if it isn't being remembered it might be that your browser is not accepting cookies from Rompr.

If you can give me a debug log **at Level 9** of what happens when you try to change to Tablet skin, I will look into it.
