### ISSUE TITLE
Snapcast support

### ISSUE THREAD

**Issue by natumbri** [fatg3erman/RompR#77]
It would be great if RompR worked more closely with Snapcast (https://github.com/badaix/snapcast) - specifically, it would be excellent if RompR could allow you to mute/unmute  snapcast clients, and to adjust their volume. This could perhaps be dealt with by the RompR volume control, similar to the way it deals with multiple outputs. It would save having to use a separate app for this, and would be centralised.

Seems like it would be fairly straightforward to implement using the Snapcast JSON RPC Control API (https://github.com/badaix/snapcast/blob/master/doc/json_rpc_api/v2_0_0.md). I'd be happy to have a crack at it, but I'd be interested to hear if people (@fatg3erman) are interested and, if so, have thoughts about the best way to do it... I'm not very good at writing code, but I'm pretty persistent.

**Comment by fatg3erman** [comment]
Yeah I rather like that idea. I'd need to have a think about how to implement it; the principal difficulty would be keeping any UI items updated if any settings are changed by another program, but there are ways and means to do that. I'm rather busy with other things at the moment; also I'm in the middle of a *huge* refactor of a lot of Rompr's core code, so I wouldn't suggest trying to do anything yourself as you'll probably have to rewrite it all once Im finished with that.

**Comment by fatg3erman** [comment]
Snapcast support is now in version 1.30
