### ISSUE TITLE
Issues when using an external Databse Server

### ISSUE THREAD

**Issue by searchingAFreeUserName** [fatg3erman/RompR#78]
First of all: Thanks for this awesome Software.
I have installed it on a Raspberry Pi and everything works fine.

Because of the Limited Space on the SDCard, i tried to move the MySql Database to a Database Server, hosted on my Nas.
At the Setup Page of RompR i changed the Adress of th Database Server from Localhost to the IP Number of my new Database. Connection was Successful, the Tabels were Greated and also the Update of my Media Library was Successful.
Playing Media from my Local Media Library is also working fine.
But: No Covers were loaded. The Information Tabs shows Errors (for Example: Wikibedia is unable to find Informations).
Links for Wikipedia for example points to "null.wikipedia.org/wiki/null". (With the local Database the same Url is "en.wikipedia.org/wiki/Artist").
Same thing with Radio Stations. With local Database, listening works fine, switching to the external Server: no Station is reachable anymore.

**Comment by fatg3erman** [comment]
That is strange. None of what you describe should depend on the database.

I'll need a debug log at level 8.

**Comment by fatg3erman** [comment]
Also the information from the Debug Information panel

**Comment by searchingAFreeUserName** [comment]
Logs in Attachment, Created on a Debian VM, because i can not reach my Raspberry PI this time. The Problem is the same.
Also two Screenshots, showing the differences.
(I Removed my Passwords and IPs from the Logs)
[debugout.txt](https://github.com/fatg3erman/RompR/files/3214249/debugout.txt)
[rompr.log](https://github.com/fatg3erman/RompR/files/3214250/rompr.log)
With external DB:
![externalDb](https://user-images.githubusercontent.com/50965012/58288034-cdaf9e00-7db2-11e9-8dff-face3b982fc2.png)
With local DB:
![localDb](https://user-images.githubusercontent.com/50965012/58288035-cdaf9e00-7db2-11e9-9d54-e40857620749.png)

**Comment by fatg3erman** [comment]
That looks like a log from the case where it is working. I can see it finding 'Welle 1 Salzburg' in the database, and all the wikipedia URLs are correct, there are no nulls. Are you sure that's a log from the case where you are using an external database?

**Comment by searchingAFreeUserName** [comment]
Starting at Line 220 ([Thu May 23 22:47:56.655611 2019) i started Switchind teh Database to my External Server.
At Line 463 (Thu May 23 23:03:52.303140 2019) i switched Back to the local DB.

**Comment by fatg3erman** [comment]
Radio station information is stored in the database when the radio station is added to the playlist. In your local database it has the correct information for the radio station, but your remote database does not - this is probably because you added the radio station to the playlist when you were connected to your local database. This explains the difference in wikipedia output.

Can you try a different radio station, adding it from one of the radio station browsers, and see if you get images and a correct wikipeida link?

**Comment by searchingAFreeUserName** [comment]
Adding another Radio Station works.
Also the Wikipedia Link is ok.

**Comment by searchingAFreeUserName** [comment]
Is it possible to reset the Playlists?

**Comment by fatg3erman** [comment]
OK, so if you want the first radio station to work correctly in your new database you need to do the following:

First clear the playlist from Rompr (trash can icon)
then, we'll reset the radio station tables in your new database:

mysql -h [database ip] [database name] -u [database user] -p[database password]
(note no space between -p and the password)
DELETE FROM RadioTracktable WHERE Trackindex > 0;
DELETE FROM RadioStationtable WHERE Stationindex > 0;
exit;

Now you should be able to add Welle 1 Salzburg back into the playlist and it will work.

**Comment by searchingAFreeUserName** [comment]
Thanks, that solved my problems.
