### ISSUE TITLE
SQLite or MySQL database is required?

### ISSUE THREAD

**Issue by EthanWeegee** [fatg3erman/RompR#80]
I have previously set up RompR on an Ubuntu 18.04 machine with no problems. However, following the same instructions on an openSUSE Leap machine, the interface throws an error:
![image](https://user-images.githubusercontent.com/22205580/62828073-5caaa600-bbab-11e9-8fff-bf3ae3ad8a6c.png)
I'm not sure where the problem is or how to troubleshoot this.

**Comment by fatg3erman** [comment]
I'm afraid I've no experience with OpenSUSE but at a guess I'd say you're missing a package. Those Warnings indicate that RompR has been unable to determine what kind of database you're using so it's likely to be a missing PHP package. I'd look for packages with names like php-sqlite, php-mysql, and php-pdo. Your web server error log might give some more information, but I don't know where that is on OpenSUSE.

**Comment by EthanWeegee** [comment]
I don't believe I'm missing a package. `php7-sqlite`, `php7-mysql` and `php7-pdo` are all installed.

I found the [error.log](https://github.com/fatg3erman/RompR/files/3490387/error.log), but I don't see anything obvious here.

**Comment by fatg3erman** [comment]
Couldn't use SQLite Either - PDOException: SQLSTATE[HY000] [14] unable to open database file in /home/server/RompR/backends/sql/connect.php:34

Suggests the permissions on your prefs directory aren't correct. You'll need to check the user and group that your webserver is running as. The install instructions were written on Ubuntu where it's www-data but it's probably not that in Suse, but I've no way to find out. If only there was some kind of standard...

**Comment by EthanWeegee** [comment]
The directory is owned by `nginx nginx`, which is the same user-group of nginx. php-fpm was configured to `nobody nobody`, changing that to `nginx nginx` causes the webpage to be grey.
