### ISSUE TITLE
php 7.4 errors "Trying to access array offset on value of type null"

### ISSUE THREAD

**Issue by CultofRobots** [fatg3erman/RompR#83]
Since the php 7.4 update on arch linux I've had a number of errors on rompr concerning mpdinterface.php on line 331

most relevant line from the nginx error log:
```
2019/12/02 06:33:11 [error] 196754#196754: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331PHP message: PHP Notice:  Trying to access array offset on value of type null in /usr/share/webapps/rompr/player/mpd/mpdinterface.php on line 331" while reading response header from upstream, client: IP REMOVED, server: rompr.SITEREMOVED.net, request: "GET /getplaylist.php?_=1575286390380 HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "rompr.SITEREMOVED.net", referrer: "https://rompr.SITEREMOVED.net/"
```
Thanks.

**Comment by fatg3erman** [comment]
:rolls eyes: PHP is a constant game of whack-a-mole.

Can you tell me *exactly* what you're doing to reproduce this, as I don't have access to a PHP 7.4 install and can't see any way this could possibly happen :)

**Comment by CultofRobots** [comment]
> Can you tell me _exactly_ what you're doing to reproduce this, as I don't have access to a PHP 7.4 install and can't see any way this could possibly happen :)
Opening rompr itself with any tracks already in mpd's queue. Starting with a clear queue and adding tracks. Pretty much everything playlist related.

php-fpm has a bunch of new security checks and features (many of which are enabled by default in the upstream service file). I've disabled most of them for the time being but that still could be the culprit. `Trying to access array offset on value of type null` is a common error I'm getting across most of my self-hosted services. For instance, Wallabag is totally broken for me specifically because of this check.

Since 7.4 was just released and arch put it in stable just this past weekend (which they probably shouldn't have yet because no one was really ready for it including the package maintainers) there's not a whole lot of info out there yet. That's about all the help I can be in whack-a-mole atm. I suspect I'm just going to roll back to 7.3 for a few more weeks.

**Comment by fatg3erman** [comment]
That's bizzarre. Usually if they're going to make a breaking change like that they start issuing warnings at least a couple of releases beforehand, but I'm running 7.2 and see nothing at all.

I suspect I just need to initialise a variable and that adding

`$dbterms = array( 'tags' => null, 'rating' => null );
`

underneath all the require_once lines in getplaylist.php would cure it. If it does then it is strictly a bug and the checks they're doing are working; it's just wierd that it never even warned me before now.

**Comment by CultofRobots** [comment]
FYI: I've got no warnings in the logs since rolling back to 7.3.9. I'm just leaving everything at that until I've had a chance to read the docs.

**Comment by fatg3erman** [comment]
I've managed to get php7.4 running under Homebrew on the mac and I was right, I just needed to initialise that variable. There were also a couple of other things that needed fixing in a couple of the external libs I'm using but I'm getting there.
