### ISSUE TITLE
Add support for mpd sticker. WARNING: Long Post

### ISSUE THREAD

**Issue by mbhangui** [fatg3erman/RompR#86]
I have just started using rompr on a small SBC from allo, which uses dietpi distribution. The distribution came with a web client O!MPD. https://dietpi.com/phpbb/viewtopic.php?t=1132

However, I find rompr much better and have managed to get it installed for lighthttpd (which is what dietpi distribution puts).

I started with mediamonkey more than 10 yrs back. Finally migrated to Linux with clementine. All my songs have been rated over more than a decade. Later when I moved to mpd, I wrote a small shell script to pull the ratings from the sqlite db $HOME/.config/Clementine/clementine.db and insert the same in mpd's sqlite sticker db. The sticker db can be enabled by having
```
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file                    "/var/lib/mpd/sticker.db"
```
mpd also provides api to get and set the rating.
e.g.
```
# get the rating for a single song
$ mpc sticker 'Dave Brubeck/Gone with the Wind - 1959/05 - B1 Camptown races (S.Foster).flac' get rating
rating=6

# get the rating for songs in an entire directory
$ mpc sticker 'Dave Brubeck/Gone with the Wind - 1959' find rating
Dave Brubeck/Gone with the Wind - 1959/01 - A1 Swanee River (S. Foster).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/02 - A2 The lonesome road (G. Austin, N. Silkret).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/03 - A3 Georgia on my mind (S. Gorrell, H. Carmichael).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/04 - A4 Camptown races (S.Foster).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/05 - B1 Camptown races (S.Foster).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/06 - B2 Short'nin bread.flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/07 - B3 Basin street blues (S.Williams).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/08 - B4 Ol' man river (O.Hammerstein II, J. Kern).flac: rating=6
Dave Brubeck/Gone with the Wind - 1959/09 - B5 Gone with the wind (H. Magidson, A. Wrubel).flac: rating=6
```

A player like cantata supports this and hence allows the user to rate the songs on a scale of 1 to 5. When a user rates a song on a scale of 1 to 5, it doubles the value and submits it to mpd using the mpd sticker uri set command.
e.g. this is how it looks in cantata. 

![image](https://user-images.githubusercontent.com/8198189/74118839-1a5a3400-4be3-11ea-8843-e45d4ff1dcf6.png)

I believe there is no existing client, apart from Cantata that supports the mpd sticker command. But cantata can be used only on Linux/MacOS computers. Along with rating, last_played, date_added fields, one can generate automated playlist, discover favourite music that one has not listened to before. It can be a good feature in my opinion. In fact, when I listen to a good song, I have to switch on my linux laptop, run cantata to rate the song. I wish it could be done from rompr itself. Can we have support for mpd sticker in rompr? IMHO it can be done in the following 2 ways

1. Check if sticker is enabled in mpd by sending the sticker command for a single URI. mpd will return error if sticker is not supported. If supported, rompr can pull the sticker value for the entire playlist when the user adds songs or directory to mpd playlist. When a user rates a song, rompr can issue the mpc sticker <uri> set <value>

2. Have a import / export option. I have figured out a way to export ratings from rompr to mpd, but import is looking very difficult because I have very limited knowledge on framing complicated SQL queries.

```
I can add a DEFAULT_CURRENT_TIMESTAMP column to Ratingtable or Tracktable, run a shell script in cron and keep getting songs rated by the user recently and update the same in mpd's sqlite sticker database. This is the query that I'm using currently. But this is a sub optimal approach

mysql> select r.Rating, t.Uri from Ratingtable r, Tracktable t where r.TTindex = t.TTindex;
+--------+-------------------------------------------------------------------------------------------------------------------+
| Rating | Uri                                                                                                               |
+--------+-------------------------------------------------------------------------------------------------------------------+
|      4 | Harry Belafonte/Harry Belafonte - Discography Part 1/1956 Island in the sun cd 3/10 Banana Boat Song (Day-O) .mp3 |
|      3 | Harry Belafonte/Harry Belafonte - Discography Part 1/1956 Island in the sun cd 3/11Star-O .mp3                    |
|      3 | Harry Belafonte/Harry Belafonte - Discography Part 1/1956 Island in the sun cd 3/12 Suzanne .mp3                  |
+--------+-------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.02 sec)

```

**Comment by fatg3erman** [comment]
You're not the first person to ask for this, but I'm not keen on the idea for several reasons.

1) There's a good reason why no other clients support the mpd sticker command - it's not very good. There is no defined schema for the mpd sticker database. It's up to individual clients to choose their own schemes, so while I could make something that works with Cantata, it potentially won't work with other clients. And as everything is indexed by URI, lookups are very slow and inefficient.

2) I mainly work to support mopidy, which does not support the sticker database. This then leaves me with 2 separate code paths to maintain. I don't really want to do that.

3) Importing them - using ether of the methods you suggest - would be *incredibly* slow. Doing it for the entire playlist is impractical with large playlists, it causes browser timeouts and http server failures. I could do an import when creating the music collection, but brief tests I did a while ago showed that it makes that process take more than 10 times as long. People are using Rompr with > 100000 tracks in their collection, so a 10x slowdown is unacceptable.

4) How do I map a rating of 1 - 10 onto rompr's scale of 0 - 5?

5) Rompr already supports rating and creating automated playlists so this provides no new functionality to Rompr.

6) What if a track is rated in Rompr and in the sticker database and the values are different? Which one do I use?

7) Rompr does not generally index anything using the URI for performance reasons, and because when running with Mopidy and Spotify URIs are not unique. So this would be a complete change to the core of how Rompr works and would break Spotify support.

**Comment by mbhangui** [comment]
> You're not the first person to ask for this, but I'm not keen on the idea for several reasons.
> 
> 1. There's a good reason why no other clients support the mpd sticker command - it's not very good. There is no defined schema for the mpd sticker database. It's up to individual clients to choose their own schemes, so while I could make something that works with Cantata, it potentially won't work with other clients. And as everything is indexed by URI, lookups are very slow and inefficient.
> 2. I mainly work to support mopidy, which does not support the sticker database. This then leaves me with 2 separate code paths to maintain. I don't really want to do that.
OK

> 3. Importing them - using ether of the methods you suggest - would be _incredibly_ slow. Doing it for the entire playlist is impractical with large playlists, it causes browser timeouts and http server failures. I could do an import when creating the music collection, but brief tests I did a while ago showed that it makes that process take more than 10 times as long. People are using Rompr with > 100000 tracks in their collection, so a 10x slowdown is unacceptable.

How do I do a one time import outside rompr. The problem I'm having is that both Ratingtable and Tracktable are empty after first time setup. I have around 40K tracks. If somehow I populate these two tables with dummy ratings, able to able to write my own shell script that updates the rating with the value I have from the sticker db after multiplying the rating value in sticker by 0.5. I turned on the logging of the sql statements in mysql and this is what rompr does when I update the rating in the rompr interface

```
Connect   rompr@localhost on romprdb using Socket
Query     SET NAMES utf8
Query     SET SESSION sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'CollType'
Query     START TRANSACTION
Query     UPDATE Tracktable SET justAdded = 0 WHERE justAdded = 1
Query     UPDATE Albumtable SET justUpdated = 0 WHERE justUpdated = 1
Query     SELECT
                TTindex
        FROM
                Tracktable JOIN Albumtable USING (Albumindex)
                JOIN Artisttable ON Albumtable.AlbumArtistindex = Artisttable.Artistindex
        WHERE
                LOWER(Title) = LOWER('B1 Camptown races  (S.Foster)')
                AND LOWER(Artistname) = LOWER('Dave Brubeck Quartet')
                AND LOWER(Albumname) = LOWER('Gone with the Wind')
                AND TrackNo = '5'
Query     SELECT
                TTindex
        FROM
                Tracktable JOIN Albumtable USING (Albumindex)
                JOIN Artisttable ON Albumtable.AlbumArtistindex = Artisttable.Artistindex
        WHERE
                LOWER(Title) = LOWER('B1 Camptown races  (S.Foster)')
                AND LOWER(Artistname) = LOWER('Dave Brubeck Quartet')
                AND LOWER(Albumname) = LOWER('Gone with the Wind')
Query     SELECT
                TTindex
        FROM
                Tracktable JOIN Artisttable USING (Artistindex)
                JOIN Albumtable USING (Albumindex)
        WHERE
                LOWER(Title) = LOWER('B1 Camptown races  (S.Foster)')
                AND LOWER(Artistname) = LOWER('Dave Brubeck Quartet')
            AND LOWER(Albumname) = LOWER('Gone with the Wind')
Query     SELECT
                TTindex
        FROM
                Tracktable JOIN Artisttable USING (Artistindex)
        WHERE
                LOWER(Title) = LOWER('B1 Camptown races  (S.Foster)')
                AND LOWER(Artistname) = LOWER('Dave Brubeck Quartet')
                AND Uri IS NULL
Query     SELECT Artistindex FROM Artisttable WHERE LOWER(Artistname) = LOWER('Dave Brubeck Quartet')
Query     SELECT
                Albumindex,
                Year,
                Image,
                AlbumUri,
                mbid
        FROM
                Albumtable
        WHERE
                LOWER(Albumname) = LOWER('Gone with the Wind')
                AND AlbumArtistindex = '5'
                AND Domain = 'local'
Query     INSERT INTO
                Tracktable
                (Title, Albumindex, Trackno, Duration, Artistindex, Disc, Uri, LastModified, Hidden, isSearchResult, Sourceindex, isAudiobook)
                VALUES
                ('B1 Camptown races  (S.Foster)', '4', '5', '140', '5', '1', 'Dave Brubeck/Gone with the Wind - 1959/05 - B1 Camptown races (S.Foster).flac', NULL, '0', '0', NULL, '0')
Query     REPLACE INTO Ratingtable (TTindex, Rating) VALUES ('10', '3')
Query     SELECT
                IFNULL(r.Rating, 0) AS Rating,
                IFNULL(p.Playcount, 0) AS Playcount,
                UNIX_TIMESTAMP(p.LastPlayed) AS LastTime,
                UNIX_TIMESTAMP(tr.DateAdded) AS DateAdded,
                IFNULL(GROUP_CONCAT(t.Name SEPARATOR ', ') , '') AS Tags,
                tr.isSearchResult,
                tr.Hidden
        FROM
                Tracktable AS tr
                LEFT JOIN Ratingtable AS r ON tr.TTindex = r.TTindex
                LEFT JOIN Playcounttable AS p ON tr.TTindex = p.TTindex
                LEFT JOIN TagListtable AS tl ON tr.TTindex = tl.TTindex
                LEFT JOIN Tagtable AS t USING (Tagindex)
        WHERE tr.TTindex = 10
        GROUP BY tr.TTindex
        ORDER BY t.Name
Query     SELECT DISTINCT AlbumArtistindex FROM Albumtable WHERE justUpdated = 1
Query     SELECT Albumindex, AlbumArtistindex FROM Albumtable WHERE justUpdated = 1
Query     SELECT Albumindex, AlbumArtistindex, Uri, TTindex FROM Tracktable JOIN Albumtable USING (Albumindex) WHERE justAdded = 1 AND Hidden = 0
Query     COMMIT
Quit
Connect   rompr@localhost on romprdb using Socket
Query     SET NAMES utf8
Query     SET SESSION sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'CollType'
Quit
Connect   rompr@localhost on romprdb using Socket
Query     SET NAMES utf8
Query     SET SESSION sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'CollType'
Query     START TRANSACTION
Query     UPDATE Tracktable SET justAdded = 0 WHERE justAdded = 1
Query     UPDATE Albumtable SET justUpdated = 0 WHERE justUpdated = 1
Query     DELETE FROM Albumtable WHERE Albumindex NOT IN (SELECT DISTINCT Albumindex FROM Tracktable)
Query     DROP TABLE IF EXISTS Croft
Query     DROP TABLE IF EXISTS Cruft
Query     CREATE TEMPORARY TABLE Croft(Artistindex INT UNSIGNED NOT NULL UNIQUE, PRIMARY KEY(Artistindex)) AS SELECT Artistindex FROM Tracktable UNION SELECT AlbumArtistindex FROM Albumtable
Query     CREATE TEMPORARY TABLE Cruft(Artistindex INT UNSIGNED NOT NULL UNIQUE, PRIMARY KEY(Artistindex)) AS SELECT Artistindex FROM Artisttable WHERE Artistindex NOT IN (SELECT Artistindex FROM Croft)
Query     DELETE Artisttable FROM Artisttable INNER JOIN Cruft ON Artisttable.Artistindex = Cruft.Artistindex
Query     DELETE FROM Ratingtable WHERE Rating = '0'
Query     DELETE FROM Ratingtable WHERE TTindex NOT IN (SELECT TTindex FROM Tracktable WHERE Hidden = 0)
Query     DELETE FROM TagListtable WHERE TTindex NOT IN (SELECT TTindex FROM Tracktable WHERE Hidden = 0)
Query     CREATE TEMPORARY TABLE used_tags AS SELECT DISTINCT Tagindex FROM TagListtable
used_tags)
Query     DELETE FROM Playcounttable WHERE Playcount = '0'
Query     DELETE FROM Playcounttable WHERE TTindex NOT IN (SELECT TTindex FROM Tracktable)
Query     SELECT COUNT(*) AS NumArtists FROM (SELECT AlbumArtistindex FROM Albumtable
                INNER JOIN Tracktable USING (Albumindex) WHERE Uri IS NOT NULL
                AND Hidden = 0 AND isSearchResult < 2 AND isAudiobook = 0  GROUP BY AlbumArtistindex) AS t
Query     UPDATE Statstable SET Value='2' WHERE Item='ArtistCount'
Query     SELECT COUNT(*) AS NumAlbums FROM (SELECT Albumindex FROM Tracktable WHERE Uri IS NOT NULL
                AND Hidden = 0 AND isSearchResult < 2 AND isAudiobook = 0  GROUP BY Albumindex) AS t
Query     UPDATE Statstable SET Value='2' WHERE Item='AlbumCount'
Query     SELECT COUNT(*) AS NumTracks FROM Tracktable WHERE Uri IS NOT NULL AND Hidden=0 AND isAudiobook = 0  AND isSearchResult < 2
Query     UPDATE Statstable SET Value='7' WHERE Item='TrackCount'
Query     SELECT SUM(Duration) AS TotalTime FROM Tracktable WHERE Uri IS NOT NULL AND Hidden=0 AND isAudiobook = 0  AND isSearchResult < 2
Query     UPDATE Statstable SET Value='1588' WHERE Item='TotalTime'
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'ArtistCount'
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'AlbumCount'
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'TrackCount'
Query     SELECT Value AS TheThingToFind FROM Statstable WHERE Item = 'TotalTime'
Query     COMMIT
```
> 4. How do I map a rating of 1 - 10 onto rompr's scale of 0 - 5?

Multipy by 0.5

> 5. Rompr already supports rating and creating automated playlists so this provides no new functionality to Rompr.
> 6. What if a track is rated in Rompr and in the sticker database and the values are different? Which one do I use?
> 7. Rompr does not generally index anything using the URI for performance reasons, and because when running with Mopidy and Spotify URIs are not unique. So this would be a complete change to the core of how Rompr works and would break Spotify support.

That is fine. All I am saying is that I have ratings for my songs in a database which is not in rompr. The ratings have been built over a decade and it is not practically possible to rate around 40K songs using rompr. To make it simple, let me say that I have a mysql able which two columns - uri and rating. Then can we have a SQL query which will build the Ratingtable and Tracktable? This script can just be part of extra folder in the github repo and not part of the rompr code. I will myself write a HOWTO on how to import the ratings from clementine or strawberry music player. Both are quite popular on linux distributions.

**Comment by fatg3erman** [comment]
> Connect   rompr@localhost on romprdb using Socket

I'm not sure why you're telling me how my own code works.

> > 1. How do I map a rating of 1 - 10 onto rompr's scale of 0 - 5?
> 
> Multipy by 0.5

So 7 becomes 3.5. That doesn't work.

> That is fine. All I am saying is that I have ratings for my songs in a database which is not in rompr. The ratings have been built over a decade and it is not practically possible to rate around 40K songs using rompr. To make it simple, let me say that I have a mysql able with two columns - uri and rating. Can we have a SQL query which will build the Ratingtable and Tracktable? This script can just be part of an extra folder in the github repo and not part of the rompr code. I will myself write a HOWTO on how to import the ratings from clementine or strawberry music player. Both are quite popular on linux distributions.

You cannot create the Tracktable using only URIs. The only way to do this would be to first create your Music Collection in Rompr - this would create the tracktable. 

Then, for every track in your Collection you would have to query MPD to see if it had a rating, and then set that rating in Rompr's database. A quick calculation tells me that on a moderate PC with your 40,000 tracks it would take about 7 hours. Like I say, MPD's sticker database is sloooooow.

Another way to accomplish it would be to create a 'fake' ratings backup from your MPD data. This is in JSON format, you can work out the format by rating a few tracks in rompr and creating a metadata backup then examining the file. You could then restore that - but note that doesn't use URIs either. Like I say, URIs are not useful to me, but this approach is one that might work if you can get artist, album, title, and trac knumber (I think) for every rated track in mpd.

Another approach would be to see if it's possible to read the sticker database directly, as a database, then you would only need to query MPD for the tracks that are in that database, which would speed things up somewhat. But as there's no defined schema for that database, there's no guarantee this would work in future.

And on no account should you attempt to write a script that writes to Rompr's database without using rompr's API. There is a very specific sequence of actions that has to happen, and it is version-dependant, so you would risk creating a script that would break your database in future versions.

I'll try to help if I can - I think the fake ratings backup approach would be the best. It allows you to create a simple file that you can use Rompr to import, and it would be the quickest method by far.

**Comment by mbhangui** [comment]
> 
> I'm not sure why you're telling me how my own code works.
> 
I realize now how that sounded. Sorry about that. That wasn't the intention. What I was trying to convey was that i couldn't figure out how to write a query to do the import. It seems that I will have to write a query involving complex joins. 

rompr is awesome. I'm just trying to make the ratings work for me and I want to generate playlists automatically using a playlist generation script that I have written for mpd. Ultimately I will modify this script to pull the details from rompr instead of the sqlite stats db used by mpdcron. mpdcron is an interesting project. It has a program mpdcron which listens to mpd events and can execute any script when an event happens (play, stop, pause, new playlist,etc). 

This is the script which I will modify and have an option --use-rompr to generate playlists based on personal listening habits.

https://github.com/mbhangui/mpdwatch/blob/master/src/mpdplaylist

> > > 1. How do I map a rating of 1 - 10 onto rompr's scale of 0 - 5?
> > 
> > 
> > Multipy by 0.5
> 
> So 7 becomes 3.5. That doesn't work.
> 

I will round it off to the next highest number. It will be better than having nothing.

> 
> You cannot create the Tracktable using only URIs. The only way to do this would be to first create your Music Collection in Rompr - this would create the tracktable.
> 
> Then, for every track in your Collection you would have to query MPD to see if it had a rating, and then set that rating in Rompr's database. A quick calculation tells me that on a moderate PC with your 40,000 tracks it would take about 7 hours. Like I say, MPD's sticker database is sloooooow.
> 

I have done quite a few import from the sticker db, populating another sqlite db (something similar to rompr's Tracktable. On my laptop it takes less than 10 mins to update the large table in sqlite. I guess updating a similar table in MySQL will be faster. Even if it takes very long, it will be worth it once I have the rating populated in rompr. What I want to achieve is use only rompr, be it by android phone, my development linux laptop or my macbook. Currently I have to use cantata to update ratings whenever I add new songs.

> Another way to accomplish it would be to create a 'fake' ratings backup from your MPD data. This is in JSON format, you can work out the format by rating a few tracks in rompr and creating a metadata backup then examining the file. You could then restore that - but note that doesn't use URIs either. Like I say, URIs are not useful to me, but this approach is one that might work if you can get artist, album, title, and trac knumber (I think) for every rated track in mpd.
> 
> Another approach would be to see if it's possible to read the sticker database directly, as a database, then you would only need to query MPD for the tracks that are in that database, which would speed things up somewhat. But as there's no defined schema for that database, there's no guarantee this would work in future.
> 
> And on no account should you attempt to write a script that writes to Rompr's database without using rompr's API. There is a very specific sequence of actions that has to happen, and it is version-dependant, so you would risk creating a script that would break your database in future versions.
> 
> I'll try to help if I can - I think the fake ratings backup approach would be the best. It allows you to create a simple file that you can use Rompr to import, and it would be the quickest method by far.

Thank you. That would be awesome. The fake rating approach will work for me best. Once I have the Tracktable, Ratingtable populated, I can write  a shell script to update the ratings with the value from either Clementine.db or sticker db. I will write a HOWTO on how to move from Clemetine to rompr and provide the shell script that updates the rating field in Ratingtable from Clementine.db sqlite table.Thank you for your time and being patient :)

**Comment by fatg3erman** [comment]
> I have done quite a few import from the sticker db, populating another sqlite db (something similar to rompr's Tracktable. On my laptop it takes less than 10 mins to update the large table in sqlite. I guess updating a similar table in MySQL will be faster. Even if it takes very long, it will be worth it once I have the rating populated in rompr. What I want to achieve is use only rompr, be it my android phone, my development linux laptop or my macbook. Currently I have to use cantata to update ratings whenever I add new songs.

What I was saying is that, once you have the Tracktable, you have to query MPD for *every single track* in your Tracktable. That's 40,000 MPD queries. It takes a very long time.

However I've just thought of another way. This is not as 'nice', since it's not very portable and does write directly to rompr's database, but it would work and it would be much faster than any of the other methods.

Provided you can read the sticker db and get a table of URIs and Ratings then, first you need to build your Music Collection in Rompr. Then you need a script that runs through the list of URIs/Ratings and for each one does

    SELECT TTindex FROM Tracktable WHERE Uri = [Your Uri]
    INSERT INTO Ratingtable (TTindex, Rating) VALUES ([TTindex from above], [Rating]) ON DUPLICATE KEY UPDATE Rating = [Rating]

That would work, and it would be quick. It might break if the structure of those tables ever changes, but that's unlikely. The downside of this approach is that it relies on URIs, whereas the ratings backup approach will work even if all your URIs change.

>Many users like me are discovering that small SBC like the raspberry pi handle jitter better than laptops and desktops which have SMPS (source of noise).

I use a Raspberry Pi myself, with nginx. But I disagree on the noise, the Pi creates dreadful electrical noise on the USB ports whenever there is any activity on the HDMI or Ethernet ports, or on another USB port. It's amongst the worst I've ever seen (I work for an audio company). The HATs are very good though - I use a Pi DAC Pro and it's pretty quiet, but there's still a background hum from it.

**Comment by mbhangui** [comment]
> ```
> SELECT TTindex FROM Tracktable WHERE Uri = [Your Uri]
> INSERT INTO Ratingtable (TTindex, Rating) VALUES ([TTindex from above], [Rating]) ON DUPLICATE KEY UPDATE Rating = [Rating]
> ```
> 
> That would work, and it would be quick. It might break if the structure of those tables ever changes, but that's unlikely. The downside of this approach is that it relies on URIs, whereas the ratings backup approach will work even if all your URIs change.
>

This worked like a charm. It took 92 minutes to set the ratings for 40k songs. Thank you so much
 
> I use a Raspberry Pi myself, with nginx. But I disagree on the noise, the Pi creates dreadful electrical noise on the USB ports whenever there is any activity on the HDMI or Ethernet ports, or on another USB port. It's amongst the worst I've ever seen (I work for an audio company). The HATs are very good though - I use a Pi DAC Pro and it's pretty quiet, but there's still a background hum from it.

I too use a hats made by allo using a SBC known as sparky. It uses two hat boards. One board called kali which supplies accurate clock and one board having 4 dac chips (two for left+right and two for subwoofer left+right).

https://allo.com/sparky/sparky-sbc.html

**Comment by fatg3erman** [comment]
Importer added to version 1.42
