### ISSUE TITLE
error in ngnix log 

### ISSUE THREAD

**Issue by tkgafs** [fatg3erman/RompR#88]
When I start rompr i have noticed this error in the nginx error log

2020/03/08 12:17:03 [error] 859#859: *67831 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: outputenabled in /var/www/rompr/player/mpd/outputs.php on line 26PHP message: PHP Notice:  Undefined index: outputname in /var/www/rompr/player/mpd/outputs.php on line 30" while reading upstream, client: 192.168.49.70, server: zotac.localdomain, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "zotac.localdomain"

It only seems to happen on starting the web interface, and doesnt seem to have any effect as everything plays ok

in MPD I only have this output defined

audio_output {
        type            "alsa"
        name            "My ALSA Device"
        device          "hw:0,0"        # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "default"       # optional
#       mixer_control   "PCM"           # optional
#       mixer_index     "0"             # optional
}
 
Debug Info from the plugin you pointed out !!

* **BACKEND INFO**
  * **Version** 1.41
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host** 
  * **proxy_password** 
  * **proxy_user** 
  * **spotify_token** 
  * **spotify_token_expires** 
* **SERVER INFO**
  * **PHP_SELF** /utils/debuginfo.php
  * **SERVER_ADDR** 192.168.49.20
  * **SERVER_NAME** zotac.localdomain
  * **SERVER_SOFTWARE** nginx/1.16.1
  * **DOCUMENT_ROOT** /var/www/rompr
  * **HTTP_HOST** zotac.localdomain
  * **HTTP_USER_AGENT** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:73.0) Gecko/20100101 Firefox/73.0
  * **REMOTE_ADDR** 192.168.49.70
  * **SERVER_PORT** 80
  * **REQUEST_URI** /utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **skin** desktop
  * **player_backend** mpd
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **sortbydate** true
  * **sortcollectionby** albumbyartist
* **PHP INFO**
  * **Version** 7.3.11-0ubuntu0.19.10.3
  * **mbstring** 7.3.11-0ubuntu0.19.10.3
  * **PDO** 7.3.11-0ubuntu0.19.10.3
  * **pdo_mysql** 
  * **pdo_sqlite** 7.3.11-0ubuntu0.19.10.3
  * **curl** 7.3.11-0ubuntu0.19.10.3
  * **date** 7.3.11-0ubuntu0.19.10.3
  * **fileinfo** 7.3.11-0ubuntu0.19.10.3
  * **json** 1.7.0
  * **SimpleXML** 7.3.11-0ubuntu0.19.10.3
  * **GD** 7.3.11-0ubuntu0.19.10.3
  * **GD Info** GD Version=2.2.5, FreeType Support=1, FreeType Linkage=with freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1, BMP Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=/var/log/php_errors.log, local_value=/var/log/php_errors.log, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=1800, local_value=1800, access=7
  * **mbstring.language** global_value=neutral, local_value=neutral, access=7
  * **memory_limit** global_value=128M, local_value=128M, access=7
  * **pdo_mysql.default_socket** [NOT SET]
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir** global_value=, local_value=, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **tagtype** Artist, Album, AlbumArtist, Title, Track, Name, Genre, Date, Composer, Performer, Disc
  * **Commands** add, addid, addtagid, albumart, channels, clear, clearerror, cleartagid, close, commands, config, consume, count, crossfade, currentsong, decoders, delete, deleteid, disableoutput, enableoutput, find, findadd, idle, kill, list, listall, listallinfo, listfiles, listmounts, listpartitions, listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb, mixrampdelay, mount, move, moveid, newpartition, next, notcommands, outputs, outputset, partition, password, pause, ping, play, playid, playlist, playlistadd, playlistclear, playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove, playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random, rangeid, readcomments, readmessages, rename, repeat, replay_gain_mode, replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek, seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, sticker, stop, subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe, update, urlhandlers, volume
  * **URL Handlers** alsa://
  * **URL Handlers** http://
  * **URL Handlers** https://
  * **URL Handlers** gopher://
  * **URL Handlers** rtp://
  * **URL Handlers** rtsp://
  * **URL Handlers** rtmp://
  * **URL Handlers** rtmpt://
  * **URL Handlers** rtmps://
  * **URL Handlers** smb://
  * **URL Handlers** nfs://
  * **URL Handlers** mms://
  * **URL Handlers** mmsh://
  * **URL Handlers** mmst://
  * **URL Handlers** mmsu://
  * **URL Handlers** cdda://
  * **plugin** mad, mpg123, vorbis, oggflac, flac, opus, sndfile, audiofile, dsdiff, dsf, faad, mpcdec, wavpack, modplug, mikmod, sidplay, fluidsynth, adplug, ffmpeg, gme, pcm
  * **suffix** mp3, mp2, mp3, ogg, oga, ogg, oga, flac, opus, ogg, oga, wav, aiff, aif, au, snd, paf, iff, svx, sf, voc, w64, pvf, xi, htk, caf, sd2, wav, au, aiff, aif, dff, dsf, aac, mpc, wv, 669, amf, ams, dbm, dfm, dsm, far, it, med, mdl, mod, mtm, mt2, okt, s3m, stm, ult, umx, xm, amf, dsm, far, gdm, imf, it, med, mod, mtm, s3m, stm, stx, ult, uni, xm, sid, mus, str, prg, P00, mid, amd, d00, hsc, laa, rad, raw, sa2, 16sv, 3g2, 3gp, 4xm, 8svx, aa3, aac, ac3, adx, afc, aif, aifc, aiff, al, alaw, amr, anim, apc, ape, asf, atrac, au, aud, avi, avm2, avs, bap, bfi, c93, cak, cin, cmv, cpk, daud, dct, divx, dts, dv, dvd, dxa, eac3, film, flac, flc, fli, fll, flx, flv, g726, gsm, gxf, iss, m1v, m2v, m2t, m2ts, m4a, m4b, m4v, mad, mj2, mjpeg, mjpg, mka, mkv, mlp, mm, mmf, mov, mp+, mp1, mp2, mp3, mp4, mpc, mpeg, mpg, mpga, mpp, mpu, mve, mvi, mxf, nc, nsv, nut, nuv, oga, ogm, ogv, ogx, oma, ogg, omg, opus, psp, pva, qcp, qt, r3d, ra, ram, rl2, rm, rmvb, roq, rpl, rvc, shn, smk, snd, sol, son, spx, str, swf, tak, tgi, tgq, tgv, thp, ts, tsp, tta, xa, xvid, uv, uv2, vb, vid, vob, voc, vp6, vmd, wav, webm, wma, wmv, wsaud, wsvga, wv, wve, ay, gbs, gym, hes, kss, nsf, nsfe, sap, spc, vgm, vgz
  * **mime_type** audio/mpeg, application/ogg, application/x-ogg, audio/ogg, audio/vorbis, audio/vorbis+ogg, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, application/ogg, application/x-ogg, audio/ogg, audio/x-flac+ogg, audio/x-ogg, application/flac, application/x-flac, audio/flac, audio/x-flac, audio/ogg, application/ogg, audio/opus, audio/x-wav, audio/x-aiff, audio/x-wav, audio/x-aiff, application/x-dff, audio/x-dff, audio/x-dsd, application/x-dsf, audio/x-dsf, audio/x-dsd, audio/aac, audio/aacp, audio/x-wavpack, application/flv, application/m4a, application/mp4, application/octet-stream, application/ogg, application/x-ms-wmz, application/x-ms-wmd, application/x-ogg, application/x-shockwave-flash, application/x-shorten, audio/8svx, audio/16sv, audio/aac, audio/aacp, audio/ac3, audio/aiffaudio/amr, audio/basic, audio/flac, audio/m4a, audio/mp4, audio/mpeg, audio/musepack, audio/ogg, audio/opus, audio/qcelp, audio/vorbis, audio/vorbis+ogg, audio/x-8svx, audio/x-16sv, audio/x-aac, audio/x-ac3, audio/x-adx, audio/x-aiffaudio/x-alaw, audio/x-au, audio/x-dca, audio/x-eac3, audio/x-flac, audio/x-gsm, audio/x-mace, audio/x-matroska, audio/x-monkeys-audio, audio/x-mpeg, audio/x-ms-wma, audio/x-ms-wax, audio/x-musepack, audio/x-ogg, audio/x-vorbis, audio/x-vorbis+ogg, audio/x-pn-realaudio, audio/x-pn-multirate-realaudio, audio/x-speex, audio/x-ttaaudio/x-voc, audio/x-wav, audio/x-wma, audio/x-wv, video/anim, video/quicktime, video/msvideo, video/ogg, video/theora, video/webm, video/x-dv, video/x-flv, video/x-matroska, video/x-mjpeg, video/x-mpeg, video/x-ms-asf, video/x-msvideo, video/x-ms-wmv, video/x-ms-wvx, video/x-ms-wm, video/x-ms-wmx, video/x-nut, video/x-pva, video/x-theora, video/x-vid, video/x-wmv, video/x-xvid, audio/x-mpd-ffmpeg, audio/L16, audio/L24, audio/x-mpd-float, audio/x-mpd-cdda-pcm, audio/x-mpd-cdda-pcm-reverse
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **music_directory_albumart** /Q_Zotac/Music/Include
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media, 2=SoundCloud/Liked
  * **lastfm_country_code** GB
  * **country_userset** true
  * **debug_enabled** 1
  * **custom_logfile** /var/log/rompr.log
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location** 
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=, mopidy_slave=false, radioparams=[radiomode=, radioparam=null, radiomaster=1581857189153, radioconsume=[["consume","1"],["repeat","0"],["random","0"]]]]
  * **dev_mode** false
  * **live_mode** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1583783839778
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory** 
  * **collection_player** mpd
  * **snapcast_server** 
  * **snapcast_port** 1705
  * **displaycomposer** true
  * **artistsatstart** 0=
  * **nosortprefixes** 0=The
  * **sortcollectionby** albumbyartist
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **google_api_key** 
  * **google_search_engine_id** 
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **last_lastfm_synctime** 1583179029000
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 0
  * **sortbydate** true
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mpd
  * **collectionrange** 0
  * **lastfm_user** 
  * **lastfm_session_key** 
  * **autotagname** 
  * **tradsearch** true
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** false
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** file
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** false
  * **clickmode** double
  * **chooser** pluginplaylistslist
  * **hide_albumlist** false
  * **hide_filelist** true
  * **hide_radiolist** false
  * **hide_podcastslist** true
  * **hide_playlistslist** true
  * **hide_audiobooklist** true
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.41
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **user_lang** en
  * **synctags** false
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Modern-Dark
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains** 0=local, 1=spotify
  * **mopidy_radio_domains** 0=local
  * **outputsvisible** true
  * **wheelscrollspeed** 150
  * **searchcollectiononly** true
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** true
  * **communityradioorderby** name
  * **browser_id** 1581857189153
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **bgimgparms** dummy=baby
  * **alarms** 
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1583179039091
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** false
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1583655459548
  * **next_podcast_refresh** 1585298254707
  * **use_original_releasedate** false
  * **collection_type** sqlite
  * **collectioncontrolsvisible** true
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password** 
  * **unix_socket** 
  * **separate_collections** false
  * **skin** desktop
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode** starRadios
  * **radioparam** custom+1970s
  * **radiomaster** 1581857189153
  * **radioconsume** [["consume","1"],["repeat","0"],["random","0"]]

**Comment by fatg3erman** [comment]
Hmmmm. Very strange.

Can you enable debug loggin at Level 7 and send me the full web server error log when you load the page. It looks like MPD is sending something odd when I ask it what audio outputs it has. Can't reproduce it here.

**Comment by tkgafs** [comment]
As requested

[error.log.txt](https://github.com/fatg3erman/RompR/files/4303371/error.log.txt)

**Comment by fatg3erman** [comment]
Thanks. Your MPD is sending something called 'attribute' with its audio outputs info. I've not seen this before and am not interested in it but as it appears more than once per output it's screwing up my parsing of the result. Latest commit ought to fix it but I can't actually test if it does because my MPD isn't doing it. I really ought to add MPD Version into that debug info....

**Comment by tkgafs** [comment]
Ok I'll test latest version later on tonight

for your info I'm running the following on 64bit Ubuntu 19.10

apt list --installed | egrep "mpc|mpd"

libmpc3/eoan,now 1.1.0-1 amd64 [installed,automatic]
libmpcdec6/eoan,now 2:0.1~r495-1build1 amd64 [installed,automatic]
libmpdclient2/eoan,now 2.16-1 amd64 [installed,automatic]
libmpdec2/eoan,now 2.4.2-2 amd64 [installed,automatic]
mpc/eoan,now 0.32-1 amd64 [installed]
mpd/eoan,now 0.21.13-1build1 amd64 [installed]

**Comment by tkgafs** [comment]
I can confirm that the error no longer appears in the nginx log

Only thing I've noticed, is that there no longer is a small panel next to the volume control containing details of the outputs, presumably to choose the outputs you want to use, but as I only have 1 defined in MPD perhaps I should have never have seen it before

**Comment by fatg3erman** [comment]
So when there is more than one output you get that extra panel which allows you to enable/disable outputs. The bug you found made me think you had 2 outputs when you only have one.

When there's only one output, the button under the volume control just behaves as a Mute button.
