### ISSUE TITLE
error: fputs() expects parameter 1 to be resource

### ISSUE THREAD

**Issue by skulko** [fatg3erman/RompR#89]
Hi 
my mpd/rompr is often crashing after playing a couple song, at the end / before playing the next song. I can't really figure out whats wrong.. I disabled second output to snapcast server but did not help.  
to get it going again I have to  kill -KILL mpd process 

I see multiple entries in log:

`2020/03/10 16:03:15 [error] 4791#4791: *781 FastCGI sent in stderr: "PHP message: PHP Warning:  fputs() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  stream_socket_shutdown() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 168PHP message: PHP Warning:  fputs() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  stream_socket_shutdown() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 168PHP message: PHP Warning:  fputs() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  stream_socket_shutdown() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 168" while reading response header from upstream, client: 192.168.0.10, server: mpd_server, request: "GET /rompr/getplaylist.php?_=1582988426118 HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.socket:", host: "mpd_server", referrer: "http://mpd_server/rompr/"
2020/03/1016:08:35 [error] 4791#4791: *735 FastCGI sent in stderr: "PHP message: PHP Notice:  fputs(): send of 18 bytes failed with errno=32 Broken pipe in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 102PHP message: PHP Notice:  fputs(): send of 7 bytes failed with errno=32 Broken pipe in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  fputs() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  stream_socket_shutdown() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 168PHP message: PHP Warning:  fputs() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 165PHP message: PHP Warning:  stream_socket_shutdown() expects parameter 1 to be resource, bool given in /var/www/default/htdocs/rompr/player/mpd/mpdinterface.php on line 168" while reading response header from upstream, client: 192.168.0.10, server: mpd_server, request: "GET /rompr/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.socket:", host: "mpd_server"`

**Comment by fatg3erman** [comment]
That error from Rompr simply indicates that MPD has stopped responding, so it looks like MPD has crashed. The fact you have to restart MPD also supports that. This doesn't look like a rompr issue to me.
