### ISSUE TITLE
FR: Custom Default Cover

### ISSUE THREAD

**Issue by gerroon** [fatg3erman/RompR#9]
Hi

At the moment, if an album is missing a cover, it still shows the cover of the last song that had a real cover, which is very very confusing,   at least that is how it looks  to me. 

It would be so nice if one can define a custom cover for missing covers. 

Thanks

**Comment by fatg3erman** [comment]
The first part of this is definitely a bug.

The second part is not something that is ever going to happen :)

**Comment by gerroon** [comment]
Okk well, I ll be happy at least if I cna get the first part going. Let me know if you need testing of that.

**Comment by gerroon** [comment]
See the screenshot please. As you see the cover is not the artist or the album.

https://filebin.net/hcacrru3ncvijvfa/Selection_018.png?t=mq1ccsf7

**Comment by fatg3erman** [comment]
I could give you a custom default cover for the 'now playing' area, but not for the Music Collection or playlist. The fix for this issue kind of involves using a special image for the now playing area anyway..

**Comment by gerroon** [comment]
@fatg3erman 

Yeah if you could give me a custom one for the missing cover for the currently playing, that should do it. 

It is confusing to see a previous album cover with the current song. This gets a bit more tedious when one playing radio stations from .m3u, given that no radio station serves covers.

**Comment by fatg3erman** [comment]
| It is confusing to see a previous album cover with the current song.

it is. That's definitely a bug, I think I have a fix for that.

**Comment by gerroon** [comment]
Cool, glad to hear that.
