### ISSUE TITLE
Feature request:  Music Collection by Genre

### ISSUE THREAD

**Issue by uriel1998** [fatg3erman/RompR#90]
I know "multi-genre" is a PITA with the different ways folks encode it, but would it be possible to add a "genre" sorter in the music collection portion?  (See screenshot to be clear of where I mean). 

Rationale:  Sometimes I'm in the mood for a particular genre, but don't know what *album* in that genre I'd like to listen to, so...  yeah.  Currently running 1.40.

![2020-03-27--1585322837_2390x1280_scrot](https://user-images.githubusercontent.com/1130750/77772237-317fa480-701e-11ea-9674-1d5d08bafc2d.png)

**Comment by fatg3erman** [comment]
Genre is going to be in 1.41, but multi-genre is too much of a PITA :)
