### ISSUE TITLE
"Fatal Error - Could not open the preferences file" in WebUI frontend

### ISSUE THREAD

**Issue by AgentX83** [fatg3erman/RompR#91]
After a reboot of my RaspPi over the weekend, I now end up with this when I attempt to browse to my rompr frontend:

"Fatal Error - Could not open the preferences file"

Errors from nginx:

cat error.log
2020/03/30 20:13:09 [error] 2054#2054: *1 FastCGI sent in stderr: "PHP message: ERROR!              : COULD NOT LOAD PREFS" while reading response header from upstream, client: 10.0.0.122, server: www.myrompr.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "10.0.0.2"
2020/03/30 20:14:39 [error] 2054#2054: *4 FastCGI sent in stderr: "PHP message: ERROR!              : COULD NOT LOAD PREFS" while reading response header from upstream, client: 10.0.0.122, server: www.myrompr.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "10.0.0.2"
2020/03/30 20:21:15 [error] 2054#2054: *7 FastCGI sent in stderr: "PHP message: ERROR!              : COULD NOT LOAD PREFS" while reading response header from upstream, client: 10.0.0.122, server: www.myrompr.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "10.0.0.2"
2020/03/30 20:21:24 [error] 2054#2054: *7 FastCGI sent in stderr: "PHP message: ERROR!              : COULD NOT LOAD PREFS" while reading response header from upstream, client: 10.0.0.122, server: www.myrompr.net, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "10.0.0.2"
2020/03/30 20:40:18 [error] 2054#2054: *11 FastCGI sent in stderr: "PHP message: ERROR!              : COULD NOT LOAD PREFS" while reading response header from upstream, client: 10.0.0.122, server: www.myrompr.net, request: "GET /?setup HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "10.0.0.2"

Is something suddenly going on with permissions on my PHP folder?

Any suggestions or guidance would be appreciated. 

-Kasey

**Comment by fatg3erman** [comment]
Hmmm.

It's hard to say exactly why that's happening but that specific message suggests a corrupted prefs file rather than a permissions issue.

If you're running Raspbian, then the ownership of rompr/prefs and all files and subdirectories within it should be the user www-data, so check that first and if it's not right

```
cd rompr
sudo chown -R www-data prefs
sudo chmod -R u+rw prefs

```
would sort out any permissions issues. Other distributions might use a different username, check which user your nginx process is running as.

The prefs file itself is rompr/prefs/prefs.var. It's safe to delete that file, rompr will then use defaults for any prefs that are not saved in your browser - you'll need to re-set most of your preferences again afterwards.

**Comment by AgentX83** [comment]
Well, that got me to a positive end result, so thanks. Just have to re-scan my "Collection". 

I will add that I'm happy to have this tool, but I certainly wish I could streamline the whole interface. I want something that gives me a big button what says "SHUFFLE PLAY MY ENTIRE TRACK LIBRARY. There are far too many buttons and options that I'll never need, never use, never even figure out. I still don't think I know how to just tell it to refresh my "Collection" based on what MPD has in its local scan results. 

BTW, this Pi/server is being used as an unseen "jukebox" for my home video/pinball arcade.

Thanks again,
Kasey

**Comment by fatg3erman** [comment]
> I will add that I'm happy to have this tool, but I certainly wish I could streamline the whole interface. 

![Screen Shot 2020-04-01 at 07 16 27](https://user-images.githubusercontent.com/1430781/78105828-f3053380-73e9-11ea-8b3d-c297f2aad41f.png)

>I want something that gives me a big button what says "SHUFFLE PLAY MY ENTIRE TRACK LIBRARY. 

![Screen Shot 2020-04-01 at 07 16 04](https://user-images.githubusercontent.com/1430781/78105851-09ab8a80-73ea-11ea-9fc9-bd4fa62520dc.png)

> There are far too many buttons and options that I'll never need, never use, never even figure out. 

That's fine. You don't have to use them. There's a lot of functionality. It's not a record player. The instructions are here https://fatg3erman.github.io/RompR/

> I still don't think I know how to just tell it to refresh my "Collection" based on what MPD has in its local scan results.

![Screen Shot 2020-04-01 at 07 16 41](https://user-images.githubusercontent.com/1430781/78105932-35c70b80-73ea-11ea-9d21-68d283bb9b6a.png)
