### ISSUE TITLE
five star tag

### ISSUE THREAD

**Issue by sinclaircornacchia** [fatg3erman/RompR#93]
Hi your app is fantastic.
I got a problem.when i put 5 stars to a song rompr doesn't add that song to my collection.
the only way to add songs to my collection is by saving playlist.
furthermore sometimes doesn't play saved songs.
apologize for my english :)
thx

**Comment by fatg3erman** [comment]
Please send the debug information as a start.

![Screenshot 2020-06-28 at 09 32 26](https://user-images.githubusercontent.com/1430781/85942628-63a4e900-b922-11ea-9a79-805159657557.png)

**Comment by sinclaircornacchia** [comment]
* **BACKEND INFO**
  * **Version** 1.42
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host**
  * **proxy_password**
  * **proxy_user**
  * **spotify_token** [Redacted]
  * **spotify_token_expires** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.109
  * **SERVER_NAME** 192.168.1.109
  * **SERVER_SOFTWARE** Apache/2.4.41 (Ubuntu)
  * **DOCUMENT_ROOT** /var/www/server_development
  * **HTTP_HOST** 192.168.1.109
  * **HTTP_USER_AGENT** Mozilla/5.0 (Linux; Android 9; SM-G965F)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile
Safari/537.36
  * **REMOTE_ADDR** 192.168.1.102
  * **SERVER_PORT** 80
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **skin** phone
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **sortcollectionby** album
  * **player_backend** mopidy
* **PHP INFO**
  * **Version** 7.4.3
  * **mbstring** 7.4.3
  * **PDO** 7.4.3
  * **pdo_mysql** 7.4.3
  * **pdo_sqlite**
  * **curl** 7.4.3
  * **date** 7.4.3
  * **fileinfo** 7.4.3
  * **json** 7.4.3
  * **SimpleXML** 7.4.3
  * **GD** 7.4.3
  * **GD Info** GD Version=2.2.5, FreeType Support=1, FreeType Linkage=with
freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG
Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1,
BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=30, local_value=1800, access=4
  * **mbstring.language** global_value=neutral, local_value=neutral,
access=7
  * **memory_limit** global_value=128M, local_value=128M, access=4
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock,
local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir**
global_value=/var/www/server_development/rompr/prefs/temp,
local_value=/var/www/server_development/rompr/prefs/temp, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Artist, ArtistSort, Album, AlbumArtist, AlbumArtistSort,
Title, Track, Name, Genre, Date, Composer, Performer, Disc,
MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID,
MUSICBRAINZ_TRACKID, X-AlbumUri, X-AlbumImage
  * **Commands** add, addid, addtagid, channels, clear, clearerror,
cleartagid, close, commands, consume, count, crossfade, currentsong,
decoders, delete, deleteid, disableoutput, enableoutput, find, findadd,
idle, list, listall, listallinfo, listfiles, listmounts, listneighbors,
listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb,
mixrampdelay, mount, move, moveid, next, notcommands, outputs, password,
pause, ping, play, playid, playlist, playlistadd, playlistclear,
playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove,
playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random,
rangeid, readmessages, rename, repeat, replay_gain_mode,
replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek,
seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop,
subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe,
update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** file
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** internetarchive
  * **URL Handlers** m3u
  * **URL Handlers** radionet
  * **URL Handlers** rtsp
  * **URL Handlers** sc
  * **URL Handlers** somafm
  * **URL Handlers** soundcloud
  * **URL Handlers** tunein
  * **URL Handlers** youtube
  * **URL Handlers** yt
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **music_directory_albumart**
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media,
2=SoundCloud/Liked
  * **lastfm_country_code** IT
  * **country_userset** true
  * **debug_enabled** 6
  * **custom_logfile**
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location**
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=,
mopidy_slave=false, radioparams=[radiomode=, radioparam=, radiomaster=,
radioconsume=0]]
  * **dev_mode** false
  * **live_mode** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1593435738562
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory**
  * **collection_player** mopidy
  * **snapcast_server** 151.61.163.44
  * **snapcast_port** 1705
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** album
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **google_api_key**
  * **google_search_engine_id**
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **last_lastfm_synctime** 1592830861000
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 1592834906
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mopidy
  * **collectionrange** 0
  * **lastfm_user** [Redacted]
  * **lastfm_session_key** [Redacted]
  * **autotagname**
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** true
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** file
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** single
  * **chooser** infobar
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** true
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.42
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **user_lang** en
  * **synctags** true
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Modern-Dark
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains**
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1592833278574
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **bgimgparms** dummy=baby
  * **alarms**
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1592832940888
  * **playlistbuttons_isopen** false
  * **collectionbuttons_isopen** true
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1593281184091
  * **next_podcast_refresh** 1594950153530
  * **use_original_releasedate** false
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password**
  * **unix_socket**
  * **separate_collections** false
  * **collection_type** mysql
  * **collectioncontrolsvisible** true
  * **hide_pluginplaylistslist** true
  * **skin** phone
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode**
  * **radioparam**
  * **radiomaster**
  * **radioconsume** 0


Il Dom 28 Giu 2020, 10:33 Mark Greenwood <notifications@github.com> ha
scritto:

**Comment by fatg3erman** [comment]
So you don't have 'local' or 'spotify' backends enabled in Mopidy.

What are you listening to when you are rating a song as 5 stars?

**Comment by sinclaircornacchia** [comment]
From you tube

Il Lun 29 Giu 2020, 17:56 Mark Greenwood <notifications@github.com> ha
scritto:

**Comment by fatg3erman** [comment]
Mopidy-Youtube has a LOT of problems. This works for me but I'm running a heavily-patched version direct from github.

If you can get me a [Debug Log](https://fatg3erman.github.io/RompR/Troubleshooting#debug-logging) I can investigate for you.

**Comment by sinclaircornacchia** [comment]
* **BACKEND INFO**
  * **Version** 1.42
  * **mysql_database** [Redacted]
  * **mysql_host** [Redacted]
  * **mysql_password** [Redacted]
  * **mysql_port** [Redacted]
  * **mysql_user** [Redacted]
  * **proxy_host**
  * **proxy_password**
  * **proxy_user**
  * **spotify_token** [Redacted]
  * **spotify_token_expires** [Redacted]
* **SERVER INFO**
  * **PHP_SELF** /rompr/utils/debuginfo.php
  * **SERVER_ADDR** 192.168.1.109
  * **SERVER_NAME** 192.168.1.109
  * **SERVER_SOFTWARE** Apache/2.4.41 (Ubuntu)
  * **DOCUMENT_ROOT** /var/www/server_development
  * **HTTP_HOST** 192.168.1.109
  * **HTTP_USER_AGENT** Mozilla/5.0 (Linux; Android 9; SM-G965F)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Mobile
Safari/537.36
  * **REMOTE_ADDR** 192.168.1.102
  * **SERVER_PORT** 80
  * **REQUEST_URI** /rompr/utils/debuginfo.php
* **COOKIES**
  * **currenthost** Default
  * **skin** phone
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **sortcollectionby** album
  * **player_backend** mopidy
* **PHP INFO**
  * **Version** 7.4.3
  * **mbstring** 7.4.3
  * **PDO** 7.4.3
  * **pdo_mysql** 7.4.3
  * **pdo_sqlite**
  * **curl** 7.4.3
  * **date** 7.4.3
  * **fileinfo** 7.4.3
  * **json** 7.4.3
  * **SimpleXML** 7.4.3
  * **GD** 7.4.3
  * **GD Info** GD Version=2.2.5, FreeType Support=1, FreeType Linkage=with
freetype, GIF Read Support=1, GIF Create Support=1, JPEG Support=1, PNG
Support=1, WBMP Support=1, XPM Support=1, XBM Support=1, WebP Support=1,
BMP Support=1, TGA Read Support=1, JIS-mapped Japanese Font Support=
  * **ImageMagick** Installed
  * **date.timezone** global_value=, local_value=, access=7
  * **default_charset** global_value=UTF-8, local_value=UTF-8, access=7
  * **default_socket_timeout** global_value=60, local_value=60, access=7
  * **display_errors** global_value=, local_value=, access=7
  * **error_log** global_value=, local_value=, access=7
  * **error_reporting** global_value=22527, local_value=22527, access=7
  * **file_uploads** global_value=1, local_value=1, access=4
  * **log_errors** global_value=1, local_value=1, access=7
  * **max_execution_time** global_value=30, local_value=1800, access=4
  * **mbstring.language** global_value=neutral, local_value=neutral,
access=7
  * **memory_limit** global_value=128M, local_value=128M, access=4
  * **pdo_mysql.default_socket** global_value=/var/run/mysqld/mysqld.sock,
local_value=/var/run/mysqld/mysqld.sock, access=4
  * **session.use_cookies** global_value=1, local_value=1, access=7
  * **upload_tmp_dir**
global_value=/var/www/server_development/rompr/prefs/temp,
local_value=/var/www/server_development/rompr/prefs/temp, access=4
* **PLAYER INFORMATION**
  * **Connection Status** Connection Successful
  * **MPD Interface Version** 0.19.0
  * **tagtype** Artist, ArtistSort, Album, AlbumArtist, AlbumArtistSort,
Title, Track, Name, Genre, Date, Composer, Performer, Disc,
MUSICBRAINZ_ARTISTID, MUSICBRAINZ_ALBUMID, MUSICBRAINZ_ALBUMARTISTID,
MUSICBRAINZ_TRACKID, X-AlbumUri, X-AlbumImage
  * **Commands** add, addid, addtagid, channels, clear, clearerror,
cleartagid, close, commands, consume, count, crossfade, currentsong,
decoders, delete, deleteid, disableoutput, enableoutput, find, findadd,
idle, list, listall, listallinfo, listfiles, listmounts, listneighbors,
listplaylist, listplaylistinfo, listplaylists, load, lsinfo, mixrampdb,
mixrampdelay, mount, move, moveid, next, notcommands, outputs, password,
pause, ping, play, playid, playlist, playlistadd, playlistclear,
playlistdelete, playlistfind, playlistid, playlistinfo, playlistmove,
playlistsearch, plchanges, plchangesposid, previous, prio, prioid, random,
rangeid, readmessages, rename, repeat, replay_gain_mode,
replay_gain_status, rescan, rm, save, search, searchadd, searchaddpl, seek,
seekcur, seekid, sendmessage, setvol, shuffle, single, stats, status, stop,
subscribe, swap, swapid, tagtypes, toggleoutput, unmount, unsubscribe,
update, urlhandlers, volume
  * **Not Commands** config, kill
  * **URL Handlers** file
  * **URL Handlers** http
  * **URL Handlers** https
  * **URL Handlers** internetarchive
  * **URL Handlers** m3u
  * **URL Handlers** radionet
  * **URL Handlers** rtsp
  * **URL Handlers** sc
  * **URL Handlers** somafm
  * **URL Handlers** soundcloud
  * **URL Handlers** tunein
  * **URL Handlers** youtube
  * **URL Handlers** yt
* **CONFIG**
  * **rgbs** r=1, g=1, b=1, a=0.75
  * **music_directory_albumart**
  * **sortbycomposer** false
  * **composergenre** false
  * **composergenrename** 0=Classical
  * **preferlocalfiles** false
  * **mopidy_collection_folders** 0=Spotify Playlists, 1=Local media,
2=SoundCloud/Liked
  * **lastfm_country_code** IT
  * **country_userset** true
  * **debug_enabled** 8
  * **custom_logfile**
  * **cleanalbumimages** true
  * **do_not_show_prefs** false
  * **load_plugins_at_loadtime** false
  * **beets_server_location**
  * **multihosts** Default=[host=localhost, port=6600, password=, socket=,
mopidy_slave=false, radioparams=[radiomode=, radioparam=, radiomaster=,
radioconsume=0]]
  * **dev_mode** false
  * **live_mode** false
  * **collection_load_timeout** 3600000
  * **smartradio_chunksize** 5
  * **linkchecker_nextrun** 1594045325598
  * **linkchecker_isrunning** false
  * **linkchecker_frequency** 604800000
  * **linkchecker_polltime** 5000
  * **audiobook_directory**
  * **collection_player** mopidy
  * **snapcast_server** 151.61.163.44
  * **snapcast_port** 1705
  * **displaycomposer** true
  * **artistsatstart** 0=Various Artists, 1=Soundtracks
  * **nosortprefixes** 0=The
  * **sortcollectionby** album
  * **sortresultsby** albumbyartist
  * **actuallysortresultsby** albumbyartist
  * **google_api_key**
  * **google_search_engine_id**
  * **sync_lastfm_playcounts** false
  * **sync_lastfm_at_start** false
  * **last_lastfm_synctime** 1592830861000
  * **next_lastfm_synctime** 0
  * **lastfm_sync_frequency** 3600000
  * **lfm_importer_start_offset** 0
  * **lfm_importer_last_import** 1592834906
  * **sortbydate** false
  * **notvabydate** false
  * **currenthost** Default
  * **player_backend** mopidy
  * **collectionrange** 0
  * **lastfm_user** [Redacted]
  * **lastfm_session_key** [Redacted]
  * **autotagname**
  * **tradsearch** false
  * **lastfm_scrobbling** false
  * **lastfm_autocorrect** true
  * **sourceshidden** false
  * **playlisthidden** false
  * **infosource** file
  * **sourceswidthpercent** 25
  * **playlistwidthpercent** 25
  * **downloadart** true
  * **clickmode** single
  * **chooser** infobar
  * **hide_albumlist** false
  * **hide_filelist** false
  * **hide_radiolist** false
  * **hide_podcastslist** true
  * **hide_playlistslist** false
  * **hide_audiobooklist** false
  * **hide_searcher** false
  * **hidebrowser** false
  * **shownupdatewindow** 1.42
  * **scrolltocurrent** false
  * **alarm_ramptime** 30
  * **alarm_snoozetime** 8
  * **lastfmlang** default
  * **user_lang** en
  * **synctags** true
  * **synclove** false
  * **synclovevalue** 5
  * **theme** Numismatist.css
  * **icontheme** Modern-Dark
  * **coversize** 40-Large.css
  * **fontsize** 04-Grande.css
  * **fontfamily** Nunito.css
  * **displayresultsas** collection
  * **crossfade_duration** 5
  * **newradiocountry** countries/GB
  * **search_limit_limitsearch** false
  * **scrobblepercent** 50
  * **updateeverytime** false
  * **fullbiobydefault** true
  * **mopidy_search_domains**
  * **mopidy_radio_domains** 0=local, 1=spotify
  * **outputsvisible** false
  * **wheelscrollspeed** 150
  * **searchcollectiononly** false
  * **displayremainingtime** true
  * **cdplayermode** false
  * **auto_discovembobulate** false
  * **sleeptime** 30
  * **sleepon** false
  * **sortwishlistby** artist
  * **player_in_titlebar** false
  * **communityradioorderby** name
  * **browser_id** 1592833278574
  * **playlistswipe** true
  * **default_podcast_display_mode** 0
  * **default_podcast_refresh_mode** 4
  * **default_podcast_sort_mode** 0
  * **podcast_mark_new_as_unlistened** false
  * **use_albumart_in_playlist** true
  * **podcast_sort_levels** 4
  * **podcast_sort_0** Title
  * **podcast_sort_1** Artist
  * **podcast_sort_2** Category
  * **podcast_sort_3** new
  * **bgimgparms** dummy=baby
  * **alarms**
  * **lastversionchecked** 1.00
  * **lastversionchecktime** 1593440525492
  * **playlistbuttons_isopen** true
  * **collectionbuttons_isopen** true
  * **advsearchoptions_isopen** true
  * **podcastbuttons_isopen** false
  * **last_cache_clean** 1593547348799
  * **next_podcast_refresh** 1594950153530
  * **use_original_releasedate** false
  * **mpd_host** localhost
  * **mpd_port** 6600
  * **mpd_password**
  * **unix_socket**
  * **separate_collections** false
  * **collection_type** mysql
  * **collectioncontrolsvisible** true
  * **hide_pluginplaylistslist** true
  * **skin** phone
  * **maxrgbs** r=150, g=150, b=150, a=0.75
  * **bgdrgbs** r=1, g=1, b=1, a=0
  * **radiomode**
  * **radioparam**
  * **radiomaster**
  * **radioconsume** 0


Il Lun 29 Giu 2020, 19:20 Mark Greenwood <notifications@github.com> ha
scritto:

**Comment by fatg3erman** [comment]
I meant turn Debug Logging on and send me the log, not send me the same thing you've already sent. Please read the link again.

**Comment by sinclaircornacchia** [comment]
hi better late than never :D 
here the logtrace....
thx a lot
[logtrace.txt](https://github.com/fatg3erman/RompR/files/5119229/logtrace.txt)

**Comment by sinclaircornacchia** [comment]
youtube doesn't work for searching tracks....
but works for find videos....

**Comment by fatg3erman** [comment]
If mopidy-youtube isn't finding the tracks you want then that is not a Rompr problem. Like I say I'm running the develp branch of the patched version I referred to. That finds stuff but the search is wildly inaccurate. Like I say there's nothing I can do to make youtube's search work better, all I do is display what it returns.

**Comment by sinclaircornacchia** [comment]
Ok thx
I'm so sorry cause until few months ago It worked well with rompr ....


Il Lun 24 Ago 2020, 19:21 Mark Greenwood <notifications@github.com> ha
scritto:

**Comment by fatg3erman** [comment]
Like I say, it worked for me but ONLY when I use the develop branch of the fork I linked to. Youtube services update frequently, you need to keep mopidy up to date. Unfortunately mopidy development really isn't happening any more so using branches from github seems to be the only option currently.

The other thing I do with youtube is to use my own API key, which you can do if you're using the version I linked to,

I know mopidy-youtube is good, but unfortunately until the main mopidy developers take the new fork seriously it will take work on your part to keep it working. Don't expect that to change soon, I have outstanding pull requests on Mopidy that have been waiting nearly 2 years to be looked at.

**Comment by sinclaircornacchia** [comment]
You are so gentle to answer to me.
I think rompr is great and I can imagine how much work there's behind It
therefore saturday i'll make a donation for you.
A last question....does YouTube work better with Api key? Is Google custom
search engine necessary As well?

Il Lun 24 Ago 2020, 22:12 Mark Greenwood <notifications@github.com> ha
scritto:

**Comment by fatg3erman** [comment]
I don't really know. the version of mopidy-youtube I am using allows me to put an api key into mopidy.conf. I have done this, I can't remember why but there must have been a good reason. Like I say, have a look at the link to the fork I posted, he's doing great work and updates regularly. Thanks for the donation :)
